### ISSUE TITLE
Wrong Battery power

### ISSUE THREAD

**Issue by RahulRaktale** [kontaktio/kontakt-android-sdk#1]
The battery power for Beacon device sometimes gives -1 value for the battery power

**Comment by dawidgdanski** [comment]
Transmission power is read directly from advertising data. Are you sure that the value comes from kontakt.io's Beacon device?

**Comment by RahulRaktale** [comment]
Yes, the value was coming from Kontakt.io's beacon device but I am now using the latest version of the jar it's not coming now. At that moment, I was using Samsung Note 3 neo to test it. Well, anyways the issue seems to be resolved. 

I apologise for the late reply, I got caught up by the deadline for the project.
