### ISSUE TITLE
Application crashes if bluetooth service on turned off when the application is running

### ISSUE THREAD

**Issue by mahtavata** [kontaktio/kontakt-android-sdk#10]
You should handle a situation when bluetooth service is turned off when the application is running. Now the application crashes immediately. You can see in the stack trace the reason:

06-09 10:51:07.205  16112-16148/com.xxxx.app E/AndroidRuntime﹕ FATAL EXCEPTION: monitor-message-consumer-thread
    Process: com.xxxx.app, PID: 16112
    java.lang.IllegalStateException: BT Adapter is not turned ON
            at android.bluetooth.le.BluetoothLeUtils.checkAdapterStateOn(BluetoothLeUtils.java:136)
            at android.bluetooth.le.BluetoothLeScanner.stopScan(BluetoothLeScanner.java:145)
            at com.kontakt.sdk.android.factory.RunnersL$1.run(RunnersL.java:62)
            at com.kontakt.sdk.android.manager.MonitorController$Consumer.run(MonitorController.java:99)
            at java.lang.Thread.run(Thread.java:818)

I think you agree that this is blocker and should be fixed immediately. Perhaps adding a try / catch in the run might do the trick...

**Comment by dawidgdanski** [comment]
Hey @jkouos. Yes, we aware that manual bluetooth switch interruptions are causing unhandled exception being raised. Primarily we came with the assumption that the Bluetooth should be turned on when  BeaconManager is running. It was reported in #7, we are working to provide some enhancements on the SDK side.

Next release (about half of June) will bring some fixes.

**Comment by kwanzen** [comment]
We are currently having this same issue. Our clients are waiting for our update so we hope to see new version coming asap.
Thank you very much.

**Comment by dawidgdanski** [comment]
Hey @jkouos @mrmilk90. Apologies for a lack of contact for some time, busy times indeed. We've released a new version which fixes the bug. Check the kontakt-beacon-admin-sample-app. Thanks for reporting.
