### ISSUE TITLE
I need to get the nearest Beacon only

### ISSUE THREAD

**Issue by omarahm3** [kontaktio/kontakt-android-sdk#102]
Hi,
I need to get the nearest beacon from the device list in order to show specific content based on the nearest beacon ID.
how can i do this with Kontakt SDK?

**Comment by michaldrabik** [comment]
@omarking05 You can decide which device is closest to you by using `getDistance` from `RemoteBluetoothDevice`. This returns accuracy which is calculated according to algorithm described here: http://stackoverflow.com/questions/20416218/understanding-ibeacon-distancing
