### ISSUE TITLE
Beacon freeze when setting wrong password

### ISSUE THREAD

**Issue by hpinhal** [kontaktio/kontakt-android-sdk#103]
Good morning,

I am having some issues integrating your SDK v2.1.1 into my app.
For simplicity sake, I will be using your [beacon admin sample](https://github.com/kontaktio/kontakt-beacon-admin-sample-app) to explain my issue as it produces the same behaviour and I'm sure it's battle tested.

So, when connecting to a beacon with a correct password, it gives a Toast notifying it connected successfully, another one with "Authentication Success" and it shows the beacon data. All nice.
When using a wrong password, it will Toast "Connected" and then "Gatt error 19" instead of calling back to "Authentication Failure". After this error, scanning with a [third party app](https://play.google.com/store/apps/details?id=de.flurp.beaconscanner.app) I can find the beacon, but scanning with your SDK no beacons are found. Closing the app won't make it and neither restarting BT. I can only get the beacon found again if I take out the battery to restart the beacon.

Looking forward for your guidance.
Kind regards,
Helder Pinhal

**Comment by michaldrabik** [comment]
@HelderMPinhal This is an internal hardware security mechanism of our Beacons. After writing wrong password into the Beacon, it enters non-connectable mode for 20 minutes. The SDK doesn't recognize non-connectable beacons as "valid".

**Comment by hpinhal** [comment]
Okay, makes sense. Thank you.

On another matter, when updating the beacon values I am getting an error 9.
This is my code to set the values.

```
Config deviceConfig = new Config.Builder()
                .setProximityUUID(UUID.fromString(beacon.getUuid()))
                .setMajor(Integer.parseInt(beacon.getMajor()))
                .setMinor(Integer.parseInt(beacon.getMinor()))
                .build();

        deviceConnection.applyConfig(deviceConfig, new WriteBatchListener<IConfig>() {
            @Override
            public void onWriteBatchStart(IConfig batchHolder) {
                Log.i(LOG_TAG, "Updating device --> onWriteBatchStart");
            }

            @Override
            public void onWriteBatchFinish(IConfig batchHolder) {
                Log.i(LOG_TAG, "Updating device --> onWriteBatchFinish");
                //disconnect();
            }

            @Override
            public void onErrorOccured(int errorCode) {
                Log.i(LOG_TAG, String.format("Updating device --> onErrorOccured: %d", errorCode));
                //disconnect();
            }

            @Override
            public void onWriteFailure() {
                Log.i(LOG_TAG, "Updating device --> onWriteFailure");
                //disconnect();
            }
        });
```

**Comment by michaldrabik** [comment]
@HelderMPinhal What's your beacon's firmware version?

**Comment by hpinhal** [comment]
@michaldrabik 3.1

**Comment by michaldrabik** [comment]
Error 9 is a problem with TX_POWER write. There might be a bug in our SDK. Could you please add TX power explicitly into the config and try again: 

```
Config deviceConfig = new Config.Builder()
                .setProximityUUID(UUID.fromString(beacon.getUuid()))
                .setMajor(Integer.parseInt(beacon.getMajor()))
                .setMinor(Integer.parseInt(beacon.getMinor()))
                .setTxPower(5)
                .build();
```

**Comment by hpinhal** [comment]
@michaldrabik Now there is a callback to the device connection onCharacteristicsUpdated and then an error 12. Scanning the beacon shows the previous values and not the ones applied.

**Comment by michaldrabik** [comment]
@HelderMPinhal Sorry, in advance, for all the problems Helder seems there is actually a bug in the SDK. Error 12 refers to advertising interval. Could you once again add it explicitly and try again? 

```
Config deviceConfig = new Config.Builder()
                .setProximityUUID(UUID.fromString(beacon.getUuid()))
                .setMajor(Integer.parseInt(beacon.getMajor()))
                .setMinor(Integer.parseInt(beacon.getMinor()))
                .setTxPower(5)
                .setInterval(350)
                .build();
```

**Comment by hpinhal** [comment]
@michaldrabik It's alright. Setting those two values makes it work.

**Comment by michaldrabik** [comment]
@HelderMPinhal Great. We will fix this issue in the nearest SDK update. Thanks a lot for your help.
