### ISSUE TITLE
Not getting DEVICE_LOST in onEvent callback

### ISSUE THREAD

**Issue by ghost** [kontaktio/kontakt-android-sdk#104]
As the title says, I dont ever get `DEVICE_LOST` event in `onEvent` callback. I also tried restricting event types in `getScanContext` to `DEVICE_LOST` and `DEVICE_FOUND` events but still nothing. My SDK version is `2.1.1`. I am trying to calculate dwell time of a device in the vicinity of a beacon as you guys dont provide it and the `DEVICE_LOST` event is very necessary for that. 
Thanks, Any help is appreciated.

**Comment by michaldrabik** [comment]
@KashanDanish First of all, we have recently released version 2.1.2 which fixes some bugs regarding ranging and monitoring. Feel free to check it out:
 `compile 'com.kontaktio.sdk:kontakt-sdk:2.1.2'`

Also could you show ScanContext that you are using?

**Comment by ghost** [comment]
@michaldrabik thanks for replying. First of all project sync is failing with kontakt SDK version `2.1.2

```
Error:(56, 13) Failed to resolve: com.kontakt.sdk.android:kontakt.io-android-sdk:2.1.2
```

2nd, here is my `getScanContext` method

``` java
private ScanContext getScanContext()
    {
        if (scanContext == null)
        {
            scanContext = new ScanContext.Builder()
                    .setScanPeriod(ScanPeriod.RANGING) // or for monitoring for 15 seconds scan and 10 seconds waiting:
                            //.setScanPeriod(new ScanPeriod(TimeUnit.SECONDS.toMillis(15), TimeUnit.SECONDS.toMillis(10)))
                    .setScanMode(ProximityManager.SCAN_MODE_BALANCED)
                    .setActivityCheckConfiguration(ActivityCheckConfiguration.MINIMAL)
                    .setForceScanConfiguration(ForceScanConfiguration.MINIMAL)
                    .setIBeaconScanContext(new IBeaconScanContext.Builder().build())
                    .setEddystoneScanContext(new EddystoneScanContext.Builder().build())
                    .setForceScanConfiguration(ForceScanConfiguration.MINIMAL)
                    .build();
        }
        return scanContext;
    }
```

**Comment by michaldrabik** [comment]
@KashanDanish The dependency has changed since 2.1.2 because we now host artifacts at **jcenter**
You have `com.kontakt.sdk.android:kontakt.io-android-sdk:2.1.2` 
but it should be `com.kontaktio.sdk:kontakt-sdk:2.1.2` as I have written before.Let me know if that helps

**Comment by ghost** [comment]
Thanks for the correction. Now I am able to use the newer version but the `DEVICE_LOST` issue is still there. It is also not device specific. All my beacons profile is iBeacon, if that matters.

**Comment by michaldrabik** [comment]
@KashanDanish We will look into it and get back to you if we find something.

**Comment by ghost** [comment]
It was something on my side (mostly). What I was doing: I was showing a `Toast` on the first line in the case of `DEVICE_LOST`, which throws this exception

```
Can't create handler inside thread that has not called Looper.prepare()
```

which according to my understanding is saying that I cannot show `Toast` in a background thread. Okay, Understandable. The weird part is I am also showing `Toast` in all other cases of `onEvent` callback but they are working fine. Strange. I am able to process this event if I comment out the `Toast`. I can live without showing a toast so debug this if important. Thanks for help :)

**Comment by michaldrabik** [comment]
@KashanDanish That is good to know. You can always wrap your `Toast.make(...)` with `runOnUiThread()` to make sure it is being run on the main thread.
