### ISSUE TITLE
1.0.5 to 2.1.2

### ISSUE THREAD

**Issue by andrewindayang** [kontaktio/kontakt-android-sdk#107]
Hi guys,

I just notice that my app use 1.0.5 SDK. is there any documentation that I can follow to transform the SDK from 1.0.5 to 2.1.2? Thank you

Best,
Andrew

**Comment by michaldrabik** [comment]
@andrewindayang Try here: http://developer.kontakt.io/android-sdk/2.1.0/quickstart/#migration-from-kontakt-io-android-sdk-version-1-0-6

Or you can always just follow "Setup" and "Basic Usage" sections. It should be pretty easy to implement if migration points are not enough.

**Comment by andrewindayang** [comment]
beaconManager.startMonitoring();
beaconManager.stopMonitoring();
beaconManager.startRanging();
public void onBeaconAppeared(Constants.Region region, IBeaconDevice beaconDevice)
public void onRegionEntered(Constants.Region region)
public void onRegionAbandoned(Constants.Region region)
public void onMonitorStart()
public void onMonitorStop()
public void onBeaconsUpdated(Constants.Region region, List<IBeaconDevice> list)
public synchronized void onBeaconsDiscovered(Constants.Region region, List<IBeaconDevice> list)

Those method couldn't found on the library but it doesn't mention on the docs. Any Idea? @michaldrabik

**Comment by michaldrabik** [comment]
`BeaconManager` is now `KontaktProximityManager`. That's not only a name change but also implementation (many methods got removed or changed). I think the best way for you to migrate is to analyse `Basic Usage` examples (http://developer.kontakt.io/android-sdk/2.1.0/quickstart/#basic-usage-ranging-monitoring-beacons) and refactor your code with necessary changes.

**Comment by andrewindayang** [comment]
Hi @michaldrabik thanks for the quick reply and all those solution. by the way, may I know how I can print out the beacon UUID, major and minor from the beacon that my phone detect? because the RemoteBluetoothDevice are interface class and the Characteristics interface is inside RemoteBluetoothDevice interface. any solution?

**Comment by michaldrabik** [comment]
As stated in our docs:

``` java
@Override
    public void onEvent(BluetoothDeviceEvent bluetoothDeviceEvent) {
        List<? extends RemoteBluetoothDevice> deviceList = bluetoothDeviceEvent.getDeviceList();
        switch (bluetoothDeviceEvent.getEventType()) {
            case DEVICE_DISCOVERED:
                RemoteBluetoothDevice device = deviceList.get(0);
                Log.d(TAG, "found new beacon");
                break;
            case DEVICE_LOST:
                RemoteBluetoothDevice device = deviceList.get(0);
                Log.d(TAG, "lost device");
                break;
        }
    }
```
