### ISSUE TITLE
IntentService or Broadcast from ProximityListener.onEvent?

### ISSUE THREAD

**Issue by robachmann** [kontaktio/kontakt-android-sdk#108]
Is there a possibility to trigger an `IntentService` for every Event from the `ProximityManager.ProximityListener`? I would like to monitor beacons even while the app runs in the background and services are possibly killed by Android. My current setup looks like this:

```
public class BeaconService extends Service implements ProximityManager.ProximityListener {
    private ProximityManagerContract proximityManager;
    ...

    @Override
    public void onCreate() {
        if (!KontaktSDK.isInitialized()) {
            KontaktSDK.initialize(this);
        }
        if (proximityManager == null) {
            proximityManager = new KontaktProximityManager(this);
        }
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        proximityManager.finishScan();
        proximityManager.detachListener(this);
        proximityManager.disconnect();
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        final BeaconService beaconService = this;

        proximityManager.initializeScan(getScanContext(), new OnServiceReadyListener() {
            @Override
            public void onServiceReady() {
                proximityManager.attachListener(beaconService);
            }

            @Override
            public void onConnectionFailure() {
                Toast.makeText(BeaconService.this, "onConnectionFailure", Toast.LENGTH_SHORT).show();
            }
        });
        return START_STICKY;
    }

    @Override
    public void onEvent(BluetoothDeviceEvent bluetoothDeviceEvent) {
        List<? extends RemoteBluetoothDevice> deviceList = bluetoothDeviceEvent.getDeviceList();
        BeaconStateMachine.getInstance().beaconUpdate(this, deviceList);
    }

    private ScanContext getScanContext() {
        if (scanContext == null) {
            IBeaconScanContext iBeaconScanContext = new IBeaconScanContext.Builder()
                    .setDevicesUpdateCallbackInterval(TimeUnit.SECONDS.toMillis(1))
                    .setDistanceSort(DistanceSort.ASC)
                    .build();
            scanContext = new ScanContext.Builder()
                    .setScanPeriod(ScanPeriod.RANGING)
                    .setScanMode(ProximityManager.SCAN_MODE_BALANCED)
                    .setActivityCheckConfiguration(ActivityCheckConfiguration.MINIMAL)
                    .setForceScanConfiguration(ForceScanConfiguration.MINIMAL)
                    .setIBeaconScanContext(iBeaconScanContext)
                    .build();
        }
        return scanContext;
    }
}
```

I experience that the service sometimes is stopped by the OS and not started anymore (even with 'START_STICKY') and thus, the `ProximityListener` isn't firing events anymore. It's very hard to debug as this occurs after some hours of idling or during the night while charging. In my opinion the cleanest solution would be to trigger an `IntentService` for every event from `ProximityListener` or to use `Broadcast`s so the app doesn't have to run another service besides the `ProximityManagerContract`.

**Comment by michaldrabik** [comment]
There were some issues with Services START_STICKY on Android KitKat. Any chance you are working on 4.x.x OS?

Anyway, `IntentService` is more of a tool for "one-time" job so I don't like it here very much. You could work with `AlarmManager` to schedule a repeating broadcast that will try start your service every lets say 15 minutes, just in case. More here: http://www.vogella.com/tutorials/AndroidTaskScheduling/article.html#schedulestasks_alarmmanager

**Comment by robachmann** [comment]
My phone's on 6.0.0. Thanks for the hint, I'll look into the `AlarmManager`. I guess I should also implement a check on whether "your" (the Kontakt) service is still running.
