### ISSUE TITLE
Crash while doing Intent after found the beacon

### ISSUE THREAD

**Issue by andrewindayang** [kontaktio/kontakt-android-sdk#109]
while I am using new SDK, IbeaconDevice to get all of the list of the beacon. After I found the beacon that I am looking for from the list, I am trying to do an Intent and That my class is extends (java.io.Serializable) where it give me crash "Caused by: java.io.NotSerializableException: com.kontakt.sdk.android.ble.device.BeaconDevice" so should I extends parcelable?? or is there any other way?

**Comment by michaldrabik** [comment]
@andrewindayang Yes, BeaconDevice implements Parcelabe because its faster for Android. So you should stick to Parcelable or you can create your own wrapper that creates instance from BeaconDevice values and extends Serializable.

**Comment by andrewindayang** [comment]
Sorry about this, Can you show me what do you meant by wrapper that creates instance from BeaconDevice?

**Comment by michaldrabik** [comment]
You could create a class BeaconWrapper:

``` java
public class BeaconWrapper implements Serializable {

private final int major;
private final int minor;
...

public BeaconWrapper(BeaconDevice beaconDevice) {
this.major = beaconDevice.getMajor();
this.minor = beaconDevice.getMinor(); 
...
}
```

When you receive BeaconDevice from scan you can create this object and pass it in your Intent. But it is easier to stick with Parcelable in my opinion.

**Comment by andrewindayang** [comment]
thank you so much for your help.
