### ISSUE TITLE
Beacon detection inconsistancy

### ISSUE THREAD

**Issue by subbu1234** [kontaktio/kontakt-android-sdk#11]
Currently we are building app in both android and iOS using kontakt sdk for detecting Kontakt Beacons. Its working fine times and not working some times. There is inconsistency in beacons detection. Please provide solution. Thanks in advance.

**Comment by dawidgdanski** [comment]
There's nothing to be helpful with by reading your description. Could you please elaborate what is the problem?

**Comment by subbu1234** [comment]
we are using following code for configuration
beaconManager = BeaconManager.newInstance(this.getApplicationContext());
                beaconManager.setMonitorPeriod(MonitorPeriod.MINIMAL);
                beaconManager.setForceScanConfiguration(ForceScanConfiguration.DEFAULT);
                beaconManager.setDistanceSort(BeaconDevice.DistanceSort.ASC);  
                beaconManager.registerMonitoringListener(this.regionManager);

in listener we added the following events
onMonitorStart()
onMonitorStop()
onBeaconsUpdated(Region region, List<BeaconDevice> beaconDevices)
onBeaconAppeared(Region region, BeaconDevice beaconDevice)
void onRegionEntered(Region region)
void onRegionAbandoned(Region region)

Our application contains multiple beacons for each store. Each beacon can be identified by UUID major and minor. Sometimes these events firing. But sometimes not firing.  We tested in different scenarios
After launching the app some time events not firing. we tested in following scenarios

We tested with re-launching the app, not worked
We kill the app and re-install the app and tested, not worked
We switched-off and re-launched the device and tested. Worked well.

Please provide solutions to us. Very important in our application.

**Comment by dawidgdanski** [comment]
The BeaonManager's configuration part doesn't tell me anything neither. 

Notice the fact that there are some issues about Bluetooth in Android. Every now and then some Android devices get jammed and stop scanning. In fact, in the majority of cases we experienced such situation on Android 4.3 and 4.4. Changes in Android L seem to solve this issue.

**Comment by dawidgdanski** [comment]
Hey @subbu1234 what's the status of this issue?
