### ISSUE TITLE
After upgrading sdk to 2.1.2 becon discovery slowed down

### ISSUE THREAD

**Issue by grzegorzgolec** [kontaktio/kontakt-android-sdk#110]
After upgrading sdk from 2.0 to 2.1.2, beacons scanning got some kind of lag. Before upgrade they were discovered in about 300ms-500ms, now they are discovered after  4s. 

Scanner configuration is reather default, taken straight from docs examples.
Beacon firmware is 3.1. My test device is htc one m8 and galaxy s5.

**Comment by michaldrabik** [comment]
@grzegorzgolec No changes has been that would affect discover time so much. Also we haven't heard about such issues before. This might be related to immature BLE hardware stack on android in general on some devices. Try rebooting your devices and see if that helps. Also feel free to share your KontaktSDK related code here. Maybe we will find some issues. Regards

**Comment by arso8** [comment]
@grzegorzgolec is wi-fi enabled on device while scanning?
I figured out that active wi-fi may significant slow down scanning speed. @michaldrabik is there any workarounds for that?

**Comment by michaldrabik** [comment]
@arso8 We've noticed this. Unfortuneatly this is hardware related issue on certain devices and there's not much we can do about it.

**Comment by arso8** [comment]
@michaldrabik Maybe do you have some sort of list of problem devices? To ask their users turn off wifi. I noticed this issue on Xiaomi Redmi Note 3. Probably other devices with MediaTek Helio SoC have same problem?

**Comment by michaldrabik** [comment]
@arso8 Its not that simple :) For example I have have two exactly the same MOTO G devices and one of them works perfectly while the other has huge bluetooth problems... So you see this is an issue that goes down even to particular manufactured devices. Bluetooth on Android has always been immature and problematic (especially on lower-end devices) and we hope it will get better.

**Comment by arso8** [comment]
@michaldrabik ok, thanks for your reply, let's hope together :)

**Comment by michaldrabik** [comment]
Closing. Feel free to reopen if neccessary.
