### ISSUE TITLE
Scanning shuffled beacons and internet connection

### ISSUE THREAD

**Issue by nicolausYes** [kontaktio/kontakt-android-sdk#111]
As far as I understood, if we are going to scan shuffled beacons, during initialization of ProximityManager, SDK contacts your server to get the list of beacons.

At this moment, the android device can have a bad internet connection or don't have an internet connection at all.

SDK says that all initializations are successful and starts scanning, but can't find anything (maybe because it haven't received the list of beacons) and will not find anything in the future even if internet connection appears or become stable (because everything has been initialized already).

Can you confirm this behaviour?
If a device has bad internet connection during initialization of SDK's objects it will not be able to find shuffled beacons till reinitialization?
How to know that everything is ok during initialization? Any callbacks or returned values that will help to understand that everything should be reinitialized when a normal internet connection appears?

How to check.
1. Disable internet connection (turn off wifi or mobile internet).
2. Run sample app.
3. On some pages like Range beacons or Range all types you will see your beacon.
4. Select Scanning shuffled beacons. No beacons.
5. Enable internet connection.
6. Reselect Scanning shuffled beacons to reinitialize objects.
7. You will see a shuffled beacon.

**Comment by michaldrabik** [comment]
The SDK tries to resolve shuffled beacons not during initialization but at the moment when they are discovered on Bluetooth level (Firstly it tries to resolve it from local cache. If it's not there API call is being made and if its successful beacon is resolved and cache updated).

 This means that you can initialize scan without internet connection and keep it going without fear that even when internet comes back shuffled beacons won't be detected.

**Comment by nicolausYes** [comment]
Thanks for explanations. Became clearer.
