### ISSUE TITLE
Filter shuffled beacons by UUID

### ISSUE THREAD

**Issue by nicolausYes** [kontaktio/kontakt-android-sdk#112]
I've got problems filtering shuffled beacons by UUID.

When I'm scanning for shuffled beacons **without** filtering, I "see" the device without problems.
I don't "see" the device and not receiving any events from it when applying UUID IBeacon filter during the creation of IBeaconScanContext.

The device is functioning correctly. It has firmware version 4.0 and shuffling enabled. I see this device in your sample app on the "Scanning shuffled beacons" screen and in my application when not applying filtering. I use Proximity UUID from the web panel (which is the same as the Proximity UUID on the "Scanning shuffled beacons" screen in your sample app) for filtering.

The creation of IBeaconScanContext:

```
this.beaconScanContext = new IBeaconScanContext.Builder()
                .setEventTypes(this.eventTypes) // all events
                .setDevicesUpdateCallbackInterval(TimeUnit.SECONDS.toMillis(Constants.BEACON_UPDATE_CALLBACK_INTERVAL)) // 10 seconds
                .setIBeaconFilters(Collections.singleton(IBeaconFilters.newProximityUUIDFilter(UUID.fromString("f7826da6-xxxx-4e98-8024-bc5b71e0893e")))) // xxxx - replaced
                .setDistanceSort(DistanceSort.ASC)
                .build();
```

<hr/>

Any suggestion what can be wrong? Or the correct way of doing that? Is it generally supported?

SDK version: `2.1.2`
Device: `Nexus 5`
OS version: `4.4.4 Kit Kat`

**Comment by michaldrabik** [comment]
When  beacon is shuffled it broadcasts UUID located in "Security" tab in the web panel is this the one you are setting in the UUID filter?

**Comment by nicolausYes** [comment]
Currently, I don't have full access to the account and don't see the tab you are talking about, but I think I'm using the correct UUID.

It is here:
![1](https://cloud.githubusercontent.com/assets/865548/15486194/95dc8bfc-214c-11e6-986d-655b5163e002.jpg)

And here:
![2](https://cloud.githubusercontent.com/assets/865548/15486195/95df7be6-214c-11e6-9088-dc6f6200fb4c.jpg)

On "Range beacons" screen in you sample app, there is a different UUID, I'm **not** using that.
![3](https://cloud.githubusercontent.com/assets/865548/15486193/95d9ab1c-214c-11e6-86a6-c075a63eaec6.jpg)

**Comment by michaldrabik** [comment]
@nicolausYes The UUID that you see in your web panel is "real" UUID of your shuffled Beacon. But, because the beacon is shuffled it broadcasts different UUID called "secure UUID" (this is the one you see in Range Beacons screen). The "Scanning shuffled beacon" screen shows "real" UUID because it resolves it using our REST API. See [THIS SECTION](http://developer.kontakt.io/android-sdk/2.1.0/quickstart/#security-shuffling) for the example. We ask API for list of proximities and we use them to set Regions but filters will be analogous. Hope this will clear things up

**Comment by nicolausYes** [comment]
@michaldrabik ooh, got it. In order to filter by UUID, I have to make an API call to get a list of IProximityUUID. Then I should create a list of "secure" UUIDs that matches my "real" UUIDs. And use this list of "secure" UUIDs for filtering.

One more question. If I use KontaktProximityManager and use my API key (in AndroidManifest), I'll get events only from my beacons, right? I will not receive events from other beacons.

**Comment by michaldrabik** [comment]
@nicolausYes You will receive events from all Kontakt.io beacons.

**Comment by nicolausYes** [comment]
@michaldrabik wait. If I'm using your sample app, I always see beacons on "Range beacons" screen but don't see beacons on "Scanning shuffled beacons" screen until I put correct API key to AndroidManifest. 

From that behaviour I've made a conclusion, if I use KontaktProximityManager and my API key, then only my beacons are resolving and I receive events only from my beacons, not all. If it's not correct, why I'm not able to see beacons on "Scanning shuffled beacons" screen before I put correct API key to the AndroidManifest?

**Comment by michaldrabik** [comment]
@nicolausYes Oh ok so I assume all of beacons around you are shuffled. Then yes "Scanning Shuffled Beacons" screen won't show any results because resolving fails due to lack of API KEY. If the resolving fails shuffled beacon is not reported in the event. "Range Beacons" screen uses ProximityManager instead of KontaktProximityManager. ProximityManager doesn't even try to handle shuffled beacons it only reports what it sees.

**Comment by michaldrabik** [comment]
@nicolausYes So following up on your previous question. If there are Kontakt.io beacons around you and they are not yours (lets say they are your freind's) there are 2 options: If they are shuffled they wont be reported in onEvent callback. If they are NOT shuffled they will be reported in onEvent.

**Comment by nicolausYes** [comment]
@michaldrabik so if I need to work only with my shuffled beacons I still have to use filter mechanism? Because I will NOT receive events from other shuffled beacons, but I WILL receive events from other Kontakt.io beacons that are not shuffled (even using KontaktProximityManager). Right?

**Comment by michaldrabik** [comment]
@nicolausYes Yes. In my opinion the easiest way is to set all your beacons to the same Proximity UUID of your choice and then just apply filter or region fo this UUID as we talked before. THen you will be sure that all reported events contains only your beacons. Also you might consider turning off shuffling if your use case doesn't really need it. This will simplify the process.

**Comment by nicolausYes** [comment]
@michaldrabik described easy way is applicable only for not shuffled beacons, right? Because when they are shuffled, it's now allowed to set Proximity UUID manually.

**Comment by michaldrabik** [comment]
@nicolausYes If all your beacons have the same "real" UUID then the shuffled ones will also be the same. You can check that in the web panel

**Comment by nicolausYes** [comment]
@michaldrabik thanks for help!
