### ISSUE TITLE
Range Beacons every 1 second

### ISSUE THREAD

**Issue by bshikhar13** [kontaktio/kontakt-android-sdk#116]
Hi, My use case need to scan (range) beacons for 1 second and then 1 second passive mode. After the end of every 2 seconds, I want to find the closest beacon to the phone. The closest beacon id will then be sent to server by a socket and processed.

How can this custom ranging scheme (1 second active and 1 second passive) be implemented.

**Comment by michaldrabik** [comment]
Minimal active scan period is 3 seconds. Minimal passive period is 2 seconds. However you can use Java or Android components like `Handler`, `AlarmManager` or others to start scan for 2 seconds, collect devices, stop scan, find closest beacon and send it to server, repeat.

**Comment by bshikhar13** [comment]
@michaldrabik  Thanks for the reply! But I cannot understand how to implement this in `IBeaconListener callbacks`. Please help me out.
