### ISSUE TITLE
Beacon distance inconsistancy

### ISSUE THREAD

**Issue by subbu1234** [kontaktio/kontakt-android-sdk#12]
We are using Kontakt sdk for detecting beacons in our applications. We observed that distance not showing correctly. Its varying every time even though we are in same place ( with out moving ).

**Comment by dawidgdanski** [comment]
Hey @subbu1234 , the distance is heavily dependent on the Rssi value which is calculated by the System. The Rssi control is one of the things we are working on. In v1.0.6 there is a possibility to leverage the distance by providing customized method of Rssi calculation. During `BeaconManager`'s configuration part you can set custom `RssiCalculator` and thus make the distance variations smoother. By default, the SDK provides [LimitedMeanRssiCalculator](http://kontaktio.github.io/Android-SDK/Javadoc/com/kontakt/sdk/android/data/RssiCalculators.LimitedMeanRssiCalculator.html) calculating Rssi value based on `n` previous Rssi values so I think this may help you somehow.
 Alternatively, you can provide your own [CustomRssiCalculator](http://docs.kontakt.io/android-sdk/javadoc/com/kontakt/sdk/android/data/RssiCalculators.CustomRssiCalculator.html).

**Comment by dawidgdanski** [comment]
Hey @subbu1234  what's the status of this issue?
