### ISSUE TITLE
problems to update from 2.1.2 to 3.1.1

### ISSUE THREAD

**Issue by josean5665** [kontaktio/kontakt-android-sdk#122]
Hi I really have problems to update my project to the new version 3.1.1 or 3.0.0

On my project I initialise the kontakt on the main activity , and them I made a singleton class like a manager to call in any place on the project. 
But when update the kontakt version I really have problems:

For example with the version 3.1.1 this import is not recognised:

import com.kontakt.sdk.android.ble.configuration.scan.IBeaconScanContext;  

And I have problems with other methods 

.restartScan(scanContextMap.get(uuid));
.finishScan();

 return new ScanContext.Builder()
                **.setScanPeriod(new ScanPeriod(TimeUnit.SECONDS.toMillis(5), 0))**
                **.setIBeaconScanContext(new IBeaconScanContext.Builder()**
                        .setIBeaconFilters(Collections.singleton(new ProximityUUIDFilter(UUID.fromString(uuid))))
                        .setEventTypes(EnumSet.of(EventType.DEVICES_UPDATE))
                        .setRssiCalculator(RssiCalculators.newLimitedMeanRssiCalculator(5))
                        .build())
                **.setScanMode(ProximityManager.SCAN_MODE_BALANCED)**
                .build(); 

  @Override
        protected Void doInBackground(Void... params) {
            final ProximityManagerWrapper proximityManagerWrapper = new ProximityManagerWrapper(distance, uuid, proximityManager);
            proximityManagerWrapperList.add(proximityManagerWrapper);
            **proximityManager.initializeScan(scanContextMap.get(uuid), new OnServiceReadyListener()** {
                @Override
                public void onServiceReady() {
                    **proximityManager.attachListener(new ProximityManager.ProximityListener() {**
                        @Override
                        public void onScanStop() {

```
                    }
```

Please if you can help me....

**Comment by stoprocent** [comment]
Before we can help please put your code inside code block so it is more readable.

**Comment by josean5665** [comment]
Hi this is the source code, I use this manager to star and stop the scan of beacons and run in background. But when a try to update a have some problems with some context methods and others. 
Please if you can help me with this a really appreciate..

Best Regards
Jose Jimenez

[ProximityFrameworkManager.java.zip](https://github.com/kontaktio/kontakt-android-sdk/files/452414/ProximityFrameworkManager.java.zip)

**Comment by michaldrabik** [comment]
With SDK going from version 2.1 to 3.x we have made a lot of changes to the API and the way of how the SDK should be used (for example: ScanContext is no longer used). 

My advise is to review the 3.1.1 docs: http://developer.kontakt.io/android-sdk/3.1.1/quickstart/ and modify your code accordingly.

**Comment by josean5665** [comment]
Yes I tried to update my code with the Quick start. But this Quick Start is very general and for example in the Quick start never explain how to set the distance that I want to beacon is found. 

Thanks for your help...

**Comment by josean5665** [comment]
For example with the new version how can I use the ProximityManagerWrapper to set the distance

**Comment by michaldrabik** [comment]
@josean5665 What distance. Do you only want to scan for beacons that are closer than a specific distance?

**Comment by josean5665** [comment]
Correct in my proyect I have two types of scan.

The first is all the beacons, this scan is on background.

The second scan is when the user press a button to scan a specific beacon
of at 7 cm of distance..

The events for this two types of scan are difference, the first type I only
need the update event.

But for the second type a I need the update, space entered, space
abandoned..

In the version 2.1.2 all this works. Because I set a ScanContext with the
events and then instantiated the ProximityManager, with another class....
But with the version 3.0.0 I really have problems with this.

2016-09-05 13:16 GMT-06:00 Michal Drabik notifications@github.com:
