### ISSUE TITLE
Getting notified twice for first beacon seen

### ISSUE THREAD

**Issue by bernharda** [kontaktio/kontakt-android-sdk#124]
Since I've updated from version 3.0.0 of the SDK to 3.1.1, I'm receiving the first beacon seen twice. So the `onIBeaconDiscovered` callback method gets called twice in a row with same region and same beacon. The following beacons are notified only once.

**Comment by michaldrabik** [comment]
Could you post your Proximity Manager configuration (also filters, regions if u use them). Also what Android version are you testing on? Regards

**Comment by bernharda** [comment]
Proximity Manager configuration:
        proximityManager.configuration()
                .scanMode(ScanMode.BALANCED)
                .scanPeriod(ScanPeriod.create(TimeUnit.SECONDS.toMillis(6), TimeUnit.SECONDS.toMillis(BACKGROUND_SCANNING_INTERVALL)))
                .deviceUpdateCallbackInterval((int) TimeUnit.SECONDS.toMillis(5))
                .monitoringEnabled(true)
                .monitoringSyncInterval(10);

Region Filter:
        region = new BeaconRegion.Builder()
                .setProximity(UUID.fromString(StaticUtils.getBeaconUUID(getApplicationContext())))
                .setMajor(BeaconRegion.ANY_MAJOR) //any major, default value
                .setMinor(BeaconRegion.ANY_MINOR) //any minor, default value
                .build();
        beaconRegions.add(region);
        proximityManager.spaces().iBeaconRegions(beaconRegions);

I've tested this on Android 5.1.1 & Android 6.0.1

**Comment by michaldrabik** [comment]
@bernharda I'm having trouble reproducing this bug. Everything seems to work fine. Could you see if this happens (doubled onIBeaconDiscovered event) when you change scanPeriod to RANGING or don't use regions at all.

Maybe there is a chance that there is something else in your code that could cause this?

Regards

**Comment by bernharda** [comment]
Hi Michal, thanks for pointing that! I found the reason for this behaviour now:
I initially start scanning in "monitoring mode" and in the onRegionEntered callback I change the scanPeriod to ranging and restart scanning. That's why onIBeaconDiscovered gets called a second time immediately. I'm of the opinion that this wasn't the case with SDK Version 3.0.0 but obviously it's my fault.
Do you have any best practices how to switch scan modes on entering a region without restarting scanning or having to worry about receiving first beacon twice?

Thanks & BR

**Comment by michaldrabik** [comment]
First thing that comes to my mind would be to set some mock iBeaconListener that will do nothing at all  when in 'monitoring' mode and when you change to 'ranging' you can set up your actual iBeacon listener and start scanning.

The other option might be setting up some boolean flag indicating if you are in ranging or monitoring mode and just ignore all iBeacon callbacks when this flag indicates monitoring mode.
