### ISSUE TITLE
Inline Documentation not up to date

### ISSUE THREAD

**Issue by cboisen** [kontaktio/kontakt-android-sdk#127]
Hi Guys

I'm currently updating to version 3.1.1 (from version 2 of the SDK), and I notice some inconsistencies in your inline documentation. It's typically arguments naming that has changed, or default values that have changed, but the docblocks arent updated.

Here is an example from ScanPeriod where your default values have changed, but the documentation hasn't: https://gist.github.com/hauthorn/0eb0fe454151c92a6d1de1461eb7f011

Another example is in ForceScanConfiguration, where ForceScanConfiguration.DEFAULT is actually called ForceScanConfiguration.MINIMAL

It's not a huge issue, but it might cause confusion.

**Comment by michaldrabik** [comment]
@hauthorn Thanks for the tip! We'll re-review our docs before next release.
