### ISSUE TITLE
SDK Internet Issue

### ISSUE THREAD

**Issue by spot-anmol** [kontaktio/kontakt-android-sdk#129]
I have made an activity where I just start the scanner using the SDK provided by Kontact.
I have followed all the instruction as mentioned on "http://developer.kontakt.io/android-sdk/3.1.1/quickstart/"
The permissions are mentioned there as:
Step 2: Permissions

Interacting with beacons requires following permissions for different aspects of library:

<uses-permission android:name="android.permission.BLUETOOTH"/>
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
BLUETOOTH - needed for ranging/monitoring devices
BLUETOOTH_ADMIN - needed for connecting to devices
INTERNET & ACCESS NETWORK STATE - needed for Kontakt Cloud communication.
As it is clearly mentioned that the internet ins needed for Kontakt Cloud communication and only Bluetooth and Bluetooth_Admin are required for ranging, monitoring etc.
In my app there is a separate button (BUTTON CLOUD) through which I communicate to the Kontact Cloud and another separate button (BUTTON BLE)to start ranging and monitoring. 
My beacons have the shuffling mode ON
I firstly press the BUTTON CLOUD to get the uuid, major and minor for that particular UID of the Kontact beacon that i have stored in the app.
The issue is that after this when I press the BUTTON BLE in order to start the scanner, it is not able to find the beacons if the phone is not connected to the internet, as soon as I turn on the internet it works completely fine.
My concern is that on press of BUTTON BLE I am not contacting the cloud and doing the ranging and monitoring which requires only the :
<uses-permission android:name="android.permission.BLUETOOTH"/>
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>

So why won't the ranging/monitoring happen without an internet connection?
Please get back to me as soon as possible.

**Comment by michaldrabik** [comment]
@anmol94gupta Are your beacons shuffled?

**Comment by spot-anmol** [comment]
@michaldrabik Yes 
My beacons are in shuffling mode
though I am detecting them on the bases of the original proximity uuid that I get from Kontact cloud (on click of BUTTON CLOUD)
and not on the bases of the shuffled uuid and major/minor values

**Comment by anmol94gupta** [comment]
@michaldrabik Please let me know if you are not able to understand my question/issue clearly

**Comment by michaldrabik** [comment]
The SDK will take care of unshuffling them for you. No need to call Cloud explicitly.

The first time a shuffled beacon is scanned, SDK unshuffles the beacons using the Cloud and caches future shuffles on the disk. So you only need the internet connection for the first time.

When shuffled beacon is discovered for the first time and internet is not available and nothing is cached on the disk it won't be reported as discovered.

**Comment by spot-anmol** [comment]
@michaldrabik Tell me one thing. For instance let's suppose that the I am not in range of my shuffled beacon but I know its Unique Id. So if I contact the Cloud explicitly (while NOT IN RANGE of the beacon) in order to get the future shuffles and other stuff. It won't work and the beacon won't get reported when I come in range of the beacon and try to range/monitor it on the bases of my stored values, Right?
Also when I come in range of the beacon I would be required to again be connected to the internet and contact the Cloud in order to enable the SDK to unshuffle the detected beacon using Cloud or otherwise it won't get discovered.

**Comment by spot-anmol** [comment]
@michaldrabik Sorry I accidentally closed the issue. Please check my last post

**Comment by michaldrabik** [comment]
@anmol94gupta Yes. The first time you enter the range of shuffled beacon you need to have internet connection to unshuffle it and get notified in onDiscovered callback. After that the future shuffles are cached and no internet connection is needed. You can't "preload" future shuffles into the SDK by yourself.

I hope it's clear now?

**Comment by spot-anmol** [comment]
@michaldrabik Yeah its almost clear. One last question, can i access the cache through code somehow and check whether the information for that Unique ID is available or not and based on that then I would be able to show the user to whether turn on the internet or not.
Thank you

**Comment by michaldrabik** [comment]
You can't, but if all your beacons are shuffled then you should just check internet connection before starting a scan and inform user then.

**Comment by spot-anmol** [comment]
Thanks a lot for your support Michal. Just one last thing, is there a limit on the cache that it can only cache info. of limited number of beacons or for limited number of days or something else of this sort?

**Comment by michaldrabik** [comment]
By default shuffles change every 24 hours and 7 shuffles are cached. So aprox. 1 week ahead. Then it will try to download new set of shuffles again.

**Comment by spot-anmol** [comment]
Thankyou
