### ISSUE TITLE
Signal interval

### ISSUE THREAD

**Issue by subbu1234** [kontaktio/kontakt-android-sdk#13]
We are using following code for beacon configuration
 beaconManager = BeaconManager.newInstance(this.getApplicationContext());
                beaconManager.setMonitorPeriod(MonitorPeriod.MINIMAL);  
                beaconManager.setForceScanConfiguration(ForceScanConfiguration.DEFAULT);
                beaconManager.setDistanceSort(BeaconDevice.DistanceSort.ASC);
                beaconManager.registerMonitoringListener(this.regionManager);
We are setting monitor period as MonitorPerion.MINIMAL;
What would be the best monitor period for improving beacon detection accuracy?

**Comment by dawidgdanski** [comment]
In v1.0.6 the shortest monitor period is the `MonitorPeriod.MINIMAL`. This restriction, however, will be reduced in the next version. 

If you want to receive region-aware notifications then your configuration is correct at the moment. If you're focused primarily on beacon accuracy detection then I suggest switching to ranging.

**Comment by subbu1234** [comment]
We found that ranging works only in foreground. But we need to develop application which works in both foreground and background also.

**Comment by dawidgdanski** [comment]
Download and launch the sample application in order to see the approach we've come up with to handle both foreground and background scan.
