### ISSUE TITLE
transformClassesWithDexForDebug ERROR

### ISSUE THREAD

**Issue by disheltCiti** [kontaktio/kontakt-android-sdk#132]
Hi!

I am using Kontakt SDK 3.1.1 and I got this exception:

Error:FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:transformClassesWithDexForDebug'.
  
  > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/kontakt/sdk/android/BuildConfig;
- Try:
  Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

I tried with `multiDexEnabled true`, but I got:

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.

> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/kontakt/sdk/android/ble/broadcast/BluetoothStateChangeReceiver.class

My build.gradle is:

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.3"
    defaultConfig {
        applicationId "citi.myapplication"
        minSdkVersion 19
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled false
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.kontaktio:sdk:3.1.1'
    testCompile 'junit:junit:4.12'
}`

Hope you can help me!

Regards

**Comment by michaldrabik** [comment]
@disheltCiti I understand that this is a fresh new project and you only added `com.kontaktio:sdk:3.1.1` dependency. Do you use any other `jar` libraries?
