### ISSUE TITLE
Proximity Manager's scan status listener swallows errors

### ISSUE THREAD

**Issue by jaymes-bearden** [kontaktio/kontakt-android-sdk#133]
It appears that the ScanStatusListener set in the proximity manager is running on the background thread and swallows errors.

What I had was the following:
```
proximityManager.setScanStatusListener(new SimpleScanStatusListener() {
    @Override
    public void onMonitoringCycleStart() {
        binding.progressBar.setVisibility(View.VISIBLE);
    }

    @Override
    public void onMonitoringCycleStop() {
        binding.progressBar.setVisibility(View.GONE);
    }
});
```

This resulted in the progress bar being hidden after a monitoring cycle stopped BUT the handler for start would never be called again. The usual 'cannot modify ui from background thread' exception did not appear; however, when I changed to explicitly run this code on the UI thread, the handler continued to be called.

Can you updated the `com.kontakt.sdk.android.ble.manager.internal.EventObserver` and wrap all the listener call backs in a try catch?

Thank you!

**Comment by michaldrabik** [comment]
@jaymes-bearden Thanks for reporting that. 

Instead of try-catching though those callbacks should actually be reported on the same thread the ProximityManager is instancied on. We will modify this behaviour
