### ISSUE TITLE
Multiple Enter-Exit events

### ISSUE THREAD

**Issue by sabirmanandhar** [kontaktio/kontakt-android-sdk#135]
I followed the quick start guide for andorid SDK for IBeacon protocol with following configuration

```
proximityManager.configuration()
                .activityCheckConfiguration(ActivityCheckConfiguration.DEFAULT)
                .scanPeriod(ScanPeriod.create(TimeUnit.SECONDS.toMillis(10), TimeUnit.SECONDS.toMillis(20)))
                .scanMode(ScanMode.BALANCED);
```

Created a region and created spaces and created an space listener... but even i am stationary and in very close range to beacons, i am getting _onRegionEntered()_ and _onRegionAbandoned()_ events frequently every few seconds.

Also creating a iBeaconListener,  _onIBeaconDiscovered() and onIBeaconLost()_ are trigerred every few seconds..

Thus is gives an impression that every few intervals, the beacons are not detected or are lost.

Could you suggest how can this be made more stable so false _onRegionAbandoned() or onIBeaconLost()_ events are not fired when in range with beacons ?

**Comment by michaldrabik** [comment]
@sabirmanandhar This could be connected to your beacon's settings or phone BLE scanner quality. What is an adv. interval and TX power of your beacons, also what device and android version are you using.?

**Comment by sabirmanandhar** [comment]
I am testing using 
**Double battery beacon**
   adv interval: 350ms
   TX Power: 3(-12 dBm)
   Format iBeacon
**USB powered beacon**
   adv interval: 100ms
   TX Power: 4(-8 dBm)
   Format iBeacon

Tested using 

Motorola Moto G (2nd Generation)
Android version : 6.0 

Samsung Galaxy note 5 
Android version : 6.0.1

Both beacons are very close to mobile device.

Also I noticed that when a lost event happens.. then all beacons get lost event at once.

**Comment by michaldrabik** [comment]
@sabirmanandhar Unfortunately MOTO G 2nd is famous for its faulty bluetooth :) Is there any chance you can test your code on other devices?

Also you might want to try enabling force scan `.forceScanConfiguration(ForceScanConfiguration.MINIMAL)
` in proximity manager configuration and see if that helps.

**Comment by sabirmanandhar** [comment]
Added .forceScanConfiguration(ForceScanConfiguration.MINIMAL) in proximity manager

Also tested on Samsung galaxy Note 5 (Android 6.0.1).. but its still not working as expected and the behavior is still same in both phones for both beacons..

As mentioned.. when onRegionAbandoned() or onIBeaconLost() event is received, it is getting received for both beacons simultaneously in both phones (moto g and samsung note)

**Comment by michaldrabik** [comment]
We need to eliminate the possibility of faulty beacon hardware then. 

Could you please install nRF Connect app (https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp) and start the scanning there. Then swipe the list to the right and there will be a received signal strength chart(you can see it in one of the screencaps in the PlayStore). 

Keep the scanning running for a minute or so and see if there are any long gaps there that would indicate that the phones are not receiving signal from beacon.

Regards

**Comment by sabirmanandhar** [comment]
Checked with nRF application, the graph for signal strength seems good...attached is the graph screen shot.

I have having some doubts if there is something wrong with SDK as like mentioned before when I receive onIBeaconLost(), it is received for all the beacons 

![screenshot_2016-11-10-17-49-31](https://cloud.githubusercontent.com/assets/4929742/20176178/abeb9174-a76e-11e6-8f67-a26745ed6cdf.jpg)

**Comment by michaldrabik** [comment]
I forgot to ask which SDK version do you use.

**Comment by sabirmanandhar** [comment]
Compiled with android API level 23
Kontakt Android SDK : 3.1.1

**Comment by michaldrabik** [comment]
@sabirmanandhar We might have reproduced the bug. Could you change ScanPeriod to RANGING and see if it still happens. It should not.

**Comment by sabirmanandhar** [comment]
Tried with ScanPeriod to RANGING .. but i am still getting the false exit event.....but its a bit less frequent.

it is now getting more onIBeaconsUpdated() event until it does not and then we get onIBeaconLost().

**Comment by michaldrabik** [comment]
I've made some fixes and uploaded them to BETA channel. Official release will be somewhere next week. Please, feel free to test it out by changing your dependency to 3.2.0 RC and adding repository path in your `build.gradle`:

```
repositories {
  maven {
    url "http://dl.bintray.com/kontaktio/maven"
  }
}

dependencies {
  compile fileTree(include: ['*.jar'], dir: 'libs')
  compile 'com.android.support:appcompat-v7:24.2.1'

  compile 'com.kontaktio:sdk:3.2.0-RC1'

}

```

**Comment by sabirmanandhar** [comment]
ok thanks..!! it seems sdk:3.2.0-RC1 works a lot better.

Somehow I am getting error while creating Region though.. i will check if I am doing something wrong..I did noticed some change in API names.

**Comment by sabirmanandhar** [comment]
Checked the sample application
https://github.com/konradkontakt/Android-Kontaktio-Beacon-Health-Service

I think untill i create spaces and put space listener, it works better but after that it starts giving false exits..

Also i noticed this is using com.kontaktio:sdk:3.1.1' while earlier i was suggested to use com.kontaktio:sdk:3.2.0-RC1.

After changing to com.kontaktio:sdk:3.2.0-RC1, i can see some improvements but still there is some times false exits.. but not that frequent..

Sources changed: 
[Service.zip](https://github.com/kontaktio/kontakt-android-sdk/files/594077/Service.zip)

**Comment by michaldrabik** [comment]
@sabirmanandhar com.kontaktio:sdk:3.2.0-RC1 is just a snapshot version. Official release is coming this week.

One more thing you can try is to set custom activity check values.
Assuming your scanPeriod values are 10/20 seconds try configuring `ActivityCheckConfiguration.create(TimeUnit.SECONDS.toMillis(15), TimeUnit.SECONDS.toMillis(8))`.

This will give your devices a little bit more time to catch beacon's frame and could help with false exits.
