### ISSUE TITLE
ProximityListener in new SDK.

### ISSUE THREAD

**Issue by mail2bhramar** [kontaktio/kontakt-android-sdk#136]
What is the similar interface in new sdk. Like it is in sdk 2.1.2

 public interface ProximityListener {
        /**
         * Called when scan starts.
         */
        void onScanStart();

        /**
         * Called when scan stops.
         */
        void onScanStop();

        /**
         * Called whenever specific event occurs.
         *
         * @param event the event
         */
        void onEvent(BluetoothDeviceEvent event);
    }

**Comment by michaldrabik** [comment]
@mail2bhramar You mean scan start and scan stop? There is a Scan Status Listener. 
https://developer.kontakt.io/android-sdk/3.2.0/quickstart/#basic-usage
Basic Usage -> Scan Status Listener

**Comment by mail2bhramar** [comment]
No no.... i want to know the different type of event like ..previously available in onEvent() method.In ScanstatusListener there is no way to find event or i want to know  how to find when specific event occurs is there any listener.

**Comment by michaldrabik** [comment]
There has been a lot of changes since version 2.1.2. You will need to take a look at our quickstart. Basically there is no more one generic event listener. Now you can use different listeners for different actions (like iBeacon or Eddystone listining)

**Comment by mail2bhramar** [comment]
Yes. I agreed, but there is no documentation about this and most of the link in your website are broken. like  https://developer.kontakt.io/android-sdk/3.0.0/quickstart/

**Comment by michaldrabik** [comment]
Try here: https://developer.kontakt.io/android-sdk/3.2.0/quickstart/
It's everything you need.
