### ISSUE TITLE
Not working for Android Marshmallow 6.0.0.

### ISSUE THREAD

**Issue by mail2bhramar** [kontaktio/kontakt-android-sdk#137]
I am working on your SDK 3.2.0.It is working fine for android 6.0.1 but not working for android 6.0.0. Is there any issue with android 6.0.0. Even if your sample and admin application is not working/not able to scan beacon in 6.0.0.

Below is my device details.
Device : Moto G(2nd generation)
android version: 6.0
Kernel Version: 3.4.42

**Comment by michaldrabik** [comment]
There is no difference between 6.0.0 and 6.0.1. Make sure that Location Services are enabled. You can also try downloading NRF Connect application and se if it scans correctly. 

Unfortunately MotoG 2nd is one of the worst phones on the market when it comes to BLE as our experiences with have shown. Rebooting might help.

**Comment by mail2bhramar** [comment]
@michaldrabik Thanks . NRF connect app is able to scan the beacon. Reboot helped me...:)
