### ISSUE TITLE
Kontakt IO Beacon - Usage of API Key

### ISSUE THREAD

**Issue by MayurKJParekh** [kontaktio/kontakt-android-sdk#139]
I have downloaded demo from GitHub

https://github.com/kontaktio/kontakt-beacon-admin-sample-app

Here they have used Server API Key to initialize.

public class App extends Application {

  private static final String API_KEY = "Your Api Key here";

  @Override
  public void onCreate() {
    super.onCreate();
    initializeDependencies();
  }

  //Initializing Kontakt SDK. Insert your API key to allow all samples to work correctly
  private void initializeDependencies() {
    KontaktSDK.initialize(API_KEY);
  }

}
My question is ,

it is suppose to scan and give only those beacon which are registered to my portal of which Server API key I have placed in above code ?

Currently, I am running the demo with 2 different API key and both the time I am getting 2 of my beacons which are registered with only single API key, my thinking is that second key should not give any beacon in result of scan.

Please clear my doubts. How to use API key to only get those beacons which are registered for that key only?

http://stackoverflow.com/questions/41852784/kontakt-io-beacon-usage-of-api-key

**Comment by michaldrabik** [comment]
@MayurKJParekh API Key is necessary only when SDK needs to communicate with our Cloud (during devices unshuffling, sending monitoring events etc.). It's not directly related to scanning results.

If you wish to scan only for your devices the best way is to set specific Proximity UUID for them and then only scan in a region with given Proximity UUID.

**Comment by MayurKJParekh** [comment]
Ok, Thanks for clearing my doubts.

Sorry for misunderstanding.

**Comment by andrekovac** [comment]
@michaldrabik It would be great if you could add this info to the docs?! I also stumbled upon it.

**Comment by michaldrabik** [comment]
@Andruschenko Yep we'll add paragraph 👍
