### ISSUE TITLE
Compatibility between v3.2.0 and v3.2.1 / Doc Change

### ISSUE THREAD

**Issue by pbertsch** [kontaktio/kontakt-android-sdk#140]
Please keep the Class, Interface changes to a minimum between minor release changes.

ProximitManagerContract does not exist anymore in 3.2.1 so changing results in unwanted errors which are not documented. I found out because I compared the JavaDocs from v3.2.0 and v3.2.1

At least mention those things in your documentation.

**Comment by michaldrabik** [comment]
@pbertsch We always try to keep those changes at minimum. However, there is always a changelog available with each release: https://developer.kontakt.io/android-sdk/3.2.1/quickstart/#changelog

**Comment by pbertsch** [comment]
@michaldrabik thanks!
