### ISSUE TITLE
Problem while reading light sensor data

### ISSUE THREAD

**Issue by Oramchus** [kontaktio/kontakt-android-sdk#142]
Hi, what I am trying to achieve is to read Beacons Pro light sensor data for some period. I prepared simple app based on admin app example (https://github.com/kontaktio/kontakt-beacon-admin-sample-app). 

At the beginning app seems to work fine but after a while (~1 min) I am getting connection error with code 1019. In next step, reconnection is make and app worked again for 1 – 2 minutes. However, after three or four reconnections I am getting error with code 1133 and new connection cannot be make for next 3 minutes. After that, everything is starting from beginning. 

The needed result is to read light sensor without huge delays.
Below I post my code I am using to connect to device.
```java
public class KontaktConnectionHandler {

    private static final String TAG = "KontaktConnectionHandle";

    private String deviceUniqueId;
    private Context context;
    private ProximityManager proximityManager;
    private KontaktDeviceConnection deviceConnection;
    private RemoteBluetoothDevice targetDevice;
    private Handler handler;

    private boolean retryConnection = false;

    public KontaktConnectionHandler(Context context, String deviceUniqueId) {
        this.deviceUniqueId = deviceUniqueId;
        this.context = context;
        handler = new Handler(Looper.getMainLooper());
    }

    public void start() {
        setupProximityManager();
        scanForDevice(deviceUniqueId.trim());
    }

    private Runnable run = new Runnable() {
        @Override
        public void run() {
            if (deviceConnection == null && retryConnection) {
                //try to reconnect
                Log.i(TAG, "Was connected but now it is not ... trying to reconnect");
                connectToDevice();
            } else {
                if (deviceConnection == null) {
                    Log.i(TAG, "deviceConnection null");
                    return;
                }
                if (deviceConnection.isConnected()) {
                    setSensorListener();
                }
            }
            handler.postDelayed(this, 1000);
        }
    };


    private void setSensorListener() {
        deviceConnection.readLightSensor(new ReadListener<Integer>() {
            @Override
            public void onReadSuccess(Integer value) {
                Log.i(TAG, "Sensor value: " + value);
            }

            @Override
            public void onReadFailure(ErrorCause cause) {
                Log.i(TAG, "Sensor error: " + cause.name());
            }
        });

    }

    public void stop() {
        if (proximityManager != null) {
            proximityManager.disconnect();
        }
        if (deviceConnection != null) {
            deviceConnection.close();
            deviceConnection = null;
        }
        //handler.removeCallbacksAndMessages(null);
    }

    private void setupProximityManager() {
        proximityManager = ProximityManagerFactory.create(context);

        //Configure proximity manager basic options
        proximityManager.configuration()
                //Using ranging for continuous scanning or MONITORING for scanning with intervals
                .scanPeriod(ScanPeriod.RANGING)
                //Using BALANCED for best performance/battery ratio
                .scanMode(ScanMode.BALANCED)
                //OnDeviceUpdate callback will be received with 5 seconds interval
                .deviceUpdateCallbackInterval(TimeUnit.SECONDS.toMillis(5));

        //Setting up iBeacon and Secure Profile listeners
        proximityManager.setIBeaconListener(createIBeaconListener());
        proximityManager.setSecureProfileListener(createSecureProfileListener());
    }

    private void onDeviceDiscovered(RemoteBluetoothDevice device) {
        //Check if this is our target beacon.
        if (deviceUniqueId.equalsIgnoreCase(device.getUniqueId())) {
            proximityManager.disconnect();
            targetDevice = device;

            connectToDevice();

            String status = "Device discovered! Unique ID: " + device.getUniqueId();
            Log.i(TAG, status);
        }
    }

    private void connectToDevice() {
        //Initialize connection to the device
        deviceConnection = KontaktDeviceConnectionFactory.create(context, targetDevice, createConnectionListener());
        deviceConnection.connect();
        Log.i(TAG, "Connecting to device...");
    }

    private void scanForDevice(String uniqueId) {
        deviceUniqueId = uniqueId;
        proximityManager.connect(new OnServiceReadyListener() {
            @Override
            public void onServiceReady() {
                proximityManager.startScanning();
                Log.i(TAG, "Looking for device...");
            }
        });
    }

    private IBeaconListener createIBeaconListener() {
        return new SimpleIBeaconListener() {
            @Override
            public void onIBeaconDiscovered(IBeaconDevice ibeacon, IBeaconRegion region) {
                onDeviceDiscovered(ibeacon);
            }
        };
    }

    private SecureProfileListener createSecureProfileListener() {
        return new SimpleSecureProfileListener() {
            @Override
            public void onProfileDiscovered(ISecureProfile profile) {
                onDeviceDiscovered(SecureProfileUtils.asRemoteBluetoothDevice(profile));
            }
        };
    }

    private void onDeviceConnected() {
        //Device connected. Start configuration...
        Log.i(TAG, "Device connected - starting handler");
        handler.post(run);
    }

    private KontaktDeviceConnection.ConnectionListener createConnectionListener() {
        return new KontaktDeviceConnection.ConnectionListener() {
            @Override
            public void onConnectionOpened() {
                Log.i(TAG, "onConnectionOpened");
                retryConnection = false;
            }

            @Override
            public void onAuthenticationSuccess(RemoteBluetoothDevice.Characteristics characteristics) {
                Log.i(TAG, "onAuthenticationSuccess");
                onDeviceConnected();
            }

            @Override
            public void onAuthenticationFailure(int failureCode) {
                Log.i(TAG, "onAuthenticationFailure: " + failureCode);
                retryConnection = true;
                stop();
            }

            @Override
            public void onCharacteristicsUpdated(RemoteBluetoothDevice.Characteristics characteristics) {
                Log.i(TAG, "onCharacteristicsUpdated: " + characteristics);
            }

            @Override
            public void onErrorOccured(int errorCode) {
                Log.i(TAG, "Connection error. Code: " + errorCode);
                retryConnection = true;
                stop();
            }

            @Override
            public void onDisconnected() {
                Log.i(TAG, "Device disconnected.");
                retryConnection = true;
                stop();
            }
        };
    }
}
```
SDK version: 3.2.2
PS: I have tried also to reuse KontaktDeviceConnection object by calling close() and connect() but I got similar result.
PS 2: Checked also official app from Google Play and noticed the same behavior.
Did I miss something? Thanks in advice.

**Comment by michaldrabik** [comment]
@Oramchus Hello. Your connection problems may be strictly related to your device's Bluetooth hardware quality (especially because the same thing happens in both your code and our official app). When you start encountering 1133 error try restarting your phone and check again. This will confirm this theory :)

Also, If there is a chance try using different device and compare the results.

Also, be aware that our beacons will always terminate connection after 6 minutes.

I've conducted tests on Nexus 5 device and experienced no disconnects at all until 6 minutes mark.

**Comment by Oramchus** [comment]
@michaldrabik  first thanks for your quick response. According to your post, I have made tests using devices listed below:
-LG G2
-Samsung S6 Edge
-Nexus 6P

Their behavior vary from device to device – here is what I observed:

On LG G2 I am getting random disconnections as described in the first post both with my code and yours app. However, there is one difference. With my code, it behaves exactly as posted and with Kontakt app 1133 error is returned after 3-4 min.

On Samsung it looks like your app correctly connects and is getting light sensor data for all 6 minutes and then disconnects as expected with 1019. Nevertheless, with my code it is still disconnecting after 1-2 minutes with code 1019.

With Nexus, it is almost not possible to connect, still getting 1133 no matter what I am trying. Using your app it needs 7-10 retries to connect then it works for some time. One more observation on this device is that when it is connected to beacon and back is pressed to navigate to previous activity and try to connect (using Sensor Readings view) again it ends up with 1133 every time for next 10 tries.

Tested also two different Beacons Pro but did not find any difference.

Also, made some tests with code and found that when I’m calling 
{KontaktDeviceConnection#applySecureConfig(String, WriteListener)} with some configuration using KontaktCloud I will not get 1019 for all next 6 minutes on Samsung and LG (almost every time). If I am interested only in sensor value, it not make sense to post mock configuration every time.

Any clue why this is acting like that? Maybe it would be good idea to attach example for sensor reading to sample app.

**Comment by michaldrabik** [comment]
I see one odd thing in your code. You are calling `setSensorListener` every second. This will invoke `deviceConnection.readLightSensor` every second as well which is actually not neccessary and might be harmful. 

Check out `readLightSensor` method javadoc: 

> Reading light sensor is based on characteristic notification so after using this method a sensor reading will be received continuously every 0.5 of a second.

This means you only need to call this once after you connect to the beacon and you should receive updates in ReadListener automagically.

**Comment by Oramchus** [comment]
Yes, you are right but this changes nothing because even if I do not set any listener the phone is disconnecting from beacon.

**Comment by michaldrabik** [comment]
Is it possible that you missed the authorization step after connecting to the beacon? Without authorization beacon will disconnect after short duration. Try this steps:

1. Connect to the beacon.
2. Obtain AuthToken via [AuthToken.obtain(uniqueId, callback)](http://kontaktio.github.io/kontakt-android-sdk/3.2.2/Javadoc/com/kontakt/sdk/android/ble/security/auth/AuthToken.html#obtain-java.lang.String-com.kontakt.sdk.android.ble.security.auth.AuthToken.AuthTokenCallback-)
3. Use obtained AuthToken with [authorize ](http://kontaktio.github.io/kontakt-android-sdk/3.2.2/Javadoc/com/kontakt/sdk/android/ble/connection/KontaktDeviceConnection.html#authorize-com.kontakt.sdk.android.ble.security.auth.AuthToken-com.kontakt.sdk.android.ble.connection.AuthorizationCallback-)method.
4. After successful authorization callback call `readLightSensor` method.

**Comment by cram-rod** [comment]
Could somebody post a working example of how to access/read the light sensor data. There is nothing on the Developer's page.

**Comment by michaldrabik** [comment]
@cramirez1971 I'll add a sample into [Sample App](https://github.com/kontaktio/kontakt-beacon-admin-sample-app/) soon.

**Comment by michaldrabik** [comment]
Light sensor data reading sample has been added to [Sample App](https://github.com/kontaktio/kontakt-beacon-admin-sample-app/).

**Comment by oikonomidis** [comment]
Is this issue resolved? If not, why is this issue closed? IMHO, a sample app does not resolve the issue.
We are getting connection error codes 1019 and 1133 on two devices (Samsung Galaxy S2 Tablet / Android 6, Samsung Galaxy S6 / Android 7). We are using Beacon Pro.
We get 1019 error code after 6 minutes of light sensor data. Then we get another 1019 error code after ~30 seconds of more data. After that we get 1133 error code for connection failure (it never even reaches the authentication handshake).
We are building an IoT app which will be based on data collected by Kontakt beacons. Given the current issue, that does not seem possible at the moment. Is this issue included in your roadmap? Will it be resolved anytime soon? Or, is there an workaround / alternative path to take?

**Comment by michaldrabik** [comment]
The maximum connection time with the beacon is 6 minutes or so. Beacon will always disconnect after that time. 1133 error are generic BLE errors and are mostly related to Bluetooth hardware quality of your device.  There is nothing to be done except to retry the connection.

**Comment by oikonomidis** [comment]
Upon resetting the Bluetooth adapters of both our devices, we are still getting 1133 errors. When (hard) resetting the beacon (i.e. removing the power source), we get proper (6-minute) connection.
Given this new feedback, could you please suggest a different course of action w.r.t. to this issue?

**Comment by michaldrabik** [comment]
So I have tested your flow on some of our devices (Nexus 5,6 and a Huawei) and I haven't received any 1133. Just to be sure it is not a Samsung problem, do you have any other device that this could be tested on?

**Comment by oikonomidis** [comment]
I am sorry but we don't currently have non-Samsung devices. We 'll try to get one, though.
Thanks for investigating the issue.
JFYI, a possible workaround could be to close the bluetooth connection programmatically on the Android side _before_ the 6-minute window ends and reestablish the connection. Could be that the error code thrown in the end of this window messes up something in the bluetooth stack. I will test this and let you know if it is actually a workaround.

**Comment by michaldrabik** [comment]
Sure, try to manually close the connection after let's say 3 minutes, reconnect and see if 1133 errors occur.

**Comment by oikonomidis** [comment]
Unfortunately, explicitly disconnecting is not a workaround..the issue still exists.
What I would like to try next is to programmatically reset the beacon device. I noticed there is a resetDevice function inside KontaktDeviceConnection class but it is only available from f/w version 2.0 onwards (the f/w available for Beacon Pro is 1.9 at the moment). Is there a way to reset a Beacon Pro from the Android SDK?
Would it also make sense to provide some sort of list with all the devices that have been tested by Kontakt.io and are guaranteed to work (from a developer's perspective) with Beacon Pro devices?

**Comment by michaldrabik** [comment]
`resetDevice` is meant for some old legacy Smart Beacons so it's not the case. You can't "reset" the beacon remotely from the phone (SDK). 

When it comes to devices it's tricky. Due to Android fragmentation even if you have 2 exactly same devices the BLE quality might differ because of different BLE chips that might have been put inside. I can't really suggest any devices due to company policy :) All I can say is that Samsung are pretty tough to work with (not only for BLE) from every Android developer's perspective.

How many Beacon Pro's do you have. Do they all behave the same way? It might be crucial to test on a device other than Samsung just to exclude Beacon's fault.

**Comment by oikonomidis** [comment]
We currently have three Beacon Pro's, we 've tested all three of them. We went for Samsung due to a requirement for a widely used device. 
We are in evaluation period so we could consider switching to a different smartphone/tablet platform, but some sort of guidance would be appreciated. Would it help if I sent a request from the Kontakt.io official support channel?

**Comment by michaldrabik** [comment]
Sure you can use support@kontakt.io
