### ISSUE TITLE
Read interval

### ISSUE THREAD

**Issue by Rkr999** [kontaktio/kontakt-android-sdk#143]
How to read advertising interval from beacon?

**Comment by michaldrabik** [comment]
What is your beacon's type (smart, pro, card) and firmware version?

**Comment by Rkr999** [comment]
double battery beacons and firmware version 4.0

**Comment by michaldrabik** [comment]
Well the advertising interval can be accessed via the Kontakt.io Panel.

If you want to read it via Bluetooth I need to know what firmware version the have ( is it higher than 4.0?)

Regards

**Comment by Rkr999** [comment]
yes my beacon firmware version is 4.1.2.160620

**Comment by michaldrabik** [comment]
@Rkr999 Then you can use `readAll` method ([Javadoc](http://kontaktio.github.io/kontakt-android-sdk/3.2.2/Javadoc/com/kontakt/sdk/android/ble/connection/KontaktDeviceConnection.html#readAll-com.kontakt.sdk.android.ble.security.auth.AuthToken-com.kontakt.sdk.android.ble.connection.ReadListener-)). This methods requires an AuthToken that can be obtained via the cloud using [AuthToken.obtain()](http://kontaktio.github.io/kontakt-android-sdk/3.2.2/Javadoc/com/kontakt/sdk/android/ble/security/auth/AuthToken.html#obtain-java.lang.String-com.kontakt.sdk.android.ble.security.auth.AuthToken.AuthTokenCallback-) method.

**Comment by Rkr999** [comment]
i am passing password to  AuthToken.obtain() method but it giving FEATURE_NOT_SUPPORTED exception.

kontaktDeviceConnection.readAll(AuthToken.obtain("password"), new ReadListener<Config>() {
                    @Override
                    public void onReadSuccess(Config value) {
                        Log.d(TAG, "onReadSuccess " + value.toString());
                        
                   
                    }

                    @Override
                    public void onReadFailure(ErrorCause cause) {
                        Log.d(TAG, "device onError " + cause.toString());

                    }
                });

**Comment by michaldrabik** [comment]
AuthToken should be obtained via the Cloud. 
This of course requires internet connection and SDK initialized with correct ApiKey

Try: 

```
        AuthToken.obtain("uniqueId", new AuthToken.AuthTokenCallback() {
          @Override
          public void onSuccess(AuthToken token) {
            readAll(token);
          }

          @Override
          public void onError(String error) {
            Log.e(TAG, "onError: " + error);
          }
        });
```

**Comment by michaldrabik** [comment]
@Rkr999 Could I ask why do you need to read the interval straight from the Beacon? This whole operation might be unnecessary. What is your use case?

**Comment by Rkr999** [comment]
basically i need to change the beacon settings from the my application.

**Comment by Rkr999** [comment]
again i am getting FEATURE_NOT_SUPPORTED exception.

**Comment by Rkr999** [comment]
getting FEATURE_NOT_SUPPORTED exception 

public void readCharacteristics() {


        kontaktDeviceConnection = KontaktDeviceConnectionFactory.create(getApplicationContext(), iBeaconDevice, new KontaktDeviceConnection.ConnectionListener() {
            @Override
            public void onConnectionOpened() {
            }

            @Override
            public void onAuthenticationSuccess(RemoteBluetoothDevice.Characteristics characteristics) {
                Log.i(TAG, "onAuthenticationSuccess");
                authTokenFromUniqueId();
            }

            @Override
            public void onAuthenticationFailure(int failureCode) {

            }

            @Override
            public void onCharacteristicsUpdated(RemoteBluetoothDevice.Characteristics characteristics) {

            }

            @Override
            public void onErrorOccured(int errorCode) {

            }

            @Override
            public void onDisconnected() {

            }
        });


        kontaktDeviceConnection.connect();

    }

    void authTokenFromUniqueId() {
        AuthToken.obtain(iBeaconDevice.getUniqueId(), new AuthToken.AuthTokenCallback() {
            @Override
            public void onSuccess(final AuthToken token) {
                readAll(token);
            }

            @Override
            public void onError(String error) {
                Log.e(TAG, "onError: " + error);
            }
        });
    }

    void readAll(final AuthToken authToken) {
        kontaktDeviceConnection.readAll(authToken, new ReadListener<Config>() {
            @Override
            public void onReadSuccess(Config value) {
                Log.d(TAG, "onReadSuccess " + value.toString());
                uniqueId.setText(value.getUniqueId() + "");
                state.setText("In-Region");
                majorEntry.setText(String.valueOf(value.getMajor()));
                minorEntry.setText(String.valueOf(value.getMinor()));
                transimissionPower.setText(value.getTxPower() + "");
                advertisingInterval.setText(value.getInterval() + "");
                progressDialog.dismiss();
            }

            @Override
            public void onReadFailure(ErrorCause cause) {
                Log.d(TAG, "device onError " + cause.toString());
                progressDialog.dismiss();
            }
        });
    }

**Comment by Rkr999** [comment]
still getting INCORRECT_RESPONSE error

**Comment by michaldrabik** [comment]
Could you download our administration app and try to apply any config with it? Does it also fail?

**Comment by Rkr999** [comment]
administration app is working fine but some times i am getting INCORRECT_RESPONSE error.
so can you tell me above code is correct or wrong ? once i read the device characteristics bluetooth is not scanning that device. after removing charger only it scanning that device

**Comment by michaldrabik** [comment]
Administration app should never throw INCORRECT_RESPONSE error. Do you have a screenshot maybe?

When you are connected to a Beacon it does not broadcast anything. Only after closing the connection it will to broadcast again and will be scannable.

**Comment by michaldrabik** [comment]
Closing as the conversation has moved to internal support channel
