### ISSUE TITLE
Can't access `scanContext` methods, e.g. `getIBeaconRegions()` in SDK version 3.2.*

### ISSUE THREAD

**Issue by andrekovac** [kontaktio/kontakt-android-sdk#144]
I want to retrieve all regions which I am currently ranging. Via the `SpacesConfigurator` of the `ProximityManager` I cannot get this information. The only source I found for this info would be the function `getIBeaconRegions()` in the `ScanContext`.

However, I faced some issues when thinking about and trying to use the `scanContext`:

1. The current SDK guides don’t use the `scanContext` at all.

2. The current design of the API doesn’t allow to access the `scanContext` which is created in `ProximityManagerImpl`. Could you add and expose a field of the current `scanContext`, not the `scanContext.Builder` which is returned in the `configuration()`, `spaces()` and `filters()`? With that field I could access the function `getIBeaconRegions()`.

3. There seems to be an issue in its implementation because I always get the error that `.build()` is not defined ( `Error:(40, 17) error: cannot find symbol method build()` ) when I want to access the `scanContext` although it is defined in the `ScanContext.Builder` class. The error happens in both of the following cases where it somehow expects methods of the type `GeneralConfigurator` (or some other configurator) which is implemented by `ScanContext.Builder` but oddly not of type `ScanContext.Builder`:

    a.
    ```
    scanContext = new ScanContext.Builder()
        .scanMode(ScanMode.BALANCED)
        // This is minimal example. Of course I would use other config methods of ScanContext.Builder here
        .build();
    ```

    b.
    ```
    ScanContext scanContext = proximityManager.spaces().build();
    ```

-------
In a former version of the SDK I used (i.e. `2.1.0.`) direct access to the ScanContext was possible and thus I could call it's methods to retrieve currently ranged regions.

**Comment by michaldrabik** [comment]
@Andruschenko With versions 3.x out API has experienced some changes. One of the decisions was to hide ScanContext and provide access via specialized interfaces (configuration, filters, spaces).

Accessing already set regions and filters sounds like something that should be indeed possible. We'll revise that API and add accessors for filters and spaces. Possibly in 3.2.4.

In the meantime you'll just have to store your spaces, filters locally if you need to access them in the future.

**Comment by michaldrabik** [comment]
Version 3.3.0 is up. You can now get filters and spaces via `get` accessors. For example: 
`proximityManager.spaces().getIBeaconRegions()`
