### ISSUE TITLE
Wrong error message if activity check period is longer than active scan period

### ISSUE THREAD

**Issue by andrekovac** [kontaktio/kontakt-android-sdk#145]
With the following configuration I get a crash right after calling `scanManager.startScanning();`:

```
proximityManager.configuration()
                .scanPeriod(ScanPeriod.create(3000, 4000))
                .activityCheckConfiguration(ActivityCheckConfiguration.DEFAULT)
```

The error message I get in the logs is **Activity check period must be *longer* than active scan period** but in `ActivityCheckConfiguration.DEFAULT` the activity check period is `5000`.

Changing the scanPeriod to `.scanPeriod(ScanPeriod.create(6000, 4000))` fixes the issue. So please fix the error message to **Activity check period must be *shorter* than active scan period** or something similar, thanks.

**Comment by michaldrabik** [comment]
@Andruschenko That's a good catch, thanks for reporting 👍
