### ISSUE TITLE
Crash when using SpaceListener only

### ISSUE THREAD

**Issue by melbic** [kontaktio/kontakt-android-sdk#146]
The following code crashes when starting the ProximityManager:
```java
mMonitoringManager = ProximityManagerFactory.create(context);
mMonitoringManager.setSpaceListener(createMonitoringListener());
if (LocationManager.hasLocationPermission(getContext())) {
            mMonitoringManager.connect(new OnServiceReadyListener() {
                @Override
                public void onServiceReady() {
                    mMonitoringManager.startScanning();
                }
            });
        }
```
Stacktrace:
```
java.lang.IllegalArgumentException: At least one listener (IBeacon or Eddystone or Kontakt Secure Profile) must be set.
 at com.kontakt.sdk.android.common.util.SDKPreconditions.checkNotNullOrEmpty(SDKPreconditions.java:210)
 at com.kontakt.sdk.android.ble.configuration.ScanContext$Builder.build(ScanContext.java:363)
 at com.kontakt.sdk.android.ble.manager.ProximityManagerImpl.startScanning(ProximityManagerImpl.java:65)
```

**Comment by michaldrabik** [comment]
This is actually a Precondition not an unexpected crash :) You need to set either eddystone (if you use namespaces) or ibeacon (if you use regions) listener so the SDK knows what too look for internally. The listener can be empty if you are not interested in any callbacks.

So If you use iBeacon regions you can add:
`mMonitoringManager.setIBeaconListener(new SimpleIBeaconListener() {});`

**Comment by melbic** [comment]
I know that it is a precondition, but isn't the precondition false? Or why do I have to set a listener for iBeacons and a listener for Eddystones when there is the concept of spaces where I can observe both at the same time. 
It's inconsequent.

**Comment by michaldrabik** [comment]
I see your point here. There might be a chance for API improvements here.
If you only care about spaces (regions or namespaces) SDK should be able to figure it out under the hood.

We'll take a look at it.

**Comment by melbic** [comment]
Nice, thank you.

**Comment by michaldrabik** [comment]
Version 3.3.0 is up. You can now use only SpaceListener without any limitations.

**Comment by Wilson13** [comment]
Hi @michaldrabik,

 Although my app doesn't crash,  SpaceListener doesn't work if EddystoneListener is not set.
