### ISSUE TITLE
E/BtGatt.GattService: App 'xxxxx' is scanning too frequently

### ISSUE THREAD

**Issue by stan-ko** [kontaktio/kontakt-android-sdk#148]
As I correctly understood that message triggers on N (Android 7) and relies to Doze.
Thats the configuration we are currently using:
```
        mProximityManager.configuration()
                .scanMode(ScanMode.LOW_LATENCY)
                .deviceUpdateCallbackInterval(30000) // 30seconds
                .monitoringSyncInterval(30) // 30 seconds
                .activityCheckConfiguration(ActivityCheckConfiguration.MINIMAL)
                .forceScanConfiguration(ForceScanConfiguration.MINIMAL);
```

Is there a way to avoid that message and the battery draining users blaming us for?  
Here are articles I googled:  
https://github.com/Estimote/Android-SDK/issues/161  
https://github.com/AltBeacon/android-beacon-library/issues/418  
https://github.com/Orange-OpenSource/BeaconTag-Android-SDK/issues/2  
they are not about Kontakt.io SDK but the issue is the same.

**Comment by michaldrabik** [comment]
Hey. Since Android N Google introduced this limitation:

> We’ll prevent applications from starting and stopping scans more than 5 times in 30 seconds.

This is caused by ForceScanConfiguration which restarts the scanner internally too often.

Since SDK version **3.2.2** force scanning will always be set to DISABLED for Android N or higher devices. You can either update SDK version to 3.2.2 or higher or check device's OS version manually and only set ForceScanConfiguration to MINIMAL if it is lower than N.

**Comment by stan-ko** [comment]
So if I update to 3.3.0 which is current version I would not have to change anything in configuration, right? The only thing I'd like to change is scanMode from LOW_LATENCY to LOW_POWER

**Comment by michaldrabik** [comment]
Ye,  if you cahnge to 3.3.0 the SDK will automatically turn of ForceScan for Android N devices. Even if you specify ForceScanConfiguration.MINIMAL in `proximityManager.configuration()`

**Comment by stan-ko** [comment]
Thanx a lot!  
BTW Did you implement any workaround for HTC devices on Android 6 (since version 3.0.0)?

**Comment by michaldrabik** [comment]
What do you refer to? #141 ?

**Comment by stan-ko** [comment]
It wasn't an issue opened by me, but I reported HTC statistics there.
https://github.com/kontaktio/kontakt-android-sdk/issues/126

**Comment by michaldrabik** [comment]
I haven't had a chance yet. But I'll get HTC device and take a look at it eventually.
