### ISSUE TITLE
DeviceUpdateCallbackInterval is not stable

### ISSUE THREAD

**Issue by halidpekel** [kontaktio/kontakt-android-sdk#149]
Hi there, 

Even that I gave 350ms to deviceupdatecallbackinterval. it is handling with interval 1.5sec.

this is my configuration 

        proximityManager.configuration()
                .scanMode(ScanMode.LOW_POWER)
                .scanPeriod(ScanPeriod.RANGING)
                .activityCheckConfiguration(ActivityCheckConfiguration.DEFAULT)
                .monitoringEnabled(false)
                .deviceUpdateCallbackInterval(350L)
                .forceScanConfiguration(ForceScanConfiguration.MINIMAL);

this is log on onIbeaconupdated list: 

03-24 12:28:49.561 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:28:51.256 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:28:52.718 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:28:54.291 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:28:57.562 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:28:59.189 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:00.718 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:02.347 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:05.505 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:08.769 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:10.404 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:11.978 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:13.552 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:15.123 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:16.826 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:18.284 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:20.025 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:21.608 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:23.125 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:24.752 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:26.328 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:27.906 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:29.661 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:31.172 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:32.815 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:34.332 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:37.480 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:39.115 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:40.685 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:42.377 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:44.033 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:47.165 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 12:29:48.744 17276-17276/com.t2w I/TTW: onIBeaconsUpdatedT

What can be the problem? 

Thanks
 
Note: The device is with API24 and the kontakt SDK version is 3.3.0 . When I test the code on device with API21 This is different.. Not exactly 350ms but approximately the same. I mean no problem with API21.

Logs for API21

03-24 13:12:40.711 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:41.941 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:42.291 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:43.516 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:43.876 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:45.066 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:45.446 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:46.551 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:48.251 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:48.601 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:49.696 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:50.171 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:51.226 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:51.581 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:52.791 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:53.146 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:54.376 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:54.901 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:55.956 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:56.356 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:57.516 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:57.871 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:59.096 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:12:59.506 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:13:00.561 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:13:01.026 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:13:02.246 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:13:02.601 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT
03-24 13:13:03.711 17559-17559/com.t2w I/TTW: onIBeaconsUpdatedT

**Comment by michaldrabik** [comment]
@halidpekel Device update callback interval is a **minimum** interval. 

This means that if you set it to 350ms and your device scans packets with interval of 1200ms you will receive the callback with 1200ms interval. If your device could scan packets with 200 ms interval then you would receive the callback with 350ms interval.

Device scanning performance is of course different among devices/OS versions. Beacon interval settings is also relevant here. If the beacon is set to broadcast with 1000ms interval, naturally you will not get 350ms updates.

Hope that clarifies things. :)

**Comment by halidpekel** [comment]
This helped, thanks 👍
