### ISSUE TITLE
Far beacon detecting first before immediate beacon

### ISSUE THREAD

**Issue by subbu1234** [kontaktio/kontakt-android-sdk#15]
We are developing application using kontakt sdk for detecting kontakt beacons. We placed two beacons one in immediate proximity (1m) and another in far proximity (10m). We observed that far beacon detecting first before immediate beacon. we configured with the following code

beaconManager = BeaconManager.newInstance(this.getApplicationContext());
                beaconManager.setMonitorPeriod(MonitorPeriod.MINIMAL);
                beaconManager.setForceScanConfiguration(ForceScanConfiguration.DEFAULT);
                beaconManager.setDistanceSort(BeaconDevice.DistanceSort.ASC);
                beaconManager.registerMonitoringListener(this.regionManager);

Far beacon detecting first but immediate beacon detecting after some time ( after 2-10 seconds).
We need solution that we always require to detect immediate beacon first.

**Comment by dawidgdanski** [comment]
1. We observed that far beacon detecting first before immediate beacon.
   Detection order does not depend on the SDK. It is up to the Android device to establish the notification order.

In brief:

beaconManager.setMonitorPeriod(MonitorPeriod.MINIMAL); [MonitorPeriod description](http://kontaktio.github.io/Android-SDK/Javadoc/com/kontakt/sdk/android/configuration/MonitorPeriod.html)

beaconManager.setForceScanConfiguration(ForceScanConfiguration.DEFAULT); [ForceScanConfiguration description](http://kontaktio.github.io/Android-SDK/Javadoc/com/kontakt/sdk/android/configuration/ForceScanConfiguration.html)

beaconManager.setDistanceSort(BeaconDevice.DistanceSort.ASC);[DistanceSort description](http://kontaktio.github.io/Android-SDK/Javadoc/com/kontakt/sdk/android/device/BeaconDevice.DistanceSort.html)

**Comment by dawidgdanski** [comment]
Hey @subbu1234, what's the status of this issue?
