### ISSUE TITLE
Kontakt Beacons not found on some devices for some reasons

### ISSUE THREAD

**Issue by Washisama** [kontaktio/kontakt-android-sdk#151]
We are using the default method in order to detect Kontakt beacons but on some android devices, Kontakt beacons (there is around 30 of them in a range of max 1 meter) are simply not detected.

Is there anything we can do to have the guarantee to detect them all?

It occures on :

Huawei P9 Light
Android 6.0

One Plus 3
Android 7.1.1

**Comment by michaldrabik** [comment]
We'll need some more info. What beacons are they, firmware version? Maybe their broadcasting interval is to high or tx power too low ?

Could you download this NRF tool: https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp
and check if scanning ignores those beacons as well?

**Comment by Washisama** [comment]
The NRF tool detect directly the beacons.
Firmware is 4.2 but still doesn't detect other beacons on 3.1
Broadcasting interval : 350 ms (we also tested with 100 ms - same issue)
Tx power : 3 (we tested with 7 - same issue)

**Comment by michaldrabik** [comment]
Does it fail to detect always the same, particualar beacons or randomly among those 30? 

Also can you scan them using the Kontakt Administration App?

**Comment by Washisama** [comment]
None of them are detected.
With the Kontakt app they are all detected.
With our apps through the Kontakt SDK, it depends on devices or some other reason.

**Comment by michaldrabik** [comment]
If you can scan them all using Administration App (nearby section) then there might be somtehing wrong with your code. Can you share the code responsible for scanning?

**Comment by Washisama** [comment]
`
public interface BeaconsListener {

    void onScanStart();

    void onScanStop();

    void onUpdateListIBeacon(IBeaconRegion region, List<IBeaconDevice> deviceList);

 
    void onUpdateListEddyStone(List<IEddystoneDevice> deviceList);


    void onRegionEnteredIBeacon(String uuid, int major, int minor);

    void onRegionAbandonedIBeacon(String uuid, int major, int minor);


    void onImmediateUpdateIBeacon(IBeaconDevice iBeaconDevice);

}
`

`
public class BeaconManager implements ProximityManager.ProximityListener{

    private ProximityManager proximityManager;
    private ScanContext scanContext;
    private ScanPeriod scanPeriod;
    private Collection<EventType> eventTypes;
    private BeaconsListener beaconsListener;
    private EddystoneScanContext eddystoneScanContext;
    private IBeaconScanContext iBeaconScanContext;
    private List<IBeaconRegion> iBeaconRegionsFiltre;

    private static Date dateLastUpdate;
    private static long timeInterval = 5000;

    public BeaconManager(Context context) {
        proximityManager = new ProximityManager(context);
        scanPeriod = new ScanPeriod(TimeUnit.SECONDS.toMillis(5), TimeUnit.SECONDS.toMillis(3));
        eventTypes = new ArrayList<>();
        eventTypes.add(EventType.DEVICE_DISCOVERED);
        eventTypes.add(EventType.DEVICES_UPDATE);
        eventTypes.add(EventType.SPACE_ABANDONED);
        eventTypes.add(EventType.SPACE_ENTERED);
        iBeaconRegionsFiltre = new ArrayList<>();
        dateLastUpdate = Calendar.getInstance().getTime();
    }

    public void setScanPeriod(long activePeriodSeconde, long passivePeriodSeconde) {
        scanPeriod = new ScanPeriod(TimeUnit.SECONDS.toMillis(activePeriodSeconde)
                , TimeUnit.SECONDS.toMillis(passivePeriodSeconde));
    }

    public void addAllRegionsFiltre(List<IBeaconRegion> iBeaconRegions) {
        iBeaconRegionsFiltre.addAll(iBeaconRegions);
    }

    public void addRegionFiltre(IBeaconRegion iBeaconRegion) {
        iBeaconRegionsFiltre.add(iBeaconRegion);
    }

    public void setBeaconsListener(BeaconsListener beaconsListener) {
        this.beaconsListener = beaconsListener;
    }

    public void activatedIBeaconScan() {
        iBeaconScanContext = new IBeaconScanContext.Builder()
                .setEventTypes(eventTypes)
                .setDistanceSort(DistanceSort.ASC)
                .setIBeaconRegions(iBeaconRegionsFiltre)
                .setRssiCalculator(RssiCalculators.newLimitedMeanRssiCalculator(5))
                .build();
    }


    public void activatedEddyStoneScan() {
        eddystoneScanContext = new EddystoneScanContext.Builder()
                .setEventTypes(eventTypes)
                .setDistanceSort(DistanceSort.ASC)
                .build();
    }

    public void setEvent(TypeOfEvent... typeOfEvents) {
        eventTypes.clear();
        for (TypeOfEvent event: typeOfEvents) {
            if (event == TypeOfEvent.DEVICE_DISCOVERED) {
                eventTypes.add(EventType.DEVICE_DISCOVERED);
            } else if (event == TypeOfEvent.DEVICES_UPDATE) {
                eventTypes.add(EventType.DEVICES_UPDATE);
            } else if (event == TypeOfEvent.REGION_ABANDONED) {
                eventTypes.add(EventType.SPACE_ABANDONED);
            } else if (event == TypeOfEvent.REGION_ENTERED) {
                eventTypes.add(EventType.SPACE_ENTERED);
            }
        }
    }
	
    public void startScan() {
        if (!proximityManager.isScanning()) {
            scanContext = new ScanContext.Builder()
                    .setScanMode(ProximityManager.SCAN_MODE_BALANCED)
                    .setIBeaconScanContext(iBeaconScanContext)
                    .setEddystoneScanContext(eddystoneScanContext)
                    .setActivityCheckConfiguration(ActivityCheckConfiguration.DEFAULT)
                    .setForceScanConfiguration(ForceScanConfiguration.DEFAULT)
                    .setScanPeriod(scanPeriod)
                    .build();
            initializeScan();
        }
    }

    public void pauseScan() {
        if (proximityManager != null && proximityManager.isScanning()) {
            proximityManager.finishScan();
        }
    }

    public void stopScan() {
        if (proximityManager != null && proximityManager.isScanning()) {
            proximityManager.finishScan();
            proximityManager.disconnect();
            proximityManager = null;
        }
    }

    private void initializeScan() {
        proximityManager.initializeScan(scanContext, new OnServiceReadyListener() {
            @Override
            public void onServiceReady() {
                proximityManager.attachListener(BeaconManager.this);
            }

            @Override
            public void onConnectionFailure() {

            }
        });
    }

    public boolean isScanActive(){
        return proximityManager != null && proximityManager.isScanning();
    }

    @Override
    public void onScanStart() {
        if (beaconsListener != null) {
            beaconsListener.onScanStart();
        }
    }

    @Override
    public void onScanStop() {
        if (beaconsListener != null) {
            beaconsListener.onScanStop();
        }
    }

    @Override
    public void onEvent(BluetoothDeviceEvent event) {
        Date dateNow = Calendar.getInstance().getTime();
        if (dateNow.getTime() >= dateLastUpdate.getTime() + timeInterval) {
            dateLastUpdate = Calendar.getInstance().getTime();
            switch (event.getEventType()) {
                case SPACE_ENTERED:
                    if (event.getDeviceProfile() == DeviceProfile.IBEACON) {
                        IBeaconDeviceEvent iBeaconDeviceEvent = (IBeaconDeviceEvent) event;
                        IBeaconRegion region = iBeaconDeviceEvent.getRegion();
                        beaconsListener.onRegionEnteredIBeacon(region.getProximityUUID().toString()
                                , region.getMajor(), region.getMinor());
                    }
                    break;
                case SPACE_ABANDONED:
                    if (event.getDeviceProfile() == DeviceProfile.IBEACON) {
                        IBeaconDeviceEvent iBeaconDeviceEvent = (IBeaconDeviceEvent) event;
                        IBeaconRegion region = iBeaconDeviceEvent.getRegion();
                        beaconsListener.onRegionAbandonedIBeacon(region.getProximityUUID().toString()
                                , region.getMajor(), region.getMinor());
                    }
                    break;
                case DEVICES_UPDATE:
                    if (event.getDeviceProfile() == DeviceProfile.IBEACON) {
                        IBeaconDeviceEvent iBeaconDeviceEvent = (IBeaconDeviceEvent) event;
                        IBeaconRegion region = iBeaconDeviceEvent.getRegion();
                        List<IBeaconDevice> deviceList = iBeaconDeviceEvent.getDeviceList();
                        beaconsListener.onUpdateListIBeacon(region, deviceList);
                        beaconsListener.onImmediateUpdateIBeacon(deviceList.get(0));
                    } else if (event.getDeviceProfile() == DeviceProfile.EDDYSTONE) {
                        EddystoneDeviceEvent eddystoneDeviceEvent = (EddystoneDeviceEvent) event;
                        List<IEddystoneDevice> deviceList1 = eddystoneDeviceEvent.getDeviceList();
                        beaconsListener.onUpdateListEddyStone(deviceList1);
                    }
                    break;
                case DEVICE_DISCOVERED:

                    break;
                case DEVICE_LOST:

                    break;

            }
        }
    }
}
`

`public class BeaconScanService extends Service implements BeaconsListener {

    private static BeaconScanService beaconScanService;

    private static Context context;
    private static Preferences preferences;
    private static BeaconManager beaconManager;
    private static List<IBeaconDevice> beacons;


    public static BeaconScanService getInstance(Context c) {
        if (beaconScanService == null) {
            context = c;
            preferences = new Preferences(context);
            beacons = new ArrayList<>();
            beaconScanService = new BeaconScanService();
            return beaconScanService;
        } else {
            return beaconScanService;
        }
    }

    public BeaconScanService() {
    }

    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }

    public static void startScanBeacon() {
        if (BluetoothManager.isBluetoothLeSupported(context)
                && BluetoothManager.isBluetoothEnabled()) {
            List<IBeaconRegion> iBeaconRegionList = new ArrayList<>();

            beaconManager = new BeaconManager(context);
            beaconManager.setBeaconsListener(beaconScanService);
            beaconManager.activatedIBeaconScan();
            beaconManager.setScanPeriod(3,0);
            beaconManager.startScan();
        }
    }

    public static void stopScanBeacon() {
        if (BluetoothManager.isBluetoothLeSupported(context)
                && BluetoothManager.isBluetoothEnabled()
                && beaconManager != null
                && beaconManager.isScanActive()) {
            beaconManager.stopScan();

            beacons.clear();
        }
    }

    public static boolean isScanEnded() {
        return beaconManager.isScanActive();
    }

    public static List<IBeaconDevice> getDevices() {
        return beacons;
    }


    @Override
    public void onScanStart() {
    }

    @Override
    public void onScanStop() {
    }

    @Override
    public void onUpdateListIBeacon(IBeaconRegion region, List<IBeaconDevice> deviceList) {
        for(IBeaconDevice device: deviceList) {
            if (!beacons.contains(device)) {
                beacons.add(device);
            }
        }
    }

    @Override
    public void onUpdateListEddyStone(List<IEddystoneDevice> deviceList) {
    }

    @Override
    public void onRegionEnteredIBeacon(String uuid, int major, int minor) {
    }


    @Override
    public void onRegionAbandonedIBeacon(String uuid, int major, int minor) {
    }

 
    @Override
    public void onImmediateUpdateIBeacon(IBeaconDevice iBeaconDevice) {
    }
}
`

`public enum TypeOfEvent {

    DEVICE_DISCOVERED,

    DEVICES_UPDATE,

    REGION_ENTERED,

    REGION_ABANDONED
}`

**Comment by michaldrabik** [comment]
This looks pretty old :) Which SDK version are you using?

**Comment by Washisama** [comment]
2.0.0

**Comment by Washisama** [comment]
Do you think that it would ask us to change a lot to switch to the last version ?

**Comment by michaldrabik** [comment]
You definitely need to update to newest version, 2.0.0 is super-old and unsupported. I don't think you will have to change a ton of code but some adjustments will have to be done. Just check out the docs and you will be fine.

Regards

**Comment by michaldrabik** [comment]
Firstly you can check out samples app: https://github.com/kontaktio/kontakt-beacon-admin-sample-app
and proceed with the migration from there.
