### ISSUE TITLE
Why are some ScanContext constants not public anymore after updating to 3.3.0?

### ISSUE THREAD

**Issue by andrekovac** [kontaktio/kontakt-android-sdk#152]
Why are the constants `DEFAULT_MONITORING_ENABLED`, `DEFAULT_DEVICES_UPDATE_CALLBACK_INTERVAL` and `DEFAULT_MONITORING_SYNC_INTERVAL` of the `ScanContext` suddenly not public anymore?

I am now forced to use hard-coded values instead of the constants..

**Comment by michaldrabik** [comment]
@Andruschenko Hi. Scan context is not really used anymore (just internally in some cases). I've noticed that it has not been mentioned in the changelog and some of those constants still appear in Javadoc. It will be fixed.

You can still define those constants you need by yourself and don't use hard-coded values.
