### ISSUE TITLE
phonegap / cordova wrapper?

### ISSUE THREAD

**Issue by rlucian** [kontaktio/kontakt-android-sdk#153]
Could not find any references on how the sdk could be used in hybrid apps, through cordova/phonegap wrappers. Could you point out if there is such an effort or even an outdated project that could be revived and updated for the current sdk?

**Comment by michaldrabik** [comment]
We've never supported cordova/phonegap and as far as I know there are no current plans to do so. Sorry.

**Comment by rlucian** [comment]
I guess I'll resort to a non-sdk implementation and let you know if we work towards developing a wrapper ourselves.

**Comment by michaldrabik** [comment]
Sure. Such an initiatives are always welcome :) Regards
