### ISSUE TITLE
onEddystoneLost() callback is not getting invoked

### ISSUE THREAD

**Issue by VinuVijayanPalnar** [kontaktio/kontakt-android-sdk#155]
onEddyStoneLost() callback is not getting invoked when one of my beacon is out of range..
Please help..

**Comment by michaldrabik** [comment]
Are you sure you are out of beacon's range. What is your ProximityManger configuration?

**Comment by VinuVijayanPalnar** [comment]
Yes I am.
TX Power : 2
Average connection interval : 344s
proximityManager.configuration()
                .scanMode(ScanMode.BALANCED)
                .forceScanConfiguration(ForceScanConfiguration.MINIMAL)
                .activityCheckConfiguration(ActivityCheckConfiguration.DISABLED);

**Comment by michaldrabik** [comment]
> .activityCheckConfiguration(ActivityCheckConfiguration.DISABLED);

You set it to DISABLED which means that once the beacon is detected it will never be reported as lost.

Change this to DEFAULT and try again.

**Comment by VinuVijayanPalnar** [comment]
Thank You...
It works
