### ISSUE TITLE
Can Kontakt Android SDK detect Beacons from other vendors?

### ISSUE THREAD

**Issue by bshikhar13** [kontaktio/kontakt-android-sdk#156]
I have 2 issues here. When I put my KONTAKT_API_KEY in the app's initialization, does it make sure that the app cannot detect beacons from other vendors AND that the app cannot detect even Kontakt.io Beacons if they belong to some other user (having different API_KEY)

**Comment by sbobowiec** [comment]
API key is used internally by SDK to resolve shuffled devices. You can still scan beacons without it, even from other vendors. Of course while scanning other beacons (not ours) you won't get any other data but iBeacon or Eddystone advertising packets.
