### ISSUE TITLE
ClassCastException device.BeaconDevice to profile.IEddystoneDevice

### ISSUE THREAD

**Issue by psam44** [kontaktio/kontakt-android-sdk#157]
SDK 3.3.1
Nexus 6, Android 7.0

On discovery of a Beacon Pro with Shuffle, in monitoring scan period

06-23 18:07:13.990 15439-15439/com.ices D/kontakt.io SDK: Shuffled device discovered. Resolving... iBeaconDevice{address='DD:E0:B0:A7:E2:9F', uniqueId='null', proximityUUID=c24ae80c-19ab-4055-af12-a6509e8949c5, major=29284, minor=40890, rssi=-57, shuffled=true}
06-23 18:07:14.994 15439-16268/com.ices D/kontakt.io SDK: IBeaconIdResolver Start resolving
06-23 18:07:15.994 15439-16269/com.ices D/kontakt.io SDK: EddystoneUIDResolver Nothing to resolve
06-23 18:07:16.501 15439-16268/com.ices D/kontakt.io SDK: Shuffled device resolved. iBeaconDevice{address='DD:E0:B0:A7:E2:9F', uniqueId='BbXA', proximityUUID=f7826da6-4fa2-4e98-8024-bc5b71e0893e, major=1, minor=28466, rssi=-57, shuffled=true}
06-23 18:07:16.503 15439-16268/com.ices E/kontakt.io SDK: IBeaconIdResolver Error occurs when try to resolve shuffled device 
java.lang.ClassCastException: com.kontakt.sdk.android.ble.device.BeaconDevice cannot be cast to com.kontakt.sdk.android.common.profile.IEddystoneDevice
at com.kontakt.sdk.android.ble.discovery.eddystone.EddystoneDiscoverer.onShuffleResolved(EddystoneDiscoverer.java:19)
at com.kontakt.sdk.android.ble.discovery.AbstractDeviceDiscoverer.onResolved(AbstractDeviceDiscoverer.java:95)
at com.kontakt.sdk.android.ble.cache.FutureShufflesCache.notifyListeners(FutureShufflesCache.java:177)
at com.kontakt.sdk.android.ble.cache.IBeaconIdResolver.notifyListeners(IBeaconIdResolver.java:185)
at com.kontakt.sdk.android.ble.cache.IBeaconIdResolver.handleRequest(IBeaconIdResolver.java:171)
at com.kontakt.sdk.android.ble.cache.IBeaconIdResolver.handleRequests(IBeaconIdResolver.java:147)
at com.kontakt.sdk.android.ble.cache.IBeaconIdResolver.run(IBeaconIdResolver.java:64)

The expected listeners are not fired.
The second active period is better:
06-23 18:07:53.987 15439-15439/com.ices D/kontakt.io SDK: Shuffled device discovered. Resolving... iBeaconDevice{address='DD:E0:B0:A7:E2:9F', uniqueId='null', proximityUUID=c24ae80c-19ab-4055-af12-a6509e8949c5, major=29284, minor=40890, rssi=-57, shuffled=true}
06-23 18:07:53.990 15439-15439/com.ices D/kontakt.io SDK: Shuffled device resolved. iBeaconDevice{address='DD:E0:B0:A7:E2:9F', uniqueId='BbXA', proximityUUID=f7826da6-4fa2-4e98-8024-bc5b71e0893e, major=1, minor=28466, rssi=-57, shuffled=true}
06-23 18:07:53.996 15439-15589/com.ices D/ListenerManager: onRegionEntered: [f7826da6-4fa2-4e98-8024-bc5b71e0893e, ANY_MAJOR, ANY_MINOR]
06-23 18:07:53.998 15439-15589/com.ices D/ListenerManager: onIBeaconDiscovered: iBeaconDevice{address='DD:E0:B0:A7:E2:9F', uniqueId='BbXA', proximityUUID=f7826da6-4fa2-4e98-8024-bc5b71e0893e, major=1, minor=28466, rssi=-57, shuffled=true}, region: [f7826da6-4fa2-4e98-8024-bc5b71e0893e, ANY_MAJOR, ANY_MINOR]

**Comment by psam44** [comment]
The problem seems to originate from DefaultBluetoothDeviceDiscoverer.java.
In the constructor, an instance of `IBeaconDiscoverer` is created, with a `cache` parameter.
Just after, an instance of `EddystoneDiscoverer` may also be created, BUT on the same cache.
Through the constructor of `AbstractDeviceDiscoverer` and `ShuffledDevicesResolver`, this unique cache object will only keep the last call to its `setListener()` and so the resolveCallback will be the EddystoneDiscoverer object even for the discovery of an IBeacon.

I don't use it in my code but it could be the same with the third case `SecureProfileDiscoverer`.

Diagnostic confirmed by commenting my `setEddystoneListener()`, no more Exception if there is only one discoverer listener:

06-25 23:18:25.312 8437-8437/com.ices D/kontakt.io SDK: Shuffled device discovered. Resolving... iBeaconDevice{address='FB:C5:E0:34:6A:77', uniqueId='null', proximityUUID=c24ae80c-19ab-4055-af12-a6509e8949c5, major=29281, minor=61623, rssi=-85, shuffled=true}
06-25 23:18:26.318 8437-8561/com.ices D/kontakt.io SDK: IBeaconIdResolver Start resolving
06-25 23:18:26.482 8437-8561/com.ices D/kontakt.io SDK: Shuffled device resolved. iBeaconDevice{address='FB:C5:E0:34:6A:77', uniqueId='BbXA', proximityUUID=f7826da6-4fa2-4e98-8024-bc5b71e0893e, major=1, minor=28466, rssi=-85, shuffled=true}
06-25 23:18:26.487 8437-8493/com.ices D/ListenerManager: onRegionEntered: [f7826da6-4fa2-4e98-8024-bc5b71e0893e, ANY_MAJOR, ANY_MINOR]
06-25 23:18:26.496 8437-8493/com.ices D/ListenerManager: onIBeaconDiscovered: iBeaconDevice{address='FB:C5:E0:34:6A:77', uniqueId='BbXA', proximityUUID=f7826da6-4fa2-4e98-8024-bc5b71e0893e, major=1, minor=28466, rssi=-85, shuffled=true}, region: [f7826da6-4fa2-4e98-8024-bc5b71e0893e, ANY_MAJOR, ANY_MINOR]

**Comment by michaldrabik** [comment]
Thanks for reporting. We'll be investigating.

**Comment by michaldrabik** [comment]
@psam44 Your suspicions were correct indeed. We will be fixing this in our next release.
