### ISSUE TITLE
IBeaconIdResolver "Start resolving" + "Nothing to resolve" where something has to be resolved

### ISSUE THREAD

**Issue by psam44** [kontaktio/kontakt-android-sdk#158]
SDK 3.3.1
Nexus 6, Android 7.0

On discovery of a Card Beacon with Shuffle, in Monitoring scan_period

06-23 21:57:05.277 15831-15921/com.ices D/kontakt.io SDK: FSCache Cached size: 9
06-23 21:57:07.142 15831-15831/com.ices D/kontakt.io SDK: Device discovered: E8:26:3F:CF:EC:72 Payload: [2, 1, 6, 26, -1, 76, 0, 2, 21, -120, -121, -72, -14, 117, 100, 77, -9, -113, 78, 118, 63, -81, -76, 41, -51, 30, 21, -11, 14, -84, 2, 9, 75, 27, 22, 13, -48, 1, -120, -121, -72, -14, 117, 100, 77, -9, -113, 78, 118, 63, -81, -76, 41, -51, 30, 21, -11, 14, 52, 49, 100, 0] RSSI: -75
06-23 21:57:07.146 15831-15831/com.ices D/kontakt.io SDK: Shuffled device discovered. Resolving... iBeaconDevice{address='E8:26:3F:CF:EC:72', uniqueId='null', proximityUUID=8887b8f2-7564-4df7-8f4e-763fafb429cd, major=7701, minor=62734, rssi=-75, shuffled=true}
06-23 21:57:08.149 15831-15973/com.ices D/kontakt.io SDK: IBeaconIdResolver Start resolving
06-23 21:57:08.277 15831-15973/com.ices W/art: Before Android 4.1, method double java.util.concurrent.ThreadLocalRandom.internalNextDouble(double, double) would have incorrectly overridden the package-private method in java.util.Random
06-23 21:57:08.277 15831-15973/com.ices W/art: Before Android 4.1, method int java.util.concurrent.ThreadLocalRandom.internalNextInt(int, int) would have incorrectly overridden the package-private method in java.util.Random
06-23 21:57:08.277 15831-15973/com.ices W/art: Before Android 4.1, method long java.util.concurrent.ThreadLocalRandom.internalNextLong(long, long) would have incorrectly overridden the package-private method in java.util.Random
06-23 21:57:08.293 15831-15973/com.ices D/kontakt.io SDK: FSCache Cached size: 9
06-23 21:57:09.149 15831-15974/com.ices D/kontakt.io SDK: EddystoneUIDResolver Nothing to resolve
06-23 21:57:10.150 15831-15973/com.ices D/kontakt.io SDK: SecureProfileResolver Nothing to resolve
06-23 21:57:11.295 15831-15974/com.ices D/kontakt.io SDK: IBeaconIdResolver Nothing to resolve
06-23 21:57:12.150 15831-15973/com.ices D/kontakt.io SDK: EddystoneUIDResolver Nothing to resolve
06-23 21:57:13.151 15831-15974/com.ices D/kontakt.io SDK: SecureProfileResolver Nothing to resolve

**Comment by psam44** [comment]
It may be related to a PHANTOM_ENTRY.
This device is a Card Beacon, visible in my Web Panel, present in the Admin App as well, but I don't know why, I can't upload a config change, even after many retries.

**Comment by sbobowiec** [comment]
Sorry for my late response. Did you try it on different card beacons or just one? I'm asking because I applied new configs for 3 different shuffled card beacons using Android administration app without any problems. It's obvious but sometimes you have to restart Bluetooth in such a cases.

**Comment by psam44** [comment]
No, I didn't try on another Card Beacons, but everything was correct (visibility, resolving) on a Pro Beacon.
I had these two devices at that time, loaned by a partner. He didn't want to spend more time in investigation, switched the Card off, and gave me another Pro in exchange.
I don't know if it makes sense saying that the hardware is in defect.
I can have it back, and make some more trials but I would prefer to have first some directions for a efficient debugging.

**Comment by adrianz** [comment]
Hello @psam44!

If you suspect there is anything wrong with your Card Beacon, please get in touch with our Support team via support@kontakt.io and we can start troubleshooting it there.

We appreciate your reports about possible issues with the SDK, but if it looks like a hardware deficiency, our developers here probably won't be able to help with that. Plus, it's not really related to SDK development.
