### ISSUE TITLE
Logger.v(String) is effective despite LogLevel.VERBOSE not enabled

### ISSUE THREAD

**Issue by psam44** [kontaktio/kontakt-android-sdk#159]
Contrary to `Logger.v(String, Throwable)` the test against the `LogLevel.VERBOSE` condition is missing.

**Comment by sbobowiec** [comment]
What do you mean by saying it's more effective? The [Android documentation](https://developer.android.com/reference/android/util/Log.html) states:

> Verbose should never be compiled into an application except during development. Debug logs are compiled in but stripped at runtime. Error, warning and info logs are always kept.

**Comment by psam44** [comment]
Forget the word 'effective', it's a misunderstanding. What I meant is that despite VERBOSE is not enabled, Logger.v prints its output anyway, which it should not.
