### ISSUE TITLE
UncaughtException in ScanController.Consumer (monitor-message-consumer-thread)

### ISSUE THREAD

**Issue by psam44** [kontaktio/kontakt-android-sdk#162]
SDK 3.3.1
Nexus 6, Android 7.1.1

Because of an unmanaged death of the Consumer of a BlockingQueue, the Producer is blocked in its put() (the capacity of the queue is 1) and the whole scanning is freezed.
The crash of the Consumer is caused by manually turning OFF the Bluetooth service during or even before a scan session.
Turning it ON again won't restore a normal flow between the both sides of the queue, it's a locked situation.
The exception is in the Runnable of either RunnersL.newMonitorActiveRunnerL or RunnersL.newMonitorPassiveRunnerL.
In both cases, there is no protection against a null BluetoothLEScanner before calling its startScan() or stopScan() methods.

The benefit of swallowing an uncaughtException is not obvious. The log entry doesn't tell anything about the exception.
I suggest to log some details about the Throwable: ex.toString().

Additional notes, considering that my app runs exclusively in ScanPeriod.MONITORING mode:
1. The log message "onRangingStart(): BluetoothLeScanner is null." is probably outdated regarding the 'Ranging' notion.
2. Isn't there an overlap of startScan() calls between ScanCompatL.onScanStart() and RunnersL.newMonitorActiveRunnerL.run()?

**Comment by sbobowiec** [comment]
Your comments were correct and helpful. All issues are fixed now and will be released soon with updated SDK version.
