### ISSUE TITLE
Suspicion of missing protection against NPE in RunnersL.newForceScanRunnerL

### ISSUE THREAD

**Issue by psam44** [kontaktio/kontakt-android-sdk#163]
There is a check to consider the abnormal case of a null BluetoothLEScanner, but it seems that:
1. The processing is only a log of "Unexpected error occured - Bluetooth Scanner is null", without preventing the execution of the rest of the method.
So the calls to stopScan() and startScan() will raise a NPE.
2. The check should probably be better located before than inside the try/catch for InterruptedException.

Note: typo: occur**r**ed, in RunnersL and Runners.

**Comment by sbobowiec** [comment]
Fixed, will be available in next release.
