### ISSUE TITLE
Is beaconProximityUuid of every becon of Kontakt is unique.

### ISSUE THREAD

**Issue by agcell** [kontaktio/kontakt-android-sdk#166]
Hi Team,

Can beaconProximityUuid  for every beacon is unique or a combination of beaconProximityUuid  + instance is a unique value of every beacon. 
Many of the time we have noticed the instance is null while scanning.

Thanks
Nisha

**Comment by agcell** [comment]
Hi ,

Is there any update for me.

Thanks
Nisha

**Comment by adrianz** [comment]
Hello @agcell

Since this question has nothing to do with our SDK and we're already in touch through our support channels, I'm closing this issue.
