### ISSUE TITLE
monitor-message-consumer-thread crash

### ISSUE THREAD

**Issue by NikEyX** [kontaktio/kontakt-android-sdk#168]
Hi, we received the following crash of BT while the app was running in the background. After this happened, the background monitoring stopped. This seems to be SDK related. Can you confirm this? The app works normally and worked after restarting.

--------- beginning of crash
11-04 11:01:38.299 32522 22886 E AndroidRuntime: FATAL EXCEPTION: monitor-message-consumer-thread
11-04 11:01:38.299 32522 22886 E AndroidRuntime: Process: XXXXXXXX, PID: 32522
11-04 11:01:38.299 32522 22886 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.le.BluetoothLeScanner.stopScan(android.bluetooth.le.ScanCallback)' on a null object reference
11-04 11:01:38.299 32522 22886 E AndroidRuntime: 	at com.kontakt.sdk.android.ble.service.RunnersL$1.run(RunnersL.java:46)
11-04 11:01:38.299 32522 22886 E AndroidRuntime: 	at com.kontakt.sdk.android.ble.service.ScanController$Consumer.run(ScanController.java:160)

**Comment by sbobowiec** [comment]
There were some issues that had to be fixed. More details here: #162 

The problem was that SDK scanning components doesn't deal with turned off Bluetooth correctly and in such a case, exception were thrown which results in freezed scanning with no option to restart.

For now, scan process is not interrupted and you can handle turned off Bluetooth event via `ScanStatusListener`:

```java
final ProximityManager proximityManager = ProximityManagerFactory.create(context);
proximityManager.setScanStatusListener(new ScanStatusListener() {
  @Override
  public void onScanStart() {
    Log.i(TAG, "Scan started");
  }

  @Override
  public void onScanStop() {
    Log.i(TAG, "Scan stopped");
  }

  @Override
  public void onScanError(ScanError scanError) {
    // Here we can react for turned off Bluetooth event
    Log.e(TAG, "Scan error: " + scanError.getMessage());
  }

  @Override
  public void onMonitoringCycleStart() {
    Log.i(TAG, "Scan monitoring cycle started");
  }

  @Override
  public void onMonitoringCycleStop() {
    Log.i(TAG, "Scan monitoring cycle stopped");
  }
});
```

**Comment by NikEyX** [comment]
Thanks, when can we expect the SDK update to be released and which version number will it carry?

**Comment by sbobowiec** [comment]
Sorry for my late response. The new version (3.3.3) will be released next week.

**Comment by NikEyX** [comment]
Great, thanks!
