### ISSUE TITLE
Service stops monitoring when app is destroyed from task manager

### ISSUE THREAD

**Issue by agbanil** [kontaktio/kontakt-android-sdk#17]
Hello,
I tried working with the default foreground/background scan activity provided with the sample app, problem is whenever I close the app from the task manager the notifications for "scan started" and "scan stopped" stop showing up but the service still shows up among running processes in the app manager. I need the service to continue scanning on the background even if the app is killed. Please help me achieve this
N.B: I have tried calling startService() in onDestroy method of the activity, the service runs till i kill the app from the task manager.

**Comment by dawidgdanski** [comment]
1. I close the app from the task manager

By closing application from the task manager you kill the process the application is running on. There is no way to bring the applicatoin back until you do it manually by launching it.
1. I need the service to continue scanning on the background even if the app is killed.

If you hide your application scanning in search of BLE devices to the background,  there is a high probability that the OS will kill your application. You can read more about it here: http://stackoverflow.com/questions/31169434/application-startup-lifecycle/31170603#31170603

However, you can prevent it from doing that  by:

2.1 giving your application "foreground priority" by starting from your service notification via [Service.startForeground()](http://developer.android.com/reference/android/app/Service.html#startForeground%28int, android.app.Notification%29)

2.2 Starting your service by returning [Service.START_STICKY](http://developer.android.com/reference/android/app/Service.html#START_STICKY) parameter. WHen your app is killed and the OS finds some resources your service will be launched again and you can enable scanning once again.
