### ISSUE TITLE
Synchronizing Beacon config changes

### ISSUE THREAD

**Issue by niteshgoel** [kontaktio/kontakt-android-sdk#172]
I want to Sync Beacon config changes with my application. I have seen that if a config is changed on the web panel, I can see the black dot in the admin app beacon list and then I can apply the changes. I want to do the same with my application.
I have searched around but not able to find any documentation regarding the same.
Please Help.

Here is the matching article for admin app:
[https://support.kontakt.io/hc/en-gb/articles/207535145-Synchronizing-Beacon-config-changes-Android-]()

**Comment by wheel1992** [comment]
You can take a look at this section https://developer.kontakt.io/rest-api/api-reference/earlyaccess/#config-create-a-config

Although the API is called /config/create, it does update the beacon physically through synchronization.

**Comment by niteshgoel** [comment]
@wheel1992  I just want to fetch all the pending configuration and apply them to the Beacon if any. I am trying to find a way in which to identify only the pending configuration so that the process of applying changes to the beacon is optimized.

**Comment by sbobowiec** [comment]
@niteshgoel Configs are synchronized through push notifications from our server so you won't be able to achieve the same result.
