### ISSUE TITLE
SecureProfile not get distance

### ISSUE THREAD

**Issue by antonino-tocco** [kontaktio/kontakt-android-sdk#173]
Hi, I have a issue with my beacon pro. I need to access uniqueId and distance from my beacon pro, but the distance in on Eddystone Packet and the uniqueId is on the SecureProfile Packet. Can I have  all the information in one packet or calculate the distance from SecureProfile?

**Comment by sbobowiec** [comment]
In general distance property is not transmitted directly by the Beacon - it's calculated using rssi and tx power values. More details here: [https://stackoverflow.com/questions/20416218/understanding-ibeacon-distancing](url). There's no problem to resolve distance once Secure Profile discovered.
