### ISSUE TITLE
I get NullPointerException when trying to reconnect to beacon service

### ISSUE THREAD

**Issue by nprocak** [kontaktio/kontakt-android-sdk#18]
I can't do beaconManager.disconnect() and then connect() again because I get NullPointerException since disconnect() sets context to null. Is this desirable behavior?

**Comment by jakubkontakt** [comment]
Hi @nprocak 

Current implementation of BeaconManager assumes that disconnect() is called as final method in the lifecycle of BeaconManager. It sets context to null to let Garbage Collector do his job.

I am not sure why you need to call connect() more that once. Could you provide more details about what you want to achieve?

If you want to stop monitoring or ranging you can call stopMonitoring() or stopRanging() and after while if you decide to monitor or range you can call startMonitoring() or startRanging()

**Comment by nprocak** [comment]
My other issue #19 provides an example. I want to change configuration of the monitoring process. But I can't do it after connection is established.

**Comment by dawidgdanski** [comment]
Hey @nprocak  what's the status of this issue?

**Comment by nprocak** [comment]
Well, since a new version of sdk came out and I am in different project now, I guess it's closed.
