### ISSUE TITLE
Can't change config of a beacon pro : FEATURE_NOT_SUPPORTED

### ISSUE THREAD

**Issue by sbriat** [kontaktio/kontakt-android-sdk#180]
Hi,

i submitted a request on kontakt.io, but as i had no response yet i also post it here (and maybe other people have the same problem) 

i can't change configuration of beacon pro using Android SDK 4.0.0

i can update my tough beacons, but when i try with a beacon pro i get the following error : FEATURE_NOT_SUPPORTED

for testing purpose i only try to change minor like this :

Config config = new Config.Builder().minor(9999).build();

some logs from my app :

02-21 15:52:07.209 11082-11082/com.app.myapp I/apptag: onProfileDiscovered: SecureProfile{macAddress='C5:CB:51:43:8E:79', name='Kontakt', uniqueId='AoSe', firmwareRevision='1.10', model='BEACON_PRO', batteryLevel=100, txPower=-20, rssi=-62, namespace='null', instanceId='null', shuffled=false, telemetry=null} 
02-21 15:52:07.223 11082-11082/com.app.myapp I/apptag: prepareProConfiguration 
02-21 15:52:07.711 11082-11082/com.app.myapp I/apptag: pro config successfully created, download encrypted version 
02-21 15:52:07.828 11082-11082/com.app.myapp I/apptag: pro Encrypted version downloaded, fetching... 
02-21 15:52:07.828 11082-11082/com.app.myapp I/apptag: onConfigurationProReady 
02-21 15:52:07.855 11082-11082/com.app.myapp I/apptag: connecting to device... 
02-21 15:52:09.413 11082-11100/com.app.myapp I/apptag: onConnectionOpened 
02-21 15:52:09.418 11082-11100/com.app.myapp I/apptag: Beacon configuration error...FEATURE_NOT_SUPPORTED 
02-21 15:52:39.255 11082-11094/com.app.myapp I/apptag: onErrorOccured 1019

when using tough beacons, i create KontaktDeviceConnectionFactory using a RemoteBluetoothDevice object

when using beacon pro, i create KontaktDeviceConnectionFactory using an ISecureProfile object

as explained there : http://kontaktio.github.io/kontakt-android-sdk/4.0.0/Javadoc/com/kontakt/sdk/android/ble/connection/KontaktDeviceConnectionFactory.html

and there : https://developer.kontakt.io/android-sdk/quickstart/#security 
(Kontakt.io Beacon Pro Secure Communication section)

i think the communication with the Kloud works well, as i have a configuration pending in kontakt panel after i try to update the beacon pro

it fails when i try to connect to the Beacon and send the new encrypted configuration...

Any hint ?

PS : i'm using a Motorola G5 (Android 7.0); when using Kontakt App it works fine most of the time, only sometimes it doesn't work but maybe because i tried before with my own app, that may "block" the beacon for some minutes i guess...

**Comment by sbobowiec** [comment]
Hey. Could you paste more code here so I can investigate it?

**Comment by robertbielas** [comment]
@sylvainb54 
It seems that in your case, you had to perform firmware upgrade so that the secure profile becomes available.

From your description I am assuming you are invoking this sdk's method: 
    void applySecureConfig(String encryptedConfig, WriteListener writeListener) 
    
 FEATURE_NOT_SUPPORTED gets thrown here:
 
    try {
      overwriteSecure(
         -------> serviceStore.getSecureWriteCharacteristic() <------ here, ServiceAbsentException gets thrown for devices that do not have SECURE_CONFIGURATION_SERVICE in the associated service store; the service store is filled during the service discovery phase
         ....
         decodedConfig, writeListener, true);
    } catch (Exception e) {
      writeListener.onWriteFailure(FEATURE_NOT_SUPPORTED); <--- caught and reported to the listener
    } 
    
^ You can see that you can observe this error only in case of devices that do not have SECURE_CONFIGURATION_SERVICE installed; this service is available and activated in beacons with firmware 4.x and higher. 

Closing the issue, but feel free to reopen if you have troubles even after performing DFU.
