### ISSUE TITLE
Can not connect to Siemens beacon

### ISSUE THREAD

**Issue by mfniaki** [kontaktio/kontakt-android-sdk#183]
I'm using Kontakt io SDK in my Android and iOS apps. recently one of my clients added a new Siemens ibeacon (SiMobility Beacon) which I can receive the signal in iOS SDK and app but in Android App it never calls IBeaconListener.
is there any limit for other vendors beacon?

**Comment by sbobowiec** [comment]
Hey. Sorry for my late response. It shouldn't be any problems with scanning beacons from other vendors. We tried to do so and everything worked fine. Could you paste your `ProximityManager` configuration code here?
