### ISSUE TITLE
BackgroundScanService and Android 8 Oreo

### ISSUE THREAD

**Issue by benjaminpayoux** [kontaktio/kontakt-android-sdk#184]
I have an application that must scan beacons in background all the time. I successfully used the BackgroundScanService example but I have an error since Oreo : 

"Not allowed to start service Intent"

After some research, I found that this is related to : [Background execution limits](https://developer.android.com/about/versions/oreo/android-8.0-changes#back-all) 

So I used [evernote library](https://github.com/evernote/android-job) to implement JobScheduling for all devices and tried to move the "setupProximityManager" code into "onRunJob" method.

This is not working this time because of another error : 
"Can't create handler inside thread that has not called Looper.prepare()"

Could you please help me on how to use kontakt sdk for Android Oreo 8 in background "style" to scan beacons all the time ?

Thank you for your help

**Comment by sbobowiec** [comment]
Apologize for my late response. Have you tried our [sample app](https://github.com/kontaktio/kontakt-beacon-admin-sample-app). Please try Foreground Scan sample, which uses foreground service to scan beacons. Source code could be found in [ForegroundScanActivity class](https://github.com/kontaktio/kontakt-beacon-admin-sample-app/blob/master/sample-app/src/main/java/com/kontakt/sample/samples/ForegroundScanActivity.java).

**Comment by Rexee** [comment]
@sbobowiec It will not help you. Just test it. As soon as you turn display off - your library will stop scanning. You need to pass "wildcard" filter in `startScan` function to keep scan working during display is off:
```java
scanner.startScan(createScanFilters(), scanSettings, monitorCallback);

public ArrayList<ScanFilter> createScanFilters() {
        ArrayList<ScanFilter> scanFilters = new ArrayList<>();
        ScanFilter.Builder builder = new ScanFilter.Builder();
        scanFilters.add(builder.build());
        return scanFilters;
    }
```

Currently as I see you use empty array as scan filters and it's not working during screeen off.

It's sad that your SDK is not open sourced and end users can't do anything to fix it...

**Comment by engeld** [comment]
@Rexee or @benjaminpayoux - have you found a workaround for this issue? seems like it affects us as well.

**Comment by NielsOtten** [comment]
This stackoverflow question might be related: [https://stackoverflow.com/questions/48077690/ble-scan-is-not-working-when-screen-is-off-on-android-8-1-0](https://stackoverflow.com/questions/48077690/ble-scan-is-not-working-when-screen-is-off-on-android-8-1-0)

**Comment by robertbielas** [comment]
Anyone still interested in the issue: check out the newest sdk (5.x.x).  All of those contain the mechanism of scanFilters.
The relevant documentation can be found here:
https://knowledgebase.kontakt.io/mobile/android/qsg/usage/#scan-filters
