### ISSUE TITLE
Version 4.0.1 detected as Trojan:Script by Windows Defender

### ISSUE THREAD

**Issue by riboyama** [kontaktio/kontakt-android-sdk#187]
When trying to Gradle sync with the latest Kontakt SDK the following appears to detected:

C:\Users\Ribo\AppData\Local\Temp\gradle_download8525876370902665430bin

as Trojan:Script/Cloxer.A!cl

by Windows Defender, resulting a failed build because Gradle can't process the KontaktSDK

**Comment by robertbielas** [comment]
Solution one: turn off Windows Defender for a while.
Solution two: add it to quarantine.
Solution three: use newer Windows or Defender.
