### ISSUE TITLE
SpaceListener doesn't work if EddystoneListener is not set.

### ISSUE THREAD

**Issue by Wilson13** [kontaktio/kontakt-android-sdk#188]
Reading from this closed issue, [https://github.com/kontaktio/kontakt-android-sdk/issues/146#issuecomment-287768676](link), we should be able to just use the SpaceListener without any limitations but it's not working for me. 

Although the app doesn't crash, SpaceListener doesn't work if EddystoneListener is not set.

Thank you!

**Comment by robertbielas** [comment]
@Wilson13 

1. SpaceListener is a listener that is invoked only when either the first device in a given space  is detected  or the last device in a given space is lost (i.e. none of the devices in the past "inactivity check interval" were detected that match the defined space). The spaces are identified by UUID:major:minor in case of IBeacon, or namespace:instanceId in case of Eddystones; both should be passed by you to the sdk upon initialization. 
You can check the full documentation of those Space Events by inspecting javadocs of com.kontakt.sdk.android.ble.discovery.EventyType class. 
2. Having said that, you are correct, SpaceListener callbacks associated with Eddystone namespaces will not be invoked if you do not pass EddystoneListener. Here's why: you probably use ProximityManagerFactory to instantiate your ProximityManager, which under the hood returns ProximityManagerImpl implementing this interface.
From the source:

   private void checkObservedProfiles() {
     if (iBeaconListener == null) {
       scanContext.removeObservedProfile(IBEACON);
     } else {
       scanContext.addObservedProfile(IBEACON);
     }

     if (eddystoneListener == null) {
       scanContext.removeObservedProfile(EDDYSTONE);
     } else {
       scanContext.addObservedProfile(EDDYSTONE);
     }
     if (secureProfileListener == null) {
       scanContext.removeObservedProfile(KONTAKT_SECURE);
     } else {
       scanContext.addObservedProfile(KONTAKT_SECURE);
     }
  }
  
^ This method is invoked upon ProxymityManager.startScanning(). If EddystoneListener is null, then the sdk does not watch for Eddystones - thus sdk ignores packets representing Eddystones - thus none of the corresponding space events get triggered. You can see similar behavior in case of IBeacon and SecureProfile from the above snippet. 

Closing the issue, please reopen if you need more details.
