### ISSUE TITLE
setDistanceSort to get nearest beacon not working in Android iBeaconScanning

### ISSUE THREAD

**Issue by simpledeveloper1** [kontaktio/kontakt-android-sdk#189]
Hi,

I am trying to use setDistanceSort as said in https://stackoverflow.com/questions/30503258/kontakt-beacon-how-to-retrieve-beacon-based-on-accuracy/30505559#30505559

However, I cannot import the required class, which is com.kontakt.sdk.android.ble.configuration.scan.IBeaconScanContext.Builder

Is setDistanceSort obsolete?

**Comment by robertbielas** [comment]
@simpledeveloper1 As of today, yes, sdk 5.0.xx no longer contains IBeaconScanContext class at all. It was replaced entirely by ScanContext class, which does not contain this sorting field you mentioned.
