### ISSUE TITLE
Can't change monitor period after connecting to beacon service

### ISSUE THREAD

**Issue by nprocak** [kontaktio/kontakt-android-sdk#19]
setMonitorPeriod, setBeaconActivityCheckConfiguration and other configuration settings can only be provided before calling beaconManager.connect(). After this, I can't change period times although it would be reasonable to monitor beacons more often and more rarely under certain circumstances. Unfortunately I must recreate new beaconManager instance, because disconnecting and connecting again raises an error (my other issue). Is this a bug? What is the proper way to change configuration dynamically?

**Comment by jakubkontakt** [comment]
At this moment we do not support runtime changes in our SDK and we do not plan to support it.

If you have any proposals about that and how it should look like we can look at it.

**Comment by nprocak** [comment]
Thanks for the answers
