### ISSUE TITLE
Can not create ProximityManager IBeaconFilter Android Pie Predicate<T> removed

### ISSUE THREAD

**Issue by Rosenstoyanov** [kontaktio/kontakt-android-sdk#190]
I am compiling for android API 28 and i am trying to apply IBeaconFilter on my proximity manager

proximityManager.filters().iBeaconFilter { iBeacon -> iBeacon.minor % 2 != 0 }

e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:

package com.kontakt.sdk.android.ble.filter.ibeacon, unresolved supertypes: com.android.internal.util.Predicate.

So com.android.internal.util.Predicate are removed from android SDK api 28 and my app can not compile fro this api.

Are there any replacements of IBeaconFilter in the SDK in order to compile for api 28?
Are you planning to release a version with replacement of Predicate?

**Comment by zelenmi6** [comment]
Our company is having the same issue and our clients are getting nervous since we cannot raise the target SDK version of our app.

**Comment by kami4ka** [comment]
Our client has bought the subscription for beacons, but cannot use it with 28 SDK. Will this issue be fixed?

**Comment by stoprocent** [comment]
Hi All, we will fix this issue this month and release an updated version as soon as possible.

**Comment by Timir11** [comment]
Sorry but I got same error still in 29 SDK

**Comment by robertbielas** [comment]
Android internal Predicate replaced by internal sdk's Predicate interfaces.
This java code:
proximityManager.filters().iBeaconFilter((i) -> true);
compiles successfully.
