### ISSUE TITLE
Urgen please...com.kontakt.sdk.android:kontakt.io-android-sdk:2.1.0 required

### ISSUE THREAD

**Issue by kiteflo** [kontaktio/kontakt-android-sdk#191]
Hi guys,

we need your "old" SDK (com.kontakt.sdk.android:kontakt.io-android-sdk:2.1.0) in order to rebuild a project. It looks like you removed it from all repos.

Please can you somehow send us a link to download the old SDK?

flo@sobr.ch

thx,
Florian

**Comment by stoprocent** [comment]
Hi
This repository contains all historical releases. Just clone this repo and checkout some old commit.
This for example https://github.com/kontaktio/kontakt-android-sdk/tree/28fa667422eb55d1249c3f899304c3e1aba064ef
