### ISSUE TITLE
Error: Program type already present: com.kontakt.sdk.android.ble.cache.SecureProfileResolveRequest

### ISSUE THREAD

**Issue by netzerodash** [kontaktio/kontakt-android-sdk#192]
I've set up and run to test.
But it returns an error

> Error: Program type already present: com.kontakt.sdk.android.ble.cache.SecureProfileResolveRequest

How to fix it

**Comment by robertbielas** [comment]
@netzerodash  
Please run the following command in the terminal:

         ./gradlew clean

and try to build again.

Please reopen if the issue persist.
