### ISSUE TITLE
getUniqueId() returns null

### ISSUE THREAD

**Issue by antoniovlasic** [kontaktio/kontakt-android-sdk#193]
With the Android SDK, I try to scan for iBeacons and get their unique id. I can find them, but when I call the RemoteBluetoothDevice::getUniqueId method it always returns null. 

Android Version: 8 Oreo, 9 Pie
Beacons: Tough Beacon TB18-2 configured with the iBeacon package
Version: 4.0.2

Thank you in advance!

**Comment by antoniovlasic** [comment]
Additional information:

- Using the ProximityManager
- Without any regions
- Using only the SimpleIBeaconListener
- ScanPeriod=RANGING, ScanMode=BALANCED

I've followed the example. Also, it doesn't even return the unique id with the example.

**Comment by pranavpari** [comment]
Facing the same issue. Any luck??

**Comment by jsochurek** [comment]
Still seeing this, any updates?

**Comment by sergeylaptev** [comment]
Any updates on this?

**Comment by MKacikKontakt** [comment]
You should also scan for Secure Profile where you will get the Unique ID. I encourage you to visit the
https://developer.kontakt.io/hardware/packets/secureprofile/
Also, you will get the UniqueID when it came with Secure Response.

**Comment by robertbielas** [comment]
Rationale: 
the Ibeacon object can have a non null uniqueId only if it is associated with a connectable frame - not true for most of the modern Kontakt devices (which are based on nrf 52 chip). The old ones were based on nrf 51 chip (currently only SB16-2 Smart Beacons still have this circuit) - it allowed to transmit ScanResponse associated with the ibeacon frames (and it is this scan response that contained the unique id, not the "core" ibeacon payload).

If you are interested in getting uniqueId from payloads transmitted by nrf-52 based beacons, please do as @MKacikKontakt suggested. 

(On a bright note: SB16-2 devices will still transmit Unique Id alongside its ibeacon payload if you are interested in performing if-ology based on the device model in your app.)
