### ISSUE TITLE
Support background ble scanning android SDK API level > 26

### ISSUE THREAD

**Issue by ghost** [kontaktio/kontakt-android-sdk#194]
How does the kontakt android sdk support background beacon scanning on Android API level > 26?

Afaik fast beacon detection can be done with the android sdk:

`BluetoothLeScanner#startScan(List<ScanFilter> filters, ScanSettings settings, PendingIntent callbackIntent)  Added in API level 26`

Which should work perfectly when:
- App is killed
- Doze and App Standby

Does the kontakt android sdk work with android API level > 26 when App is killed as well as in doze mode and when App Standby?

How does this work with the Kontakt packet (Kontakt.io Secure Profile packet)?

**Comment by robertbielas** [comment]
Anyone still interested in the issue: check out the newest sdk (5.x.x). All of those contain the mechanism of scanFilters.
The relevant documentation can be found here:
https://knowledgebase.kontakt.io/mobile/android/qsg/usage/#scan-filters
