### ISSUE TITLE
service stops monitoring when display is off on Android 9 devices

### ISSUE THREAD

**Issue by JonesMuc** [kontaktio/kontakt-android-sdk#195]
When I turn off the display on Android 9 devices running the sample app with foreground service on, the monitoring stops immediately. On older devices the monitoring keeps running.

Steps to reproduce: 

- Install sample app  on an Android 9 device with logging enabled:
`KontaktSDK.initialize(API_KEY).setDebugLoggingEnabled(BuildConfig.DEBUG).setLogLevelEnabled(LogLevel.DEBUG, true);`

- Watch the logging to stop when you turn off the display 
and reappear when the display is on again. (Android 9)

- Watch the logging to work all the time. (older Devices)

We need the monitoring functionality also with turned off displays for our app. Are there any workarounds?

**Comment by enesSenVolantX** [comment]
I think I got your issue. Android says;

> Stop unfiltered BLE scans when the screen goes off.

here;

https://android.googlesource.com/platform/packages/apps/Bluetooth/+/319aeae6f4ebd13678b4f77375d1804978c4a1e1

But when I check your code, you don't give any filter for your scan like below;


```
  private static Runnable newMonitorActiveRunnerL(final ScanConfigurationL configuration) {
    final MonitorCallbackL monitorCallback = (MonitorCallbackL) configuration.getScanCallback();
    final ScanSettings scanSettings = configuration.getScanSettings();
    final List<ScanFilter> scanFilterList = new ArrayList<>();

    return new Runnable() {
      @TargetApi(Build.VERSION_CODES.LOLLIPOP)
      @Override
      public void run() {
        final BluetoothLeScanner scanner = getScanner(monitorCallback);
        if (scanner == null) return;

        Logger.d("Start Scan");
        scanner.startScan(scanFilterList, scanSettings, monitorCallback);
        Logger.d("On Monitor started");
        monitorCallback.onMonitorStarted();
      }
    };
  }

```

As you can see **scanFilterList** is empty. That is why this issue happens. 

Please make a quick fix for this issue. Waiting for ur response.

**Comment by JonesMuc** [comment]
Thank you for your comment but I cannot find this piece of code in the kontaktio-sample app [link](https://github.com/kontaktio/kontakt-beacon-admin-sample-app).
Could you tell me where I can find and change this? Thanks in advance

**Comment by enesSenVolantX** [comment]
This is bug of SDK. It is decompiled code so developers should fix it and generate a new fixed version for Android SDK. Monitoring with only screen on is a serious problem for SDK I guess. 

But for workaround you can use this code and run it on a foreground servise (If you are scanig iBeacon, but you can enlarge filter for other types)

```
ScanFilter filter = new ScanFilter.Builder()
            .setManufacturerData(0x004c, new byte[] {})
            .build();
    ArrayList<ScanFilter> list = new ArrayList<>();
    list.add(filter);

    final ScanSettings scanSettings = new ScanSettings.Builder()
            .setCallbackType(ScanSettings.CALLBACK_TYPE_ALL_MATCHES)
            .build();
    BluetoothAdapter.getDefaultAdapter().getBluetoothLeScanner().startScan(list,scanSettings,new ScanCallback() {
      @Override
      public void onScanResult(int callbackType, ScanResult result) {
          IBeaconDevice ibeaconWithReflection = getIbeaconWithReflection(result);
          System.out.println(ibeaconWithReflection);
        switch (callbackType) {
          case ScanSettings.CALLBACK_TYPE_ALL_MATCHES:
              Log.d(TAG, "CALLBACK_TYPE_ALL_MATCHES callbackType = [" + callbackType + "], result = [" + result + "]");

              break;
          case ScanSettings.CALLBACK_TYPE_FIRST_MATCH:
            Log.d(TAG, "CALLBACK_TYPE_FIRST_MATCH callbackType = [" + callbackType + "], result = [" + result + "]");
            break;
          case ScanSettings.CALLBACK_TYPE_MATCH_LOST:
            Log.d(TAG, "CALLBACK_TYPE_MATCH_LOST callbackType = [" + callbackType + "], result = [" + result + "]");
            break;
        }

        super.onScanResult(callbackType, result);

      }

        private IBeaconDevice getIbeaconWithReflection(ScanResult result) {
            IBeaconParser parser = new IBeaconParser(ScanContext.DEFAULT);

            if (!parser.isEnabled()) {
                return null;
            }

            parser.parseScanRecord(result.getScanRecord().getBytes());


            IBeaconDevice invokedObject = null;
            try {
                Method method = parser.getClass().getDeclaredMethod("getIBeaconDevice", result.getDevice().getClass(), Integer.TYPE);
                method.setAccessible(true);

                invokedObject = (IBeaconDevice) method.invoke(parser, result.getDevice(), result.getRssi());


            } catch (IllegalAccessException e) {
                e.printStackTrace();
            } catch (InvocationTargetException e) {
                e.printStackTrace();
            } catch (NoSuchMethodException e) {
                e.printStackTrace();
            }

            return invokedObject;
        }
    });
```

**Comment by JonesMuc** [comment]
thanks for pointing that out and your workaround for iBeacons. We are also using the kontakt-tlm pakets (for movement analysis), so I think we have to wait for the developers to update the SDK. But thanks anyway!

**Comment by robertbielas** [comment]
@JonesMuc please, check sdk 5.0.18.
