### ISSUE TITLE
Restart scanning vs. checking for scan status with isScanning()

### ISSUE THREAD

**Issue by andrekovac** [kontaktio/kontakt-android-sdk#196]
In `ProximityManager`: Is there a potential downside in restarting scanning frequently (via `restartScanning`) as opposed to using `isScanning` to start/stop scanning?

**Comment by robertbielas** [comment]
@andrekovac Good question sir, I think not, just restart does this:

            service.onStopScan();
            service.onStartScan((Bundle) msg.obj);            
            
(where isScanning() method you asked in your comment is invoked internally), whereas nothing stops you to perform manually all the job sdk does on restart invocation. One of the benefits I see is that you gain some more fine-grained control over the scanning behavior of your application, but at the cost of more code on your side.

The choice is yours. 

Closing the issue, please reopen if you need additional details.
