### ISSUE TITLE
How does  ScanContext#isMonitoringEnabled() work internally?

### ISSUE THREAD

**Issue by andrekovac** [kontaktio/kontakt-android-sdk#197]
How is `isMonitoringEnabled` implemented? The JavaDoc didn't contain an explanation of how it determines whether monitoring is enabled.

* Does `isMonitoringEnabled` check whether the `ScanPeriod` was set to `MONITORING`?
* Or would it also return true if other custom ranges were set with `activePeriodMillis` and `passivePeriodMillis`?

**Comment by robertbielas** [comment]
@andrekovac Yes, this should prolly require some clarification. From what I see in the sources, this flag is not determined internally by sdk, but the client app passesit to inform whether the internal EventCollector is allowed to start and collect battery / telemetry events that are obtained during the process of BT scan (this modifies lastSeen / battery properties which you can prompt by performing the http request to the /device endpoint of the Kio cloud; also, sdk 5.x.x introduced gathering telemetry fields as well, like temperature, accelerometer etc. You can check the sources which fields are currently being uploaded, look at the com.kontakt.sdk.android.common.model.FullTelemetryCollectEvent class for details).  Default value - true.

If you have further questions regarding this, please reopen the issue.
