### ISSUE TITLE
problem in 1.0.6 version and Beacons not disappearing in 1.0.1

### ISSUE THREAD

**Issue by codeButterfly** [kontaktio/kontakt-android-sdk#20]
Hello 

am having a problem with beacon class in the 1.0.6 version it seems to be not available and i am using the 1.0.1 where i have a problem of the beacons not disappearing from the onbeaconupdates list of beacons 

Help is appreciated

**Comment by dawidgdanski** [comment]
Hey @codeButterfly. http://kontaktio.github.io/Android-SDK/Javadoc/com/kontakt/sdk/android/configuration/BeaconActivityCheckConfiguration.html
Include it in the BeaconManager's configuration.
