### ISSUE TITLE
error: package android.support.annotation does not exist | cannot find symbol class Nullable

### ISSUE THREAD

**Issue by rfdc** [kontaktio/kontakt-android-sdk#200]
Hi there,

I've started a fresh react-native project and got the following error:
```
error: package android.support.annotation does not exist
error: cannot find symbol class Nullable
```
This is a picture of the error:
![image](https://user-images.githubusercontent.com/32999759/63030809-8a625880-bee5-11e9-8a63-ba2c9095ba28.png)

These are my dependencies:
```
"dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-kontaktio": "^2.6.2",
    "react-native-switch-toggle": "^1.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.8.0",
    "eslint": "^6.1.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.8.6"
  },
```
I've tried to use `npm & yarn` and both gave the same error.

Any idea on how to solve this issue?

Thanks

**Comment by robertbielas** [comment]
@rfdc please see: https://stackoverflow.com/questions/40380519/error-package-com-android-annotations-does-not-exist
