### ISSUE TITLE
Background scanning not working for a few android (>=8.1) devices when screen turned off

### ISSUE THREAD

**Issue by NielsOtten** [kontaktio/kontakt-android-sdk#201]
Since a few days i am working with the kontakt.io library, because another library i was using isn't supported anymore. With that library there was a problem with finding beacons when the screen is turned off and it seems to be in this library as well. This is a really specific problem for a few devices as explained [here](https://stackoverflow.com/questions/48077690/ble-scan-is-not-working-when-screen-is-off-on-android-8-1-0). 

When you start the scanner with (in ble/service/RunnersL.java): 
```
final List<ScanFilter> scanFilterList = new ArrayList<ScanFilter>();
scanner.startScan(scanFilterList, scanSettings, monitorCallback);
```
This works normally when the device is active or when using a foreground service, but when you turn the screen off it would return an empty array with beacons.

The old library i used fixed it with the following lines:
```
List<ScanFilter> scanFilters = new ArrayList<ScanFilter>();
ScanFilter.Builder builder = new ScanFilter.Builder();
builder.setManufacturerData(76, new byte[0]);
scanFilters.add(builder.build());
```

More information about this can be found on [the stackoverflow question](https://stackoverflow.com/questions/48077690/ble-scan-is-not-working-when-screen-is-off-on-android-8-1-0).

**Comment by NielsOtten** [comment]
This also occured in a different beacon scan module Android Beacon Library see [#637](https://github.com/AltBeacon/android-beacon-library/pull/637). They fixed it with creating a wildcard ScanFilter:
```
public List<ScanFilter> createWildcardScanFilters() {
    List<ScanFilter> scanFilters = new ArrayList<ScanFilter>();
    ScanFilter.Builder builder = new ScanFilter.Builder();
    scanFilters.add(builder.build());
    return scanFilters;
}
```

**Comment by jainamagile** [comment]
I am using the iBeacons of kontaktio. The same thing is happening to me. I have one Foreground service that helps me in scanning the beacon even it is not in the background. It is working fine except in some of the devices. 

I don't know where the issue is. It may be the Bluetooth issue configured in the device or the SDK issue.

**Comment by NielsOtten** [comment]
Got in contact with the Kontakt support desk and it seems this issue won't be fixed any time soon due to lack of mobile developers... They recommended using another library like [Alt Beacon](https://github.com/AltBeacon/android-beacon-library).



Their response: 
Hi ....,
Unfortunately as of right now, we can not assure that this feature will be implemented in the Android SDK. It has been noted but it will not be implemented in the near future because of the availability of our mobile developers.
Solution, for now, would be using foreground services in Android and some other libraries that fit your needs as you mentioned before.
I hope you understand
Best regards

**Comment by Rexee** [comment]
duplicate: https://github.com/kontaktio/kontakt-android-sdk/issues/184

**Comment by robertbielas** [comment]
Anyone still interested in the issue: check out the newest sdk (5.x.x).  All of those contain the mechanism of scanFilters.
The relevant documentation can be found here:
https://knowledgebase.kontakt.io/mobile/android/qsg/usage/#scan-filters
