### ISSUE TITLE
Obtain Proximity information from ISecureProfile

### ISSUE THREAD

**Issue by dexpota** [kontaktio/kontakt-android-sdk#202]
Is it possible to get Proximity information from an object which implements `ISecureProfile`? Maybe indirectly from `txPower` and `RSSI` fields by calculating it.

**Comment by robertbielas** [comment]
@dexpota sure. Here is the snippet:
private double calculateDistance(int rssi){
        double smoothing = 3;
        return Math.pow(10d, ((double) actualRssiAtOneMeter - rssi) / (10 * smoothing));
    }
    
where actualRssiAtOneMeter is calculated like this:
    
    public static int getRssiAt1MFrom(RemoteBluetoothDevice device, Device targetDevice){ 
    // device is scanned via our sdk, 
    // targetDevice is fetched from Kio Cloud - the latter using the appropriate method from kontaktCloud sdk object.
        List<Integer> rssisAt1m = targetDevice.getConfig().getRssi1m(); 
        return rssisAt1m.get(device.getTxPower());
    }

The result of calculateDistance is expressed in meters.
