### ISSUE TITLE
No enum constant com.kontakt.sdk.android.common.model.PacketType.BUTTON_IBEACON

### ISSUE THREAD

**Issue by Rexee** [kontaktio/kontakt-android-sdk#203]
If you enable checkbox "iBeacon Button" in Beacons cloud profile page, sync device with cloud, and then try to download devices with SDK <= 4.0.3 you will fail with following error:
**`No enum constant com.kontakt.sdk.android.common.model.PacketType.BUTTON_IBEACON`**

**Comment by robertbielas** [comment]
@Rexee correct, sdk's lower than 4.0.3 do not have this packet listed in the enum you mentioned. If you could, please use the newest sdk available. (5.0.x). Thank you.
