### ISSUE TITLE
Migrate away from JCenter

### ISSUE THREAD

**Issue by eeVoskos** [kontaktio/kontakt-android-sdk#204]
JCenter is being [sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). The library needs to be uploaded to Maven Central, or your own repo, before May 1st.

**Comment by eeVoskos** [comment]
Any update on this from the Kontakt team @robertbielas?

**Comment by robertbielas** [comment]
Hello @eeVoskos. Yes, the migration will be performed, we are aware of JCenter being sunset. 
I will let you know when the migration is complete.

**Comment by robertbielas** [comment]
@eeVoskos 
Our sdk is now available as a dependency on MavenCentral: https://search.maven.org/artifact/io.kontakt.mvn/sdk/5.0.3/aar

Until JCenter/Bintray sunset, you can add dependency on our sdk from both MavenCentral & Bintray. 
However, it is recommended that from now on the users will update their app level's build.gradle file and change the following line:
  implementation "com.kontaktio:sdk:5.0.2"
 to:
  implementation "io.kontakt.mvn:sdk:5.0.3". 
  
Note you will also have to modify your project level build.gradle  file to include:
buildscript {
  repositories {
    mavenCentral()
    ...
   }
 }
 
 if you haven't already done that.
 
 Please let us know if you have any issues.

**Comment by Rexee** [comment]
@robertbielas what about 4.0.3 version? You have no changelog anywhere. On your site last changelog was about 4.0.0 version.

**Comment by robertbielas** [comment]
@Rexee Good catch! We will update the changelog on our documentation site soon. 

Addressing your question about sdk version: please use the newest 5.0.6 version, which does everything 4.0.3 does.  (That will be in the changelog soon as well).

**Comment by robertbielas** [comment]
@Rexee The changelog of Android sdk has been updated, refer to: https://knowledgebase.kontakt.io/mobile/android/changelog/
