### ISSUE TITLE
Javadocs and documentation

### ISSUE THREAD

**Issue by pubiqq** [kontaktio/kontakt-android-sdk#205]
- [x] Javadoc and source artifacts for `io.kontakt.mvn:sdk:5.0.*` - Done (fixed in [5.0.9](https://search.maven.org/artifact/io.kontakt.mvn/sdk/5.0.9/aar))
- [x] Relevant SDK changelog - Done (https://knowledgebase.kontakt.io/mobile/android/changelog/)
- [x] Relevant introduction - Done (https://knowledgebase.kontakt.io/mobile/android/sdk/#introduction)

**Comment by pubiqq** [comment]
@robertbielas, soft push.

Also would be nice to know, is your team planning to put the source code on GitHub?

**Comment by robertbielas** [comment]
Hey @pubiqq.

Sure, let me see what I can do about javadocs. I will let you know.

The changes in the newest sdk have been documented in https://knowledgebase.kontakt.io/mobile/android/ (mostly the introduction of scan filters & background scanning), but if you have any suggestions how to improve it (maybe I missed something or did not express some concept clearly enough) - I am open to your input! Feel free to comment also on older sections, maybe they require refactoring too and modifying them could introduce value to the community.  

Thanks!

**Comment by pubiqq** [comment]
@robertbielas, thank you for the quick response!

The saddest thing for me is, of course, the lost javadocs, and I would like to see them return in the next releases:

interface GeneralConfigurator<br> (com.kontaktio:sdk:5.0.2) | interface GeneralConfigurator<br> (io.kontakt.mvn:sdk:5.0.2)
------------ | -------------
![com.kontaktio:sdk:5.0.2](https://user-images.githubusercontent.com/82187521/118565641-49167100-b77b-11eb-80d5-154dc2d6277a.png) | ![io.kontakt.mvn:sdk:5.0.2](https://user-images.githubusercontent.com/82187521/118565653-4ddb2500-b77b-11eb-97d6-8161f75ad5f2.png)

**Comment by pubiqq** [comment]
About documentation: I suppose, it needs at least shallow proofreading, for example:

![Illustration](https://user-images.githubusercontent.com/82187521/118571576-0eb2d100-b787-11eb-945a-16d87b88b8c4.png)

**Comment by robertbielas** [comment]
@pubiqq please, check out version 5.0.8, which contains both source and javadoc jars. 

As regards the documentation: you are right, there needs to be some improvement here. Copywriting changes will be done as soon as possible. 

Thanks for vigilance!

**Comment by pubiqq** [comment]
@robertbielas, sorry for the delayed response.
Yeah, I see, jar and javadocs have been added to the repository, but unfortunately showing source code still doesn't work (but tooltips work correctly).

**Comment by robertbielas** [comment]
@pubiqq Mea culpa, check out sdk 5.0.9.

**Comment by pubiqq** [comment]
@robertbielas, now it works perfectly, thank you.

**Comment by robertbielas** [comment]
@pubiqq Are we good with the third item on the checklist, or would you like some further improvements introduced into the documentation?

**Comment by pubiqq** [comment]
> Are we good with the third item on the checklist, or would you like some further improvements introduced into the documentation?

I think this is good enough, thank you!
