### ISSUE TITLE
Reading UniqueId from Card Beacon

### ISSUE THREAD

**Issue by cbaudia** [kontaktio/kontakt-android-sdk#207]
Hi!

It seems like uniqueId or name of a card becon is always returning "null". We were expecting to find "XXXXXX" either in the name or uniqueId properties. I have tried to use getName() and getUniqueId() exposed by the RemoteBluetoothDevice interface but there are always null. 

How can we get this id?

Thanks!

**Comment by cbaudia** [comment]
Edit: The solution is to use ISecureProfile as for Beacons Pros.

`proximityManager.setSecureProfileListener(object : SimpleSecureProfileListener() {
override fun onProfileDiscovered(profile: ISecureProfile) {
//Profile discovered
L.print(this, "ISecureProfile - $profile")
}
})`

**Comment by robertbielas** [comment]
@cbaudia Sorry for the delay. You are correct. For newer devices (technically every Model except SMART_BEACON) Ibeacon's objects will have nulled uniqueId. UniqueId for ibeacon is still included in sdk only for compatibility reasons with SMART_BEACON Model. 

Only SecureProfile's uniqueId property will not be nulled (as you noted.)
