### ISSUE TITLE
android:exported for BackgroundScanBroadcastReceiver

### ISSUE THREAD

**Issue by pubiqq** [kontaktio/kontakt-android-sdk#208]
Please, add [`android:exported`](https://developer.android.com/guide/topics/manifest/receiver-element#exported) attribute to `com.kontakt.sdk.android.ble.service.BackgroundScanBroadcastReceiver` in `AndroidManifest` due to [Android 12 behavior changes](https://developer.android.com/about/versions/12/behavior-changes-12#exported).
I recommend setting the value `false`, but if you want for some reason to set `true`, please also configure [`android:permission`](https://developer.android.com/guide/topics/manifest/receiver-element#prmsn) attribute for security reason.

**Comment by pubiqq** [comment]
@robertbielas, soft push.

**Comment by robertbielas** [comment]
@pubiqq hah, your soft pushes are pure gold. 

Alright, it will be added, no problem. ;)

**Comment by robertbielas** [comment]
@pubiqq sdk 5.0.14 sets exported = false for BackgroundScanBroadcastReceiver in sdk's manifest. 
Stay tuned for changelog.

**Comment by pubiqq** [comment]
Yep, I confirm this, thank you!
