### ISSUE TITLE
Android 12 support

### ISSUE THREAD

**Issue by pubiqq** [kontaktio/kontakt-android-sdk#209]
Need to support Android 12 for this library.

In particular:
- All PendingIntents [must specify the mutability](https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability)
- The library should be aware of the [new Bluetooth permissions](https://developer.android.com/about/versions/12/features/bluetooth-permissions)

**Comment by pubiqq** [comment]
@robertbielas, boop.

**Comment by robertbielas** [comment]
@pubiqq Sorry for the delay. Yes, you are 100% right about the first item. 
About the second item, sdk will add new permissions to its manifest. It will be, however, the application's responsibility to ask about runtime permissions. 

One note: if the app does not set the target to 31 (e.g. it is 30 and lower), everything works smoothly even without mutability / permissions. Problems indeed happen when the app targets Android 12 explicitly.

**Comment by robertbielas** [comment]
So to summarize, the changes that will be published in sdk 5.0.15 (among others):
- Adding mutable flag to the pending intent
- Attaching android.permission.BLUETOOTH_CONNECT and android.permission.BLUETOOTH_SCAN to the sdk's manifest.

**Comment by pubiqq** [comment]
> - Adding mutable flag to the pending intent

What was the reason to use `PendingIntent.FLAG_MUTABLE` inside `ScannerUtil` class instead of the [strongly recommended](https://developer.android.com/about/versions/12/behavior-changes-12#create-immutable-pending-intents) `PendingIntent.FLAG_IMMUTABLE`?

> - Attaching android.permission.BLUETOOTH_CONNECT and android.permission.BLUETOOTH_SCAN to the sdk's manifest

That was unnecessary, a developer can add these permissions himself (IMHO, I would roll back this change). 
The main problem is in `checkPermissions()` method inside `AbstractServiceConnector` class. This method still knows nothing about new permissions, so it will throw exceptions when trying to start the service just like the previous version.

**Comment by robertbielas** [comment]
1. SDK starts scanning passing PendingIntent with FLAG_UPDATE_CURRENT. This makes PendingIntent mutable. 
2. This will be corrected in the next version, thanks for noting this! 
3. Correct, developers can do this, the only reason I see not to rollback changes is that it helps satisfying the Android Studio's Linter - instead of sprinkling @Supress annotations everywhere, this version can remove those altogether by adding the permissions to the Manifest (cosmetics, but still :) ).

**Comment by robertbielas** [comment]
@pubiqq Sdk 5.0.16 changes checkPermissions() in this way:

    PermissionsUtils.checkPermissions(context, REQUIRED_PERMISSIONS);
    if(Build.VERSION.SDK_INT < Build.VERSION_CODES.S) {
      PermissionsUtils.checkPermissions(context, PERMISSIONS_PRE_12);
    } else {
      PermissionsUtils.checkPermissions(context, PERMISSIONS_ANDROID_12);
    }
    PermissionsUtils.checkAtLeastOneMarshmallowPermissionGranted(context, PERMISSIONS_MARSHMALLOW);
    
where: 
    
    private static final String[] REQUIRED_PERMISSIONS = new String[] {
          Manifest.permission.INTERNET,
    };

    private static final String[] PERMISSIONS_PRE_12 = new String[] {
      Manifest.permission.BLUETOOTH,
      Manifest.permission.BLUETOOTH_ADMIN,
    };

    private static final String[] PERMISSIONS_MARSHMALLOW = new String[] {
      Manifest.permission.ACCESS_FINE_LOCATION,
      Manifest.permission.ACCESS_COARSE_LOCATION,
    };

    @TargetApi(Build.VERSION_CODES.S)
    private static final String[] PERMISSIONS_ANDROID_12 = new String[] {
          Manifest.permission.BLUETOOTH_SCAN,
          Manifest.permission.BLUETOOTH_CONNECT
    };

**Comment by pubiqq** [comment]
>> What was the reason to use `PendingIntent.FLAG_MUTABLE` inside `ScannerUtil` class instead of the strongly recommended `PendingIntent.FLAG_IMMUTABLE`?
> 1. SDK starts scanning passing PendingIntent with FLAG_UPDATE_CURRENT. This makes PendingIntent mutable

You [can use](https://developer.android.com/reference/kotlin/android/app/PendingIntent#flag_update_current) `PendingIntent.FLAG_UPDATE_CURRENT` with `PendingIntent.FLAG_IMMUTABLE`.

> Sdk 5.0.16 changes checkPermissions() in this way ...

Unfortunately, the current implementation does not cover the case of using old bluetooth permissions on Android 12. This changes the behavior of the library and obliges us to use the new permission model, even if we don't want to.

**Comment by robertbielas** [comment]
@pubiqq 
1. In theory, the documentation says this, and you are correct here. In this particular case, though, it seems there is a mismatch between the docs and reality. Setting FLAG_IMMUTABLE causes pending intent to become "empty" (no scan data available), so the pending intent is in fact affected by setting FLAG_IMMUTABLE. 

Logs with FLAG_IMMUTABLE:
D/kontakt.io SDK: RECEIVED BROADCAST: com.kontakt.sdk.android.ble.service.ACTION_FOUND MonitorCallback: com.kontakt.sdk.android.ble.service.MonitorCallbackL$1@f151ad8
D/kontakt.io SDK: RECEIVED BROADCAST: com.kontakt.sdk.android.ble.service.ACTION_FOUND MonitorCallback: com.kontakt.sdk.android.ble.service.MonitorCallbackL$1@f151ad8
D/kontakt.io SDK: RECEIVED BROADCAST: com.kontakt.sdk.android.ble.service.ACTION_FOUND MonitorCallback: com.kontakt.sdk.android.ble.service.MonitorCallbackL$1@f151ad8

Logs with FLAG_MUTABLE: 
    RECEIVED BROADCAST: com.kontakt.sdk.android.ble.service.ACTION_FOUND MonitorCallback: com.kontakt.sdk.android.ble.service.MonitorCallbackL$1@d536e72
    Passive background scan callback type: 1
D/kontakt.io SDK: MonitorCallbackL Batch results arrived: [ScanResult{device=24:6F:28:C2:85:F2, scanRecord=ScanRecord [mAdvertiseFlags=6, mServiceUuids=null, mServiceSolicitationUuids=[], mManufacturerSpecificData={}, mServiceData={0000fe6a-0000-1000-8000-00805f9b34fb=[7, -1, 3, 0, 29, 0, 16, -17, 90, 97, -35, 0, 0, 113, 118, 111, 78, 99, 75]}, mTxPowerLevel=-2147483648, mDeviceName=PLight], rssi=-45, timestampNanos=3966976896223, eventType=27, primaryPhy=1, secondaryPhy=0, advertisingSid=255, txPower=127, periodicAdvertisingInterval=0}]
    MonitorCallbackL Batch results size: 1
    MonitorCallbackL Scan not stopped yet, processing received bytes
    Device discovered: 24:6F:28:C2:85:F2 Payload: [2, 1, 6, 22, 22, 106, -2, 7, -1, 3, 0, 29, 0, 16, -17, 90, 97, -35, 0, 0, 113, 118, 111, 78, 99, 75, 7, 9, 80, 76, 105, 103, 104, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] RSSI: -45
    
    
Note that in the first case, the system does not substitute byte array with scanned packets, so we do not observe the "rich" logs as in the second case. I am afraid that we need to leave this as it is. 
    
2. When it comes to permissions, I think this is not this simple sir. Android 12 **requires** PERMISSION_BLUETOOTH_SCAN / CONNECT and does not care about old permissions model. It makes sense to require only new permissions in this case - verified that Android 12 throws Security exception if we attempt to perform BT scan without them granted. It's the system that requires this, and the library follows:

W/System.err: java.lang.SecurityException: Need android.permission.BLUETOOTH_SCAN permission for android.content.AttributionSource@bea5105d: Starting GATT scan.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at android.bluetooth.IBluetoothGatt$Stub$Proxy.startScanForIntent(IBluetoothGatt.java:1834)
        at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:281)
        at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:186)
        at com.kontakt.sdk.android.ble.service.RunnersL$4.run(RunnersL.java:154)
        at com.kontakt.sdk.android.ble.service.ScanController$Consumer.run(ScanController.java:148)
        
        
java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@f3f06ccf: AdapterService getRemoteName
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at android.bluetooth.IBluetooth$Stub$Proxy.getRemoteName(IBluetooth.java:3395)
        at android.bluetooth.BluetoothDevice.getName(BluetoothDevice.java:1273)
        at com.kontakt.sdk.android.ble.discovery.ibeacon.IBeaconParser.getIBeaconDevice(IBeaconParser.java:71)
        at com.kontakt.sdk.android.ble.discovery.ibeacon.IBeaconDiscoverer.performDiscovery(IBeaconDiscoverer.java:56)
        
Both verified on Pixel 3 with Android 12 Beta installed.

**Comment by pubiqq** [comment]
> In theory, the documentation says this, and you are correct here. In this particular case, though, it seems there is a mismatch between the docs and reality. Setting FLAG_IMMUTABLE causes pending intent to become "empty" (no scan data available), so the pending intent is in fact affected by setting FLAG_IMMUTABLE.

I had to download the source codes and see this mismatch with my own eyes 😄
Turned out there is no contradiction with the documentation, you have just the case in which it is necessary to create an intent with the `PendingIntent.FLAG_MUTABLE` flag, so it looks like everything is fine here.

> When it comes to permissions, I think this is not this simple sir. Android 12 requires PERMISSION_BLUETOOTH_SCAN / CONNECT and does not care about old permissions model. It makes sense to require only new permissions in this case - verified that Android 12 throws Security exception if we attempt to perform BT scan without them granted.

Hmm, previously checking for new permissions returned 'PERMISSION_DENIED` for old targetSdk (specifically targetSdk = 30 and no new permissions in the manifest), but it seems this behavior has been fixed in the latest Android 12 beta (or I made a mistake last time).

Anyway, It looks like the library can now be used in Android 12 (albeit with some rough edges), thank you!

**Comment by robertbielas** [comment]
@pubiqq sdk 5.0.24 is configured like the following:

  targetSdkVersion = 30
  compileSdkVersion = 31
  
and AbstractServiceConnector uses targetSdkVersion int (as opposed to Build.VERSION.SDK_INT) to determine which permission set to require. Maybe that will do?

**Comment by robertbielas** [comment]
Forget about this. I am throwing this check away completely - it did not make sense to introduce this in the first place, just duplicating the system checks. I would understand if this forced the compilation error, but it just replaces one runtime error with another. It still requires the clients to ask the correct permissions in the first place. The next sdk will not try to force anything regarding the required permissions.

**Comment by robertbielas** [comment]
Edit: I think my monolog can end here. From now on each sdk version will come in two flavors: x.x.x, and x.x.x-pre-31. The first flavor is for clients that want to use compileSdkVersion = 31 in their apps. 

The second is for those who are not ready to perform such migration and prefer to stay on the target = 30.
The first artifact from the second flavor can be found here: 
https://repo1.maven.org/maven2/io/kontakt/mvn/sdk/5.0.25-pre-31/

x.x.x will require permissions depending on Build.VERSION.SDK_INT. So when it happens to run on Pixels, for instance, it will throw runtime exceptions if the client app did not ask Android 12 relevant permissions (BLUETOOTH_SCAN, BLUETOOTH_CONNECT). 

x.x.x-pre-31 do not know about Android 12 specific code (compileSdkVersion=30). So no runtime exceptions here for clients targeting version 30 on Pixels :)  

I will make sure those flavors are also documented in KontaktIO knowledge base.

**Comment by pubiqq** [comment]
> I am throwing this check away completely ... The next sdk will not try to force anything regarding the required permissions.

Well, I'm glad you have the opportunity to remove this useless check. It would enable me to remove the kludges that are necessary for the correct integration of the library into our application.
I look forward to it.
