### ISSUE TITLE
Beacon actions not working

### ISSUE THREAD

**Issue by silentFred** [kontaktio/kontakt-android-sdk#21]
Hi there,

I started playing around with the android SDK. I can read beacons and go nuts. I can also step into the lib code and see that my beacon's actions are fetched from the API but the actions are never executed.I have multiple actions on all my beacons to show images and open urls, yet nothing happens.

I followed the android quickstart and added all the required services and permissions.
Let me know if I can help debug?

**Comment by dawidgdanski** [comment]
Hey @silentFred apologies for a late response, busy times indeed. At the moment actions are not fully supported in Android SDK. However, to fetch actions you can use BeaconManager and KontaktApiClient.  
The ActionService and ActionManager will be refactored in the next releases. For the time being, please use the BeaconManager and  KontaktApiClient.

**Comment by dawidgdanski** [comment]
Hey @silentFred, what's the status of this issue?

**Comment by silentFred** [comment]
Will be implementing this functionality on our own backend and device
