### ISSUE TITLE
MockedImage.java - is it supposed to be there?

### ISSUE THREAD

**Issue by pubiqq** [kontaktio/kontakt-android-sdk#211]
`com/kontakt/sdk/android/ble/image_streaming/MockedImage.java` - 80Kb+ file with suspicious name, is it supposed to be in the library?

**Comment by robertbielas** [comment]
@pubiqq You are correct, it does not belong there, the next version will move it to the tests folder, thanks for noting that.

**Comment by robertbielas** [comment]
@pubiqq checkout sdk 5.0.18

**Comment by pubiqq** [comment]
Great, thanks!
