### ISSUE TITLE
Diagnostic property code 0x06

### ISSUE THREAD

**Issue by pubiqq** [kontaktio/kontakt-android-sdk#216]
`FallbackNetworkConnected` diagnostic property (code 0x06) is missing from the list of `DiagnosticPropertyIterator` properties. Is it done on purpose or is this property skipped by accident?

**Library version**: 5.0.32

**Comment by robertbielas** [comment]
@pubiqq good catch, looks it's been missed in the iterator.

**Comment by robertbielas** [comment]
Corrected, check out 6.0.0 and 7.0.0 (Android target 30 and below, Android target 31 and above, respectively). 
Decided to go with semantic versioning, it will be mentioned on the changelog page of the Kontakt's Knowledgebase soon.

**Comment by pubiqq** [comment]
Yes, it's fixed now.

As for the versions, it would be easier to remove the permission check altogether. In this case, you wouldn't have to release two almost identical libraries with different major versions.
