### ISSUE TITLE
Delete the permission check

### ISSUE THREAD

**Issue by pubiqq** [kontaktio/kontakt-android-sdk#217]
IMO, it would be nice to delete the permission check altogether.

**Comment by robertbielas** [comment]
@pubiqq I understand what you are saying. And I totally agree - I would personally **love** not being forced to publish those two different versions. 

" it would be nice to delete the permission check altogether" - here I also agree. Sdk simply wraps those security exceptions as soon as the attempt to do "unauthorized" scan has been detected. I suspect that you are correct and this check is useless (the exception is thrown either way, be it by sdk or the bluetooth stack), but the core issue remains. Removing this or not, compiling against sources of Android 12 (so compileSdkVersion=31) throws security exceptions for clients depending on this artifact who have not asked about the new relevant permissions. Thus the two version families (6.x.x, 7.x.x) being published.

Maybe I am wrong. I really appreciate your diligence here - having said that, how about we do a little experiment? Are you able to provide a simple project with the following features:
- it does not depend on kontakt sdk
- it compiles against 31 (compileSdkVersion = 31)
- it scans for packets and prints them to the standard output / on a TextView
- it does not throw security exceptions on Pixels (or other phones with Android 12) with only the old permissions granted -  the new ones are omitted. 

Are you able to do this? If yes, then it would mean that I was wrong and the two versions are really useless and we can stick to just one.

**Comment by pubiqq** [comment]
Well, it seems that you took one of the possible consequences of resolving the issue for its essence, so I "focused" the original proposal a bit.
It doesn't really bother me that there are multiple versions of libraries for different versions of Android. I am concerned that the missing permission exception appears because *all* permissions are checked before binding the service, even if the library does not need them.
However, I tried to write [a small example](https://github.com/pubiqq/kontaktsdk-experiments) that would use a single library, and it kind of works. Of course, this is not a production-ready solution, additional improvements and investigation are required, but at least the positive scenario seems to work.

**Comment by robertbielas** [comment]
Sdk 7.0.1 makes the described change.
6.0.0 is hereby dropped.
