### ISSUE TITLE
ScanStatusListener.onScanError() improvements

### ISSUE THREAD

**Issue by pubiqq** [kontaktio/kontakt-android-sdk#219]
1. Make the `ScanError` objects can be distinguished from each other without resorting to the `message` field parsing (add error code, inner exception, create different inheritors, or all together, whatever).
2. Invoke `onScanError()` if permission is required when trying to perform some operation (`BluetoothLeScanner.startScan()`, `BluetoothAdapter.startLeScan()` and so on).
3. Invoke `onScanError()` if an unexpected `Binder` class is received when binding the scan service (an exception may occur in `messengerSupplier = (SDKSupplier<Messenger>) serviceBinder` and `notificationProvider = (SDKBiProvider<Notification, Integer>) serviceBinder` lines).

**Comment by robertbielas** [comment]
@pubiqq Sounds reasonable.

**Comment by robertbielas** [comment]
sdk 7.0.3 addressed the described issues.
