### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by LaurieTrichet** [kontaktio/kontakt-android-sdk#22]
Hi,

I am developing an app using your sdk, and I have a crash on samsung devices. The exception is not passing through any of my classes, so I am not sure when it happens.

I'm using the 1.0.6 version of the kontakt sdk.

The Beacon manager is used into a start service. I have a BroadcastReceiver listening for bluetooth status to start if bluetooth is on or stop the service if bluetooth is off.

Here is the crash log :

```
Android: 4.4.2
Manufacturer: samsung
Model: SM-N9005
Date: Mon Jul 06 13:20:51 AEST 2015

java.lang.OutOfMemoryError: pthread_create (stack size 16384 bytes) failed: Try again
    at java.lang.VMThread.create(Native Method)
    at java.lang.Thread.start(Thread.java:1029)
    at com.kontakt.sdk.android.manager.ForceScanController.start(ForceScanController.java:55)
    at com.kontakt.sdk.android.manager.AbstractBeaconService.startForceScanModeIfEnabled(AbstractBeaconService.java:320)
    at com.kontakt.sdk.android.manager.AbstractBeaconService.access$200(AbstractBeaconService.java:35)
    at com.kontakt.sdk.android.manager.AbstractBeaconService$MessagingHandler.handleMessage(AbstractBeaconService.java:416)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:157)
    at android.app.ActivityThread.main(ActivityThread.java:5335)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
    at dalvik.system.NativeStart.main(Native Method)
```

Here is the initialisation of the manager in the service.

```
beaconManager = BeaconManager.newInstance(beaconManager.setMonitorPeriod(MonitorPeriod.MINIMAL);
        beaconManager.setForceScanConfiguration(ForceScanConfiguration.DEFAULT);
        BeaconMonitoringListener beaconMonitoringListener = new BeaconMonitoringListener();
        beaconManager.registerMonitoringListener(beaconMonitoringListener);
```

In case it can have any impact, I have done a work around to prevent a null pointer exception after calling beaconManager.stopMonitoring(); and then calling beaconManager.startMonitoring(); 
It seems to happens because after calling stopMonitoring() the message queue of the beaconManager is null. 

```
public void pauseMonitoring (){
    if (beaconManager != null){
        beaconManager.stopMonitoring();
    }
}

public void startMonitoringBeacon() {
    if (beaconManager == null){
        initBeaconManager ();
    }

    if (beaconManager.isBluetoothEnabled()) {
        if (getBeaconManager().isConnected()) {
            try {
                beaconManager.startMonitoring();
                displayBeaconMonitoringMessage (true);
            } catch (RemoteException e) {
                e.printStackTrace();
            } catch (NullPointerException exc){
                connect();
            }
        } else {
            connect();
        }
    }
}

public void connect() {
    try {
        beaconManager.connect(new OnServiceBoundListener() {
            @Override
            public void onServiceBound() {
                try {
                    beaconManager.startMonitoring();
                    displayBeaconMonitoringMessage (true);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
        });

    } catch (RemoteException e) {
        throw new IllegalStateException(e);
    }
}
```

Let me know if you need more info.

Thanks by advance.

**Comment by dawidgdanski** [comment]
Hey @LaurieTrichet, thanks for reporting. Force scan is a workaround we came up with in order to handle bluetooth scan more efficiently on the devices which scan ble devices with poor performance. I am including your issue to our backlog, we'll look at Force scan once again. For the time being, if you don't need the ForceScanConfiguration to be set, please disable it. Alternatively, please lengthen the force scan periods: new ForceScanConfiguration(TimeUnit.SECONDS.toMlillis(1), TimeUnit.SECONDS.toMlillis(1)).

**Comment by LaurieTrichet** [comment]
Thank you I will try that.

**Comment by dawidgdanski** [comment]
Hey @LaurieTrichet, did you experience similar error using new SDK?

**Comment by LaurieTrichet** [comment]
Hi,

I didn't see any crash since I change the code following your advice.

Thanks,

Le mar. 4 août 2015 23:54, Dawid Gdański notifications@github.com a
écrit :

**Comment by dawidgdanski** [comment]
Ok, let us know if anything changes, thanks.
