### ISSUE TITLE
Does't work on Android 12

### ISSUE THREAD

**Issue by SebOvs** [kontaktio/kontakt-android-sdk#220]
I used your sample with my custom APIKEY but my beacons are't discovered.
Test on SM-G780G (Galaxy S20 FE Android 12, One UI 4.0)

The same code works on my other Samsung device (Galaxy A03s Android 11, One UI 3.1)

Do you have an idea to solve this?

**Comment by robertbielas** [comment]
@SebOvs 
1. Which sample did you use?
2. What are your beacon models?
3. Please add this line in the onCreate() method: 
`Logger.enableAllLoggerLevels(true);`
run 
`./adb logcat > logs.txt`
in your terminal, and attach the logs from your Android 12 here. 

Optionally: What is the model of your Android 12 phone?

**Comment by robertbielas** [comment]
Closing due to lack of response. Feel free to reopen if the problem still occurs.
