### ISSUE TITLE
New dependency required when updating to version 7.0.2

### ISSUE THREAD

**Issue by XarhsSta** [kontaktio/kontakt-android-sdk#221]
Hello Kontakt team! We are using your SDK to scan for beacons, and recently we had to update it to the latest version.
When we updated to version 7.0.2, we got an error message saying that the dependency `dev.afanasev:kson-annotation:1.0`  is required by the Kontakt SDK. 
Is there a way to avoid using this external module?

Thanks for your time!

**Comment by robertbielas** [comment]
@XarhsSta What was the exact error message? Please provide it here.

**Comment by XarhsSta** [comment]
@robertbielas This is shown in the Build tab in Android Studio when building the project after updating to 7.0.2 version

> Could not find dev.afanasev:kson-annotation:1.0.
> Required by:
>     project :app > io.kontakt.mvn:sdk:7.0.2
> Search in build.gradle files

Could you tell me why this dependency is needed after the upgrade?

**Comment by robertbielas** [comment]
@XarhsSta 
1. This makes it easy to generate the boilerplate code creating JsonAdapter classes from kotlin classes.
2. Do you have this:
`
repositories {
  mavenCentral()
  jcenter()
}`

in your app/build.gradle file?

**Comment by XarhsSta** [comment]
@robertbielas
We are not using jcenter() in the build.gradle file, because it is deprecated.

**Comment by robertbielas** [comment]
@XarhsSta I see. Could you add this for the experiment sake and verify the project compiles?

**Comment by XarhsSta** [comment]
@robertbielas If we add the line for jcenter() the project compiles, without any errors. But we would prefer to not use deprecated technologies in our code.

**Comment by robertbielas** [comment]
@XarhsSta the kson lib per se is not a deprecated technology, the jcenter as a hosting repository is. Let me see what can be done so that you are not forced to add jcenter to your build script.

**Comment by robertbielas** [comment]
sdk 7.0.3 addressed the described issues.
