### ISSUE TITLE
does not recognize Beacons Pro equipment

### ISSUE THREAD

**Issue by ozarhu2049** [kontaktio/kontakt-android-sdk#223]
I have problems executing the code, when scanning BEACONS PRO, none of the devices appear, I am using ANDROID STUDIO BUMBLEBEE, I need help to be able to correctly execute the app and be able to recognize all the beacon devices.

**Comment by ozarhu2049** [comment]
![image](https://user-images.githubusercontent.com/94573452/166331666-b69f8e28-b0d2-44b6-b33f-d5c3b03c5f33.png)

**Comment by ozarhu2049** [comment]
does not recognize equipment

**Comment by robertbielas** [comment]
@ozarhu2049 Please share the logs of the sample application. 

Before gathering, please do this in your App.java
![Screen Shot 2022-05-11 at 10 43 54 AM](https://user-images.githubusercontent.com/56679305/167808519-ba1e5e12-a811-464f-98b6-273422303859.png)

**Comment by robertbielas** [comment]
Also, please share the information of the devices (uniqueId & mac address) you have in your proximity.

**Comment by ozarhu2049** [comment]
![preview](https://user-images.githubusercontent.com/94573452/167862380-2f0dcb1d-15ca-41af-8cd6-77451e42be5a.jpg)
You can see that it does not work, besides, the only thing I need to do is an app that captures data (proximity marketing), is it possible with this app sample? They do not have an app development repository to use the BEACONS PRO, as a capture of ads?

**Comment by ozarhu2049** [comment]
the only thing I need to create is an app like BLEESK, I have the platform ready, what doesn't work for me is the example app, I have written to support, I registered in development kontaktio and they didn't give me access. someone help me, I'm new to programming that connects with physical equipment, I have only developed apps that do not use any type of connection with physical equipment.

**Comment by ozarhu2049** [comment]
![image](https://user-images.githubusercontent.com/94573452/167865184-1eeac90e-d8b9-4878-b2a2-294c7ccba5ee.png)

Can you give me the code of this app, to edit it to my liking?

**Comment by robertbielas** [comment]
1. It is unknown if it is not working. Maybe the incorrect sample was used (there are a couple of them and depending on which devices you have, and most importantly how they are configured, the records will be listened to or ignored and not reported to the Activity's listeners; does not matter if it is beacon pro if it does not broadcast the appropriate packets). That is why you were asked about the logs. Please share them or we will not be able to proceed. Also, please provide the mac address and the unique id of the target beacon whose broadcast you wish to listen to.
2. No, the code of the admin app cannot be shared. You can see a sample connectivity sample: https://github.com/kontaktio/kontakt-beacon-admin-sample-app/blob/master/sample-app/src/main/java/com/kontakt/sample/samples/BeaconConfigurationActivity.java
3. Based on the limited information provided, we cannot offer any guidance whether it's possible to accomplish the requirements of your project sir.

**Comment by robertbielas** [comment]
Also, the toast message the screenshot refers to, is not made by the original sources of the BeaconProScanActivity. When do you trigger the message?

**Comment by ozarhu2049** [comment]
![image](https://user-images.githubusercontent.com/94573452/167893436-5efb1e4d-8e0f-484e-8f57-10ec0ebf05da.png)

**Comment by ozarhu2049** [comment]
`package com.kontakt.sample;

import android.Manifest;
import android.content.pm.PackageManager;
import android.os.Build;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;

import com.kontakt.sample.samples.ForegroundScanActivity;
//import com.kontakt.sample.samples.BackgroundScanActivity;
//import com.kontakt.sample.samples.BeaconConfigurationActivity;
//import com.kontakt.sample.samples.BeaconEddystoneScanActivity;
//import com.kontakt.sample.samples.BeaconProScanActivity;
//import com.kontakt.sample.samples.BeaconProSensorsActivity;
//import com.kontakt.sample.samples.KontaktCloudActivity;
//import com.kontakt.sample.samples.KontaktCloudWithCoroutinesActivity;
//import com.kontakt.sample.samples.ScanFiltersActivity;
//import com.kontakt.sample.samples.ScanRegionsActivity;
//import com.kontakt.sample.samples.android_8_screen_pause.AndroidAbove8ScanWithPausedScreen;
import com.kontakt.sample.samples.beam.PortalBeamImageActivity;

public class MainActivity extends AppCompatActivity implements View.OnClickListener {

  public static final int REQUEST_CODE_PERMISSIONS = 100;

  private LinearLayout buttonsLayout;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    setupButtons();
    checkPermissions();
  }

  //Setting up buttons and listeners.
  private void setupButtons() {
    buttonsLayout = findViewById(R.id.buttons_layout);

    //final Button beaconsScanningButton = findViewById(R.id.button_scan_beacons);
    //final Button beaconsProScanningButton = findViewById(R.id.button_scan_beacons_pro);
    //final Button scanRegionsButton = findViewById(R.id.button_scan_regions);
    //final Button scanFiltersButton = findViewById(R.id.button_scan_filters);
    //final Button backgroundScanButton = findViewById(R.id.button_scan_background);
    final Button foregroundScanButton = findViewById(R.id.button_scan_foreground);
    //final Button configurationButton = findViewById(R.id.button_beacon_config);
    //final Button beaconProSensorsButton = findViewById(R.id.button_scan_beacons_pro);
    //final Button kontaktCloudButton = findViewById(R.id.button_kontakt_cloud);
    final Button beamImageButton = findViewById(R.id.button_beam_image);
    //final Button pausedScreenScanButton = findViewById(R.id.button_scan_with_paused_screen);
    //final Button kontaktCloudWithCoroutinesButton = findViewById(R.id.button_kontakt_cloud_with_coroutines);

    //beaconsScanningButton.setOnClickListener(this);
    //beaconsProScanningButton.setOnClickListener(this);
    //scanRegionsButton.setOnClickListener(this);
    //scanFiltersButton.setOnClickListener(this);
    //backgroundScanButton.setOnClickListener(this);
    foregroundScanButton.setOnClickListener(this);
    //configurationButton.setOnClickListener(this);
    //beaconProSensorsButton.setOnClickListener(this);
    //kontaktCloudButton.setOnClickListener(this);
    beamImageButton.setOnClickListener(this);
    //pausedScreenScanButton.setOnClickListener(this);
    //kontaktCloudWithCoroutinesButton.setOnClickListener(this);
  }

  //Since Android Marshmallow starting a Bluetooth Low Energy scan requires permission from location group.
  private void checkPermissions() {
    String[] requiredPermissions = Build.VERSION.SDK_INT < Build.VERSION_CODES.S
            ? new String[]{Manifest.permission.ACCESS_FINE_LOCATION}
            : new String[]{ Manifest.permission.BLUETOOTH_SCAN, Manifest.permission.BLUETOOTH_CONNECT, Manifest.permission.ACCESS_FINE_LOCATION };
    if(isAnyOfPermissionsNotGranted(requiredPermissions)) {
      ActivityCompat.requestPermissions(this, requiredPermissions, REQUEST_CODE_PERMISSIONS);
    }
  }

  private boolean isAnyOfPermissionsNotGranted(String[] requiredPermissions){
    for(String permission: requiredPermissions){
      int checkSelfPermissionResult = ContextCompat.checkSelfPermission(this, permission);
      if(PackageManager.PERMISSION_GRANTED != checkSelfPermissionResult){
        return true;
      }
    }
    return false;
  }

  @Override
  public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
    if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
      if (REQUEST_CODE_PERMISSIONS == requestCode) {
        Toast.makeText(this, "Permisos concedidos!", Toast.LENGTH_SHORT).show();
      }
    } else {
      disableButtons();
      Toast.makeText(this, "Los permisos de ubicación se activan con versiones de BLE 6", Toast.LENGTH_LONG).show();
    }
  }

  @Override
  public void onClick(View view) {
    switch (view.getId()) {
      //case R.id.button_scan_beacons:
      //  startActivity(BeaconEddystoneScanActivity.createIntent(this));
      //  break;
      //case R.id.button_scan_beacons_pro:
      //  startActivity(BeaconProScanActivity.createIntent(this));
      //  break;
      //case R.id.button_scan_filters:
      //  startActivity(ScanFiltersActivity.createIntent(this));
      //  break;
      //case R.id.button_scan_regions:
      //  startActivity(ScanRegionsActivity.createIntent(this));
      //  break;
      //case R.id.button_scan_background:
      //  startActivity(BackgroundScanActivity.createIntent(this));
      //  break;
      case R.id.button_scan_foreground:
        startActivity(ForegroundScanActivity.createIntent(this));
        break;
      //case R.id.button_beacon_config:
      //  startActivity(BeaconConfigurationActivity.createIntent(this));
      //  break;
      //case R.id.button_scan_beacons_pro:
      //  startActivity(BeaconProSensorsActivity.createIntent(this));
      //  break;
      //case R.id.button_kontakt_cloud:
      //  startActivity(KontaktCloudActivity.createIntent(this));
      //  break;
      case R.id.button_beam_image:
       startActivity(PortalBeamImageActivity.createIntent(this));
        break;
      //case R.id.button_scan_with_paused_screen:
      //  startActivity(AndroidAbove8ScanWithPausedScreen.createIntent(this));
      //  break;
      //case R.id.button_kontakt_cloud_with_coroutines:
      //  startActivity(KontaktCloudWithCoroutinesActivity.createIntent(this));
      //  break;
    }
  }

  private void disableButtons() {
    for (int i = 0; i < buttonsLayout.getChildCount(); i++) {
      buttonsLayout.getChildAt(i).setEnabled(false);
    }
  }

}`
this is my main activity

**Comment by robertbielas** [comment]
Yes, and the modified activity that does the scanning?

**Comment by robertbielas** [comment]
Make sure you listen to ibeacons and eddystones. Try out other samples, not only the one that listens to secure profiles - your Beacon Pro 16 probably does not broadcast kontakt frames. Add IBeaconListener / EddystoneListener implementation as e.g. in the ScanFilltersActivity.

**Comment by robertbielas** [comment]
Closing, assuming other examples work. Reopen if they did not.
