### ISSUE TITLE
ErrorCode in KontaktDeviceConnection.ConnectionListener's onErrorOccured

### ISSUE THREAD

**Issue by XarhsSta** [kontaktio/kontakt-android-sdk#225]
Hello Kontakt team,

I am using the [KontaktDeviceConnection.ConnectionListener](https://kontaktio.github.io/kontakt-android-sdk/4.0.2/Javadoc/com/kontakt/sdk/android/ble/connection/KontaktDeviceConnection.ConnectionListener.html#onErrorOccured-int-) and I want to know the different errorCode values so I can map a different text for each specific errorCode. I couldn't find any mention of it in the documentation for it. Can you please share with me the different errorCode values and what each value means as an error?

Thanks for your time.

**Comment by robertbielas** [comment]
@XarhsSta This article is good: https://medium.com/@abrisad_it/ble-error-codes-a3c6675b29c1. Theoretically any of those codes could be thrown, but from experience the most common one is simply 133 ("umbrella" error). Those are low-level, bt-stack-specific errors. Best strategy is to actually retry opening the connection if any of them occurs. 😞

**Comment by XarhsSta** [comment]
@robertbielas Thanks for your answer. Not the one I was looking for, but an answer nonetheless. I will add a flow in my app about retrying the connection in case of failure
