### ISSUE TITLE
Can't Apply Configuration to a Beacon in Android 13

### ISSUE THREAD

**Issue by XarhsSta** [kontaktio/kontakt-android-sdk#226]
Hello Kontakt team. 

I use the Kontakt SDK to apply a new configuration to my Beacons, but since I updated my device to Android 13 I am not able to do it. Initially I thought it was an issue of my app, but I also installed the Kio Setup Manager app to apply a new configuration via that app, and I could not. 
So I think it is an issue of the Kontakt SDK. Is it a known issue? Have you planned a new version release for it?

Thanks for your time!

**Comment by robertbielas** [comment]
@XarhsSta Please share the logs containing the error message and stack trace.

**Comment by XarhsSta** [comment]
@robertbielas Since opening this issue, it seems the bug was fixed, without updating the dependency in my app. Also the issue was fixed in Kio Setup Manager app without updating it. Maybe the issue was server side? Anyway the issue is now fixed and I will close this issue
