### ISSUE TITLE
regression- startScan failure on Android < 8

### ISSUE THREAD

**Issue by psam44** [kontaktio/kontakt-android-sdk#227]
My app works with 5.0.25, but no more with 7.0.8. The error is:
```
E/kontakt.io SDK: monitor-message-consumer-thread interrupted, thrown exception:
 No virtual method startScan(Ljava/util/List;Landroid/bluetooth/le/ScanSettings;Landroid/app/PendingIntent;)I
 in class Landroid/bluetooth/le/BluetoothLeScanner; or its super classes
```

My device is Android N, and indeed this signature appeared in API 26.
It seems that the culprit is in ScanCompatL.java, in method createScanController():

```
    return shouldPerformAndroid8Scan(...)
            ? createScanControllerL(...)
            : createScanControllerO(...);

```
The logic is simply the inverse that it should be (typo).

**Comment by robertbielas** [comment]
@psam44 You are correct, there was a typo. Checkout sdk 7.0.9.1 and see if this fixes the problem for you. Note - there are a couple of other changes / fixes in this artifact as well.

**Comment by psam44** [comment]
It works again with 7.0.9.1, thanks.
