### ISSUE TITLE
typo in log: "D/SDK: : Stopping monitoring"

### ISSUE THREAD

**Issue by psam44** [kontaktio/kontakt-android-sdk#228]
Compared to: "D/SDK: Starting monitoring".

In ScanController.java

**Comment by robertbielas** [comment]
@psam44 Could you elaborate? Not sure I follow.

**Comment by robertbielas** [comment]
Do you mean this: Logger.d(": Stopping monitoring"); 
? You dislike the colon in this log, correct?

**Comment by robertbielas** [comment]
Typo corrected in sdk 7.0.10.
