### ISSUE TITLE
Candidate for NPE in InternalProximityManager

### ISSUE THREAD

**Issue by psam44** [kontaktio/kontakt-android-sdk#229]
It is in internal code, so it will never happen, but ...
```
        try {
          //noinspection unchecked
          messengerSupplier = (SDKSupplier<Messenger>) serviceBinder;
        } catch (ClassCastException e) {
          proximityListener.onScanError(
```
(same with `notificationProvider`)
At this stage, `proximityListener` is not yet valued, so an NPE fires.

**Comment by sb-kio** [comment]
Thank you for spotting this issue. This problem was resolved in the latest SDK version 7.0.12.1.
