### ISSUE TITLE
Please tell me BeaconLayout 

### ISSUE THREAD

**Issue by kiledar2006** [kontaktio/kontakt-android-sdk#23]
Hello,

I need Kontakt Beacon Layout, please tell me Kontakt BeaconLayout.

**Comment by dawidgdanski** [comment]
Hey @kiledar2006 , unfortunately I don't know how to help you. How would the Kontakt Beacon Layout look like?

**Comment by dawidgdanski** [comment]
Hey @kiledar2006 what's the status of this issue?
