### ISSUE TITLE
Xamarin Support

### ISSUE THREAD

**Issue by DavePilks** [kontaktio/kontakt-android-sdk#24]
Hi

Do you have Xamarin bindings for your Android SDK? iOS is fine as it is complient with iBeacon but I am stumped for Android. I have tried to do the bindings myself but am coming up short.

**Comment by dawidgdanski** [comment]
Hey @DavePilks at the moment binding to Xamarin is not planned but thanks for reporting, I am pasting your issue to our backlog.
