### ISSUE TITLE
Expose readRemoteRssi

### ISSUE THREAD

**Issue by theindexer** [kontaktio/kontakt-android-sdk#25]
It'd be useful to be able to read the rssi while connected to the beacon.  It looks like readRemoteRssi should take care of that, would be nice to have some access to that instead of just an empty implementation in the onReadRemoteRssi portion of the GattCallback.

**Comment by dawidgdanski** [comment]
Hey @theindexer, thanks for the suggestion, I am pasting your issue to our backlog, thanks again.
