### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by fvlgnn** [kontaktio/kontakt-android-sdk#26]
The timestamp value is recorded only at the first contact with the beacon and it doesn’t update as the other values of beacon (eg. Rssi, proximity, etc.).
For update the timestamp we have to exit from the activity and to launch a new scan.
The timestamp function update is provided in your SDK for Android ?
I use BeaconManager and void onBeaconsDiscovered 
An example on BeaconRangeActivityunder ui, activity of kontakt-beacon-admin-sample-app

**Comment by dawidgdanski** [comment]
Hey @fvlgnn the timestamp value refers to the time when IBeacon is discovered for the first time: http://kontaktio.github.io/Android-SDK/Javadoc/com/kontakt/sdk/android/device/BeaconDevice.html#getTimestamp--

**Comment by dawidgdanski** [comment]
Hey again, thanks for reporting btw, we'll consider including updated timestamp value.

**Comment by dawidgdanski** [comment]
Hey @fvlgnn, we released the new version of the SDK. To obtain updated timestamp value, check the 
[BluetoothDeviceEvent](http://kontaktio.github.io/Android-SDK/2.0.0/Javadoc/com/kontakt/sdk/android/ble/discovery/BluetoothDeviceEvent.html).
