### ISSUE TITLE
Sleep mode

### ISSUE THREAD

**Issue by mw-cosmose** [kontaktio/kontakt-android-sdk#27]
Hi,

I'm interested to know how the sdk handles android device going into sleep mode. Will it pause monitoring/ranging or try to keep it alive by acquiring wake lock? 

Thanks :)

**Comment by dawidgdanski** [comment]
Hey @mw-cosmose, acquiring wake lock does not leverage bluetooth scan provided by BeaconManager. You must handle it on your own.

**Comment by mw-cosmose** [comment]
Do you mean that if monitoring is started and the device goes to sleep shortly after then the monitoring will freeze? I can acquire a wake lock when monitoring starts and release it afterwards, but I cannot efficiently handle monitoring periods i.e. wake the device when its time for another round of scans.

**Comment by dawidgdanski** [comment]
Do you mean that if monitoring is started and the device goes to sleep shortly after then the monitoring will freeze?

If you configure BeaconManager's scan to be stopped then yes, the scan will freeze. But it is your responsibility, not the SDK's. The SDK does not interact with Wakelock, what would be the point of including such functionality?
