### ISSUE TITLE
Beacon detection issues in Ranging

### ISSUE THREAD

**Issue by paxbat14** [kontaktio/kontakt-android-sdk#28]
With the help of ranging (onBeaconsDisovered()) I am trying to detect beacons. When I have 4 beacons in the vicinity method return me 4 beacons but when I have turned off any 3 beacons practically I suppose to receive only 1 beacon which is in the vicinity but unfortunately with the help onBeaconsDiscovered() I am receiving 4 beacons.

Can you please do let us know due to what cause this is happening?
Thanks in advance

**Comment by dawidgdanski** [comment]
Hey @paxbat14, do you include [BeaconActivityCheckConfiguration](http://kontaktio.github.io/Android-SDK/Javadoc/com/kontakt/sdk/android/configuration/BeaconActivityCheckConfiguration.html) to the `BeaconManager` during the configuration part? Could you provide any code?

**Comment by dawidgdanski** [comment]
Hey @paxbat14 what's the status of this issue?

**Comment by paxbat14** [comment]
hi Thank you @dawidgdanski I have already include BeaconActivityCheckConfiguration but it won't work for me. I am still results which is always on toss.
