### ISSUE TITLE
Issue with setDistanceSort

### ISSUE THREAD

**Issue by emtt** [kontaktio/kontakt-android-sdk#29]
[...]
mBeaconManager.setDistanceSort(DistanceSort.ASC);

[...]
 public void onBeaconsUpdated(final Region region, final List<BeaconDevice> beacons) {
int pos = 0;
    for(BeaconDevice beacon:beacons) {
        Log.wtf("BeaconList", "Pos: "+pos+ " Minor: "+ beacon.getMinor() + " Distance: " + beacon.getAccuracy());
    pos ++;
}
...

Result in this:

Pos: 0 Minor: 1074 Distance: 1.440510248595126 <- OK
Pos: 1 Minor: 1059 Distance: 3.967965270075985 <- Hum?
Pos: 2 Minor: 1084 Distance: 2.038887307946296 <- RLY?

why did this happen?

**Comment by dawidgdanski** [comment]
Hey @emtt, I'm including the issue in our backlog with bug fixes. Upgrade the SDK to the latest version please and let me know if this happens.

**Comment by emtt** [comment]
Ok, thank you @dawidgdanski. I will test it.

**Comment by dawidgdanski** [comment]
Hey @emtt what's the status of this issue?

**Comment by jakubkontakt** [comment]
@emtt Please check version 2.0.1.

For now I am closing issue and will reopen if still applicable
