### ISSUE TITLE
Android Application Sample not working

### ISSUE THREAD

**Issue by mrakha** [kontaktio/kontakt-android-sdk#3]
I have Kontakt beacons, and trying to use the code in the documentation and here to scan and display content on finding the beacon, but the problem is that the code provided is giving errors.

So please advise which part we can use to scan for beacons.

**Comment by dawidgdanski** [comment]
Hey @mrakha ,
You asked the same question in two projects. Please, raise project-specific issues in a proper place next time.

Thanks,
Dawid
