### ISSUE TITLE
kontakt Smart Beacons  gives wrong distance 

### ISSUE THREAD

**Issue by rishi-ios** [kontaktio/kontakt-android-sdk#30]
Hi,

we are using Kontakt Smart Beacons to locate user distance from door via beacon (Both in iOS and Android).

we are using latest iOS SDK (6.0) and Android SDK (2.0) to locate beacon distance. We get two readings "accuracy" and "proximity" which we are considering to calculate distance from Beacon.

Even if I am near the beacon the "accuracy" and "proximity" values keeps on fluctuating very often. Is that the expected behaviors, for eg: Accuracy ranges between 0.4 - 5.5 at the same spot.

Please let us know if "accuracy" is the parameter of distance from beacon ? If so what is the measure - Meters / Feets ?

Also, at time we get accuracy as negative value, what does that imply ?

Thanks

**Comment by dawidgdanski** [comment]
Hey @rishi-ios apologies for late response, busy times indeed. 

Please let us know if "accuracy" is the parameter of distance from beacon ? 
As far as I know, yes, on iOS the accuracy but iOS guys need to clarify that @stoprocent @hlebowicz-kontakt .  in Android SDK v2.0.0 `getAccuracy()` (previous versions) was renamed to `getDistance()`.

 If so what is the measure - Meters / Feets ?
Android SDK - meters.

Also, at time we get accuracy as negative value, what does that imply ?
I'm including the report as a bug, we'll see what causes the distance to be negative, cannot give you the exact  response at the moment.

As a workaround you can include filter that will accept beacons to be notified from specific range of distance. This will ensure that you will not receive beacons with negative distance.

Secondly, regarding the range (0.4 - 5.5 at the same spot). To make the rssi signal of scanned devices ranging more smoothly, use [RssiCalculator](http://kontaktio.github.io/Android-SDK/2.0.0/Javadoc/com/kontakt/sdk/android/ble/rssi/RssiCalculator.html) during [ScanContext](http://kontaktio.github.io/Android-SDK/2.0.0/Javadoc/com/kontakt/sdk/android/ble/configuration/scan/ScanContext.html) construction.

**Comment by dawidgdanski** [comment]
Hey @rishi-ios what's the status of this issue?

**Comment by rishi-ios** [comment]
Thanks for reply. Right now the new Android SDK is giving fairly good accuracy results but iOS SDK is giving us fairly inaccurate distance from the beacons. 

I have not got any reply from iOS guys  @stoprocent @hlebowicz-kontakt . Please let me know what can we do to get good accuracy results in iOS App.

**Comment by stoprocent** [comment]
@rishi-ios @dawidgdanski accuracy in iOS is calculated on a system level. Have a look in Apple Documentation for CLBeacon. We dont have any control over this.
