### ISSUE TITLE
Conflict Jar file with jcifs.jar file 

### ISSUE THREAD

**Issue by vminfra** [kontaktio/kontakt-android-sdk#31]
Hi, I am trying to integrate beacon with my app that is having exchange server communication facility . I am trying to add "android.sdk.1.0.6.jar" and "coresdk1.0.6.jar" jar file in my app But it is conflict with my existing jar file "jcifs.jar" . I can not do exchange server work with out "jcifs.jar" as it is important for my app . Now when I am trying to add "coresdk1.0.6.jar" and "android.sdk.1.0.6.jar" I can not run my app and it is showing multiple dex file . Please help me!

jsifc.jar file is used for communicate with ms exchange server.

**Comment by dawidgdanski** [comment]
Hey @vminfra, thanks for reporting, could you please paste any error logs that you've received?

**Comment by vminfra** [comment]
Unable to execute dex: method ID not in [0, 0xffff]: 65536
[14:42:50] Abakasha Panda: Conversion to Dalvik format failed: Unable to execute dex: method ID not in [0, 0xffff]: 65536

This came when I added "android.sdk.1.0.6.jar" and "coresdk1.0.6.jar".

My app is already having "jcifs.jar" for exchange server use.

**Comment by dawidgdanski** [comment]
Hey @vminfra you exceeded magic limitation of  2^16 of methods in your app. To solve the problem you either must enable [MultiDex in your application](https://developer.android.com/tools/building/multidex.html) or use ProGuard.

**Comment by vminfra** [comment]
I used proguard then enable multidex but its not working....
If I remove "jcifs.jar" then its running but not able to communicate with exchange server without this jar file so I am using this.

**Comment by dawidgdanski** [comment]
How about using 2.0.0 SDK version?

**Comment by vminfra** [comment]
which jar file of 2.0.0 version????

**Comment by vminfra** [comment]
Checking with 2.0.0 now

**Comment by vminfra** [comment]
There are 2 jar file in 1.0.6
there are 4 jar file inside 2.0.0 , we will use all jar file or any specific one???

**Comment by vminfra** [comment]
Once I add all file I am not getting the BeaconManager class

and it is showing same error like before ...multiple dex

After adding all jar files I am getting below  problem
![kontakt](https://cloud.githubusercontent.com/assets/10059366/8980973/254e3f94-36d2-11e5-99b6-22bd2aaf1d58.PNG)

**Comment by vminfra** [comment]
Is there any clue to solve this issue?
