### ISSUE TITLE
Conflict Jar file with jcifs.jar file

### ISSUE THREAD

**Issue by vminfra** [kontaktio/kontakt-android-sdk#32]
Hi, I am trying to integrate beacon with my app that is having exchange server communication facility . I am trying to add "android.sdk.1.0.6.jar" and "coresdk1.0.6.jar" jar file in my app But it is conflict with my existing jar file "jcifs.jar" . I can not do exchange server work with out "jcifs.jar" as it is important for my app . Now when I am trying to add "coresdk1.0.6.jar" and "android.sdk.1.0.6.jar" I can not run my app and it is showing multiple dex file . Please help me!

jsifc.jar file is used for communicate with ms exchange server.

this is the error

Unable to execute dex: method ID not in [0, 0xffff]: 65536
[14:42:50] Abakasha Panda: Conversion to Dalvik format failed: Unable to execute dex: method ID not in [0, 0xffff]: 65536

This came when I added "android.sdk.1.0.6.jar" and "coresdk1.0.6.jar".

My app is already having "jcifs.jar" for exchange server use.

dawidgdanski answered this:

Hey @vminfra you exceeded magic limitation of 2^16 of methods in your app. To solve the problem you either must enable MultiDex in your application or use ProGuard.

This was the result.

I used proguard then enable multidex but its not working....
If I remove "jcifs.jar" then its running but not able to communicate with exchange server without this jar file so I am using this.

How about using 2.0.0 SDK version?

Once I add all file I am not getting the BeaconManager class

and it is showing same error like before ...multiple dex

After adding 2.0.0 all jar files I am getting below problem

![kontakt](https://cloud.githubusercontent.com/assets/10059366/8983014/188a6690-36e4-11e5-8f85-11475a3a2358.PNG)

**Comment by dawidgdanski** [comment]
Read the [quickstart](http://docs.kontakt.io/android-sdk/2.0.0/quickstart/) please and try out the [sample app](https://github.com/kontaktio/kontakt-beacon-admin-sample-app), should help.
