### ISSUE TITLE
Not working Beacon monitoring when app killed or closed

### ISSUE THREAD

**Issue by subbu1234** [kontaktio/kontakt-android-sdk#33]
Beacon monitoring working when app is in foreground or background but not working when app killed or closed. Please provide solution.

**Comment by subbu1234** [comment]
Dear Dawidgdanski, 
          Is it possible to get notifications when app killed? We require this when beacon detected. Please provide solutions for this. Thanks in advance.

**Comment by pravinuttarwar** [comment]
Any solution to this issue? Or it is fixed? Please comment, we also need to implement same thing in our app.

**Comment by jakubkontakt** [comment]
It is not an issue. This is normal behaviour of all Android applications. Each application has different process, when process is killed then your application is killed also. Please read more about processes and threading: http://developer.android.com/guide/components/processes-and-threads.html. 

 There is no way to scan beacons on Android without hosting process.
