### ISSUE TITLE
DEVICE_LOST always called directly after DEVICE_DISCOVERED in SDK 2.0.0

### ISSUE THREAD

**Issue by Dadoffak** [kontaktio/kontakt-android-sdk#37]
I migrated my project from SDK 1.0.6 to 2.0.0 and now I experience extrem problems concerning the detection that a beacon isn't in reach anymore.
As soon as I use ActivityCheckConfiguration (I tried it with several value combination) directly after a beacon was discovered the DEVICE_LOST event is sent for the previously discovered beacon.
It's always the combination first DEVICE_DISCOVERED after that DEVICE_LOST.
The configuration I used is attached below.
When I use ActivityCheckConfiguration.DISABLED, DEVICE_LOST is never called, which is not an alternative, since I need to know when a beacon is out of reach.

SDK 1.0.6 worked better in this part. I use an Nexus 4 with the newest Android Version. I wrap the SDK in my own Service in my project.

Please tell what the problem is. Currently SDK 2.0.0 is not usable for me.

ActivityCheckConfiguration myActivityCheckConfiguration = new ActivityCheckConfiguration(TimeUnit.SECONDS.toMillis(10), TimeUnit.SECONDS.toMillis(2));

scanContext = new ScanContext.Builder()
        .setScanMode(ProximityManager.SCAN_MODE_LOW_LATENCY)
        .setScanPeriod(new ScanPeriod(TimeUnit.SECONDS.toMillis(5), TimeUnit.SECONDS.toMillis(2))) // scan, sleep
        .setForceScanConfiguration(ForceScanConfiguration.DISABLED)
        .setActivityCheckConfiguration(myActivityCheckConfiguration) //test
        .setIBeaconScanContext(new IBeaconScanContext.Builder()
            .setDevicesUpdateCallbackInterval(TimeUnit.SECONDS.toMillis(1))
            .setDistanceSort(DistanceSort.DESC)
            .build()
        ).build();

**Comment by jakubkontakt** [comment]
It is subtle bug in SDK, we already have bugfix for that. Release on new version will be soon,

**Comment by jakubkontakt** [comment]
Fixed in 2.0.1

**Comment by bradleywildman** [comment]
Hi,
I too received this bug above, upon reading that there was a bug fix which was 2.0.1 i have migrated the correct jar files into my project, when i run my application it works however the bugfix doesn't appear to have worked, when looking at my logcat i am getting these logs:

12-08 14:11:31.539 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: onCreate
12-08 14:11:31.565 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: onResume
12-08 14:11:31.698 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: onServiceReady
12-08 14:11:31.988 4852-4923/com.example.bradleywwildman.practiseapp D/iBeacon: case : onScanStart
12-08 14:13:59.690 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:13:59.690 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_DISCOVERED
12-08 14:13:59.816 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:13:59.816 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_DISCOVERED
12-08 14:14:01.819 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:14:01.819 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_DISCOVERED
12-08 14:14:11.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:14:11.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_LOST
12-08 14:14:11.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:14:11.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_LOST
12-08 14:14:51.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:14:51.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_LOST
12-08 14:14:57.747 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:14:57.747 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_DISCOVERED
12-08 14:15:16.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:15:16.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_LOST
12-08 14:15:57.038 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:15:57.038 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_DISCOVERED
12-08 14:16:36.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:16:36.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_LOST

These are the same logs i was getting from using to 2.0.0 JAR files. Can you please re-open this as a bug as i have updated all the necessary files and i am still getting the same errors also If you could get back to me with some technical support that would be great.

Thanks :)
