### ISSUE TITLE
Eddystone beacon get Action

### ISSUE THREAD

**Issue by MH-Python** [kontaktio/kontakt-android-sdk#39]
I am trying to get an eddystone beacon action throw the this code:

DevicesApiAccessor devicesApiAccessor = new KontaktApiClient();

devicesApiAccessor.getActionsForDevice(proximityUUID, major, minor, new ResultApiCallback() { 
@Override 
public void onSuccess(HttpResult result) {

}

@Override 
public void onFailure(ClientException e) {

} 
});

but it always return this:
java.lang.IllegalStateException: Invalid http status: 404 (Resource not found). Result is null

**Comment by jakubkontakt** [comment]
Hi,

It seems that you are using wrong method from DevicesApiAccessor for pulling eddystone actions. For eddystone is another method: 

getActionsForDevice(String namespace, String instanceId, ResultApiCallback<List<IAction>> apiCallback);

**Comment by MH-Python** [comment]
thank you for your quick answer

**Comment by MH-Python** [comment]
Hi again
I can't find this method 
getActionsForDevice(String namespace, String instanceId, ResultApiCallback> apiCallback);

and I'm using android SDK 2.0
compile 'com.kontakt.sdk.android:kontakt.io-android-sdk:2.0.0'

**Comment by jakubkontakt** [comment]
Hi,

Yes you are right. There is no such method in SDK for now but soon will be available. 

Before that you can use following snippet:

``` java

   kontaktApiClient.getDevice(uniqueId, new ResultApiCallback<IDevice>() {
            @Override
            public void onSuccess(HttpResult<IDevice> iDeviceHttpResult) {
                if(iDeviceHttpResult != null){
                    IDevice iDevice = iDeviceHttpResult.isPresent() ? iDeviceHttpResult.get() : null;

                    if(iDevice != null){
                        List<IContentAction> contentActions = iDevice.getContentActions();
                        List<IBrowserAction> browserActions = iDevice.getBrowserActions();
                    }
                }
            }

            @Override
            public void onFailure(ClientException e) {

            }
        });

```

**Comment by MH-Python** [comment]
Sorry but that snippet did not work for Eddystone beacon returned Resource not found
 but worked fine for IBeacon
still can't get Eddystone actions by the SDK

**Comment by MH-Python** [comment]
I also noticed that the following snippet returns only the Ibeacon and cloud devices but no Eddystones in spite I have three Eddystones in my beacons collection :

KontaktApiClient kontaktApiClient = new KontaktApiClient();
        kontaktApiClient.listDevices(new ResultApiCallback<List<IDevice>>() {
            @Override
            public void onSuccess(HttpResult<List<IDevice>> result) {

```
        }

        @Override
        public void onFailure(ClientException e) {

        }
    });
```

**Comment by jakubkontakt** [comment]
Hi @mustafahalimeh 

Sorry for such late response.

In version 2.1.1 we added possibility to get actions for beacon by unique id. Please check our developer docs: http://devdocs.kontakt.io/android-sdk/2.1.0/quickstart/

**Comment by RahaAkhtar** [comment]
@jakubkontakt Can you please share the example code? i'm new to android and i have already spend more then a day to get the Device action against kontakt beacons :( i have iOS development experience but beginner in android  :)
