### ISSUE TITLE
REST API Issue

### ISSUE THREAD

**Issue by alishak** [kontaktio/kontakt-android-sdk#4]
I have been developing a small program to update my beacons' settings through my Android device (no access to any iOS devices atm). As stated in the docs, the REST api should be used to update the settings for the kontakt.io panel.

I have implemented REST calls that return "update successful" upon modifying certain values for the beacons, however as I log into the panel, the values have not changed.

Note that that values on the actual beacons HAVE changed, and that I execute the api calls from a custom AsyncTask that is called from the onWriteSuccess methods whenever a setting is overwritten. How can I properly update the values on the web panel?

Example url to update tx power: 
"https://api.kontakt.io/device/update?&deviceType=beacon&tx_power=4&uniqueId=tk4t"

With added headers:
"Accept", "application/vnd.com.kontakt+json;version=5"
and API Key

**Comment by stoprocent** [comment]
Hi, I'm not Android developer but as far I see this is more REST API related question.
Are you sending this request using POST HTTP Method? 
Request parameters should be send as form urlencoded body.

**Comment by alishak** [comment]
Here is a code snippet used to send a POST request through HTTPS. The response String returns an "update successful." message.

Example for a name value pair:

```
NameValuePair accept = new BasicNameValuePair("Accept", "application/vnd.com.kontakt+json;version=5");


String url = "https://api.kontakt.io/device/update?&deviceType=beacon&tx_power=4&uniqueId=tk4t";

HttpPost post = new HttpPost(url);
post.addHeader(api_key.getName(), api_key.getValue());
post.addHeader(accept.getName(), accept.getValue());

try {
    post.setEntity(new UrlEncodedFormEntity(requests, HTTP.UTF_8));
} catch(UnsupportedEncodingException e) {
    Log.e("ENTITY", e.getMessage());
}

HttpClient client = new DefaultHttpClient();

HttpResponse httpResponse;

try {
    httpResponse = client.execute(post);
    int responseCode = httpResponse.getStatusLine().getStatusCode();
    String message = httpResponse.getStatusLine().getReasonPhrase();

    HttpEntity entity = httpResponse.getEntity();

    if (entity != null) {

        InputStream instream = entity.getContent();
        String response = convertStreamToString(instream);

        // Closing the input stream will trigger connection release
        instream.close();
    }

} catch (ClientProtocolException e)  {
    client.getConnectionManager().shutdown();
    e.printStackTrace();
} catch (IOException e) {
    client.getConnectionManager().shutdown();
    e.printStackTrace();
}
```

**Comment by alishak** [comment]
Note that this is all done inside an AsyncTask task

**Comment by dawidgdanski** [comment]
Hey @alishak, try sending your POST request with  the url `https://api.kontakt.io/device/update` and move all the parameters to the UrlEncodedFormEntity (http://developer.android.com/reference/org/apache/http/client/entity/UrlEncodedFormEntity.html). 

You specified incorrect parameter name to be updated. Instead of `tx_power` there should be `txPower`. I was wrong saying about case sensitivity in device type. The `deviceType` can be of type `BEACON` or `beacon`. 

To avoid the mistakes like yours, you can use KontaktApiClient which allows to perform CRU operations on `/device` resource.

Let us know once you succeed please and close the issue if everything is correct. Thanks.

**Comment by dawidgdanski** [comment]
Hey @alishak  did you succeed?

**Comment by alishak** [comment]
Hello!

In case anyone else runs into this issue, the problem was the `txPower` parameter name. I would just like to point out that there may be a typo in the documentation: http://docs.kontakt.io/rest-api/resources/#update-device

Both `UrlEncodedFormEntity` AND `NameValuePair` will work for headers.

Thank you.

**Comment by simontoulson** [comment]
Thanks @alishak - yes, the documentation was incorrect - that's corrected and flagged for update now.  Thanks.

**Comment by mittalprayag25** [comment]
Hi Everyone,

I am working on Beacon application. I have created a service that runs at
background and started it with START_STICKY.  The problem I am facing is in
registerMonitoringListener . My onRegionAbandoned and onRegionEntered
methods are getting called again and again when I am range of beacons. My
worry is when I am in range onRegionEntered  should be called once and
thats it and onRegionAbandoned  top be called when I move out of it. But
when I am in range both the functions are getting called again and again.
Is this the normal behaviour or else I am doing anything wrong.

Regards

Prayag
