### ISSUE TITLE
Unable to set only UUID to IBeaconRegion in Android SDK 2.0.0

### ISSUE THREAD

**Issue by milosgaric23** [kontaktio/kontakt-android-sdk#40]
Hi.

I have one problem. I making an app, and I need to set region for scanning, and I need to  limit scanning only on specified UUID beacons. However, I can't find anything which will allow me that, because IBeaconRegion constructor must be filled with major and minor value also, and I don't need those values to effect my region scanning. I am counting on SPACE_ENTERED and SPACE_ABANDONED event types to do my magic.

I have tried with setting filters just on UUID, but that didn't get me any benefits.

Do you have any proposal for my problem?

Best regards.

**Comment by dawidgdanski** [comment]
Could you provide the ScanContext creation part in your code? How do you apply the [IBeaconFilter](http://kontaktio.github.io/Android-SDK/2.0.0/Javadoc/)? 
Thanks

**Comment by milosgaric23** [comment]
IBeaconRegion region = new BeaconRegion(UUID.fromString(storeUuid),-1,-1);

```
    IBeaconScanContext iBeaconScanContext = new IBeaconScanContext.Builder()
            .setEventTypes(EnumSet.of(EventType.SPACE_ENTERED, EventType.SPACE_ABANDONED, EventType.DEVICES_UPDATE))
            .setIBeaconFilters(Collections.singletonList(
                    IBeaconFilters.newProximityUUIDFilter(UUID.fromString(storeUuid))
            ))
            .setIBeaconRegions(Collections.singletonList(region))
            .build();
```

I thought that setting major and minor on -1, or on 0, will make it to look on all devices with only "storeUuid" value. However, adding filter works, only devices with "storeUuid" will be scanned, but when U go into the SPACE_ENTERED, and call iBeaconDeviceEvent.getRegion().getProximityUUID(), that and UUID that I want, are completely different.

Thanks

**Comment by jakubkontakt** [comment]
If you are giving custom BeaconRegion you are forcing to scan on concrete attributes. So passing as major or minor values like 0 or any other which does not exist will cause that no devices will be discovered.

You should only add IBeaconFilters to your IBeaconScanContext to have beacons with specified Proximity UUID.

If I understand you correctly after configuring ScanContext in such way you are receiving strange proximity uuid on SPACE_ENTERED, does it work the same in DEVICE_DISCOVERED or DEVICES_UPDATE?

**Comment by milosgaric23** [comment]
In DEVICES_UPDATE, it is updating it always, and of course, because it is scanning it always, it is working like it should do, I am getting just specified UUID.

In DEVICE_DISCOVERED it is woking same as on DEVICES_UPDATE, but it is scanning it most often, and I need it to when I enter in some region, to show some notification, but with DEVICES_UPDATES  and DEVICE_DISCOVERED, it will fire those notifications rapidly, which I don't need.

I could maybe fix it using some flags, but I don't think that is an option, if we have such an awesome method: SPACE_ENTERED :)

**Comment by jakubkontakt** [comment]
Hi @milosgaric23 our latest version of SDK introduced way of defining Region only with UUID.

You can find more details in our quickstart: http://developer.kontakt.io/android-sdk/2.1.0/quickstart/
