### ISSUE TITLE
Which event will fire when user exits completly from beacon region.

### ISSUE THREAD

**Issue by subbu1234** [kontaktio/kontakt-android-sdk#41]
Hi,
 We are developing app using kontakt.io beacons and latest sdk( 2.0.0). "SPACE_ENTERED" event firing when user enters into beacon region. Which event fires when user completely exits from the beacon region. We tried with SPACE_ABANDONED event but firing even app is in the beacon proximity i.e firing even when there is no movement with in the region.
   How to know user (device or App) exited from the beacon region completely?
Thanks in advance.
Regards,
subbu

**Comment by jakubkontakt** [comment]
Have you tried changing ActivityCheckConfiguration inactivityTimeout?  That may happen that SPACE_ABANDONED will be fired even phone is in proximity of beacon due to long bluetooth scanning and slow devices recognition. 

Default values of inactivityTimeout is 5 seconds, and after that time SPACE_ABANDONED will be fired for certain region. But you can make it time longer if there is more beacons around.

**Comment by subbu1234** [comment]
Hi Jakubkontakt,
           Thanks for you immediate replay. In our app we required to know the user exit completely from the beacon proximity region. Elaborating in detail.
1) suppose user enters into beacon proximity region from the outside region. In this case "SPACE_ENTERED" event firing successfully. 
2) similarly when user exit completely from the beacon proximity region to outside region, our question is 
    Is any event to know when user exits completely from beacon proximity region?
Thanks in advance.
Regards,
subbu

**Comment by jakubkontakt** [comment]
Please update to version 2.0.1

DEVICE_LOST is event when particular device is not in range. Is that what you are asking for?

**Comment by subbu1234** [comment]
We updated to version 2.0.1 but still firing DEVICE_LOST event even though device is in the range.'
But we want the evet when user completely exit from the region.

Please help us.

**Comment by jakubkontakt** [comment]
Have you tried lengthen ActivityCheckConfiguration? I do not know what is the device you are using, but many devices has poor bluetooth performance, and to not fire DEVICE_LOST we need to scan particular beacon continuously. 

And, please use FORCE_SCAN_CONFIGURATION in your scan context.

**Comment by subbu1234** [comment]
We are using following configuration for scan context.
 ScanContext scanContext = new ScanContext.Builder()
                    .setScanMode(ProximityManager.SCAN_MODE_BALANCED)
                    .setIBeaconScanContext(iBeaconScanContext)
                    .setActivityCheckConfiguration(ActivityCheckConfiguration.DEFAULT)

```
                .setForceScanConfiguration(ForceScanConfiguration.DEFAULT)
                .setScanPeriod(new ScanPeriod(TimeUnit.SECONDS.toMillis(7), TimeUnit.SECONDS.toMillis(3)))
                .build();
```

**Comment by subbu1234** [comment]
In details we are using following code...
Set<IBeaconRegion> regionSet = new HashSet<IBeaconRegion>();
            for (int i = 0; i < lsBeaconArray.size(); i++) {
                BeaconRegion beaconRegion = new BeaconRegion(UUID.fromString(lsBeaconArray.get(i).getBeaconUUID()), Integer.parseInt(lsBeaconArray.get(i).getMajor()), Integer.parseInt(lsBeaconArray.get(i).getMinor()));
                regionSet.add(beaconRegion);
            }

```
        IBeaconScanContext iBeaconScanContext = new IBeaconScanContext.Builder()
                .setEventTypes(EnumSet.of(EventType.DEVICE_DISCOVERED,
                        EventType.DEVICE_LOST, EventType.DEVICES_UPDATE, EventType.SPACE_ENTERED, EventType.SPACE_ABANDONED))
                .setRssiCalculator(RssiCalculators.newLimitedMeanRssiCalculator(5))
                .setIBeaconRegions(regionSet)
                .build();

        ScanContext scanContext = new ScanContext.Builder()
                .setScanMode(ProximityManager.SCAN_MODE_BALANCED)
                .setIBeaconScanContext(iBeaconScanContext)
                .setActivityCheckConfiguration(ActivityCheckConfiguration.DEFAULT)

                .setForceScanConfiguration(ForceScanConfiguration.DEFAULT)
                .setScanPeriod(new ScanPeriod(TimeUnit.SECONDS.toMillis(7), TimeUnit.SECONDS.toMillis(3)))
                .build();

        proximityManager.initializeScan(scanContext, new OnServiceReadyListener() {
            @Override
            public void onServiceReady() {
                proximityManager.attachListener(regionManager);
            }

            @Override
            public void onConnectionFailure() {
                // Utils.showToast(proximityListener, getString(R.string.unexpected_error_connection));
            }
        });
```

**Comment by jakubkontakt** [comment]
What is phone model that you are using?

**Comment by subbu1234** [comment]
1) Nexus 5 and version - 6.0.1
2) Samsung mini S5  and version 4.4.2

**Comment by jakubkontakt** [comment]
Could you update to latest version 2.1.1? It seems like the bug we fixed recently.

**Comment by subbu1234** [comment]
We upgraded 2.1.1 and configured ScanContext like this

 scanContext = new ScanContext.Builder()
                            .setScanMode(ProximityManager.SCAN_MODE_LOW_LATENCY)
                            .setIBeaconScanContext(iBeaconScanContext)
                            .setActivityCheckConfiguration(new ActivityCheckConfiguration(TimeUnit.SECONDS.toMillis(180), TimeUnit.SECONDS.toMillis(100)))
                            .setForceScanConfiguration(new ForceScanConfiguration(TimeUnit.MILLISECONDS.toMillis(1000), TimeUnit.MILLISECONDS.toMillis(300)))
                            .setScanPeriod(ScanPeriod.RANGING)
                            .build();

But still sometimes we are facing this problem. DEVICE_LOST event firing even though device is in the range.
We tested with following devices.
1.  Samsung Galaxy S5 with Android 5.0
2.  HTC One M7 with Android 5.0.2
3.  Moto G 2nd Gen with Android 5.0.2
4.  One Plus One 

```
On certain phones like Moto G 2nd Gen and One Plus One, the beacon detection doesn’t work most of the times
```

**Comment by subbu1234** [comment]
We are waiting for your replay. Please provide solution.

**Comment by michaldrabik** [comment]
Closing. Feel free to reopen if necessary.
