### ISSUE TITLE
dalvikvm﹕ Could not find class 'android.bluetooth.le.ScanSettings$Builder', referenced from method com.kontakt.sdk.android.ble.service.ScanCompat.createScanConfiguration

### ISSUE THREAD

**Issue by milosgaric23** [kontaktio/kontakt-android-sdk#42]
Hi guys, me again :)

I have faced with this error, and two more others:
dalvikvm﹕ Could not find class 'android.bluetooth.le.ScanSettings$Builder', referenced from method com.kontakt.sdk.android.ble.service.ScanCompat.createScanConfiguration
dalvikvm﹕ Could not find class 'android.bluetooth.le.ScanSettings$Builder', referenced from method com.kontakt.sdk.android.ble.service.ScanCompat.createScanConfiguration

I don't know why, but I know that I was able to use library before, and now I am getting these 3 errors, and scanning couldn't be started. Problem is on http://www.gsmarena.com/lenovo_a8_50_a5500-6281.php device. I have tested it on Nexus 5, and Samsung Galaxy S6 Edge, and is working fine, I could even say fantastic.

Do you have any idea what could go wrong?

Thanks in advance.

**Comment by jakubkontakt** [comment]
Hi,

Could you tell what version of Android is installed on device? It seems that there is no 
https://developer.android.com/reference/android/bluetooth/le/ScanSettings.html available on phone.

**Comment by milosgaric23** [comment]
So, here are the concrete parameters of device:
Model: Lenovo Tablet A5500-F
Android Version: 4.4.2
Kernel version (just in case): 3.4.67

**Comment by milosgaric23** [comment]
Calling BluetoothUtils.isBluetoothLeSupported(this), I am getting true. And that is method from kontakt.io library, as I could see.

**Comment by cboisen** [comment]
How did you resolve it?

**Comment by michaldrabik** [comment]
This issue seems like a single-device specific (Lenovo A8-50). Are you having similair issues @hauthorn. If so, could you please describe your case?

**Comment by michaldrabik** [comment]
dalvikvm issue should no longer appear in 3.0.0 version. Feel free to reopen if necessary.
