### ISSUE TITLE
How to switch dynamically from monitoring to ranging and vice-versa

### ISSUE THREAD

**Issue by subbu1234** [kontaktio/kontakt-android-sdk#43]
Hi,
  In our application we need for background notifications when app is in the beacon region. From your documentation we found that in ranging passivePeriod should set to 0 and in monitoring passivePeriod should set to more than 2 seconds. So in monitoring Android device stays idle for ScanPeriod.passivePeriod. But we want immediate updates from the beacon when user moves within the range of beacon proximity. and also ranging don't work when app is in background.
So we want to run the app in ranging mode when app is in foreground and we want to switch into monitoring mode when app is in background mode. our question is 
Please provide the code to dynamically switching from monitoring to ranging and vice-versa?
Thanks and regards,
subbu

**Comment by jakubkontakt** [comment]
Only way to switch periods is to restart scan with other ScanContext
