### ISSUE TITLE
Can't connect to Beacon firmware version 3.1 Android

### ISSUE THREAD

**Issue by guilhermemamprin** [kontaktio/kontakt-android-sdk#44]
Hi,
I'm currently working with the SDK V1.0.6 on Android and was having no problem connecting and updating information on Kontakt Beacons. Recently I've aquired some new Beacons (also from Kontakt) and since then I've been unable to do it. 

After some Debugging I've observed that the new Beacons have firmware version 3.1 and the old ones V.2.6, which seems to be the case. Also, after monitoring, the new beacons (BeaconDevice) sometimes come without uniqueId, and even when they come with it, on trying to connect it raises an AuthenticationFailure and the failure code shown is FAILURE_UNKNOWN_BEACON.

I've also tested it with your app for Android (Kontakt.io Management App) and it seems that the new ones take much more time to connect and sometimes even fail to do it, whereas the old one seems to be working fine. 

I'm aware of the new version of the SDK but I'm using the old one due to compatibility. 

Do you know what could be happening?

Regards

**Comment by jakubkontakt** [comment]
Does the problem with unique id also happens on the latest version with SDK?

**Comment by guilhermemamprin** [comment]
I didn't test it, but as I previously stated it would be much easier for me to use to older version.

**Comment by jakubkontakt** [comment]
Closing as we do not provide support anymore for 1.0.x SDK tree.
