### ISSUE TITLE
How to Set a region to monitor ?

### ISSUE THREAD

**Issue by jitendra00777** [kontaktio/kontakt-android-sdk#45]
My use case scenario is i want to implement an attendance app for which i am using onRegionEntered() and onRegionAbandoned() functions.

I have already changed the UUID of my cloud beacons from web panel but still i am getting the old UUID for the region and major minor 0.

**Comment by jakubkontakt** [comment]
Could you tell me what is the value of "Last Connection" in "Device properties" tab of your Cloud Beacon on http://panel.kontakt.io website? 

As this is issue is not related to Android SDK but to Cloud Beacon please in case of any troubles ask support@kontakt.io
