### ISSUE TITLE
Eddystone beacon proximity and distance

### ISSUE THREAD

**Issue by MH-Python** [kontaktio/kontakt-android-sdk#46]
Greetings kontaktio team,
Great work but I have an issue that I am working with IBeacons and Eddystones trying to make monitoring on all of them the IBeacons values (proximity, distance) changing reasonably according to the distance between the mobile and the IBeacon (and I think the distance is measure by meters)
but for the Eddystones the proximity not changing and it is always takes value FAR but the distance changes when the Eddystones get far or near (and I think the distance in Eddystones is measured by centimeters)
I am using android SDK 2.0

**Comment by jakubkontakt** [comment]
Hi, 

Sorry for late response. We spotted a bug in our SDK that causes not updating Eddystone Proximity.

Very soon we will have release of SDK with fixed this issue

**Comment by jakubkontakt** [comment]
Please update your dependency to latest version 2.0.1

**Comment by jagadishcc** [comment]
I am using the latest version 2.0.1. 
If I place 5 Kontact.io Eddystone Devices in a same location ,  I am getting different RSSI and Distance value from getRssi() and getDistance() respectively. I am expecting least difference in RSSI and Distance values for all the 5 Devices I configures. Please advice

I need to implement Immediate,Near and Far for Eddystone devices. Is there any methods to implement without RSSI and Distance values? .

**Comment by jakubkontakt** [comment]
Are all the beacons have the same tx power?

**Comment by jagadishcc** [comment]
Yes. All beacons have the same tx power. 

TX Power:3
Interval:350 ms

**Comment by rafaljanicki** [comment]
Hello,

We've worked with Google on Eddystone format and the ranges was one of the
topic of discussion. However, Google decided to not support this as those
value are quite unstable.

Therefore, you can implement those, but you have to work your own way. But
please note that it may vary based on the Android device - they all have
different BT specifics and therefore may report different RSSI values for
the same environment.

On Thu, Nov 5, 2015 at 5:58 AM, jagadishcc notifications@github.com wrote:

> I am using the latest version 2.0.1.
> If I place 5 Kontact.io Eddystone Devices in a same location , I am
> getting different RSSI and Distance value from getRssi() and getDistance()
> respectively. I am expecting least difference in RSSI and Distance values
> for all the 5 Devices I configures. Please advice
> 
> I need to implement Immediate,Near and Far for Eddystone devices. Is there
> any methods to implement without RSSI and Distance values? .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kontaktio/Android-SDK/issues/46#issuecomment-153958256
> .

## 

Best regards,

[image: Rafal Janicki]
Rafal JanickiCTO

rafal@kontakt.io

www.kontakt.io

office: +48 123 793 445
[image: Kontakt.io] http://kontakt.io/[image: Facebook]
https://www.facebook.com/kontakt.io [image: Twitter]
https://twitter.com/kontakt_io [image: LinkedIn]
https://www.linkedin.com/company/kontakt-io [image: Google+]
https://plus.google.com/106304420610581266611/about

**Comment by marioosh-net** [comment]
I'm using a latest sdk 3.0.0 and i see that Eddystone beacon report wrong distance. I have iBeacon and Eddystone beacons scanned in the same time. For example i have two of them in distance about 20 cm, but i get distances like below. For iBeacon is ok, but Eddystone report huge distance.

06-13 21:46:08.037 D/beacons: IBeacon updated: dist: 0.09736236134931163, battery: 73, profile: IBEACON, rssi: -61.0, txPower: -77, proximity: IMMEDIATE
06-13 21:46:11.225 D/beacons: Eddystone updated:dist: **52.56914334186881**, battery: 36, profile: EDDYSTONE, rssi: -61.0, txPower: -36, proximity: FAR

Can i calculate distance for Eddystone beacon in some way using txPower and RSSI ?

**Comment by michaldrabik** [comment]
@marioosh-net Are you calculating with your own method (using txpower and RSSI)? Be aware that Eddystone standard returns RSSI@0m instead of 1m so we need to add 41dBM (1m) (http://i.imgur.com/DU6Ni5p.png)

**Comment by marioosh-net** [comment]
I don't want to calculate, but i see that i have to because sdk show wrong distance for Eddystone. For now i have modified standard method (-41db) and did this like below.

```
public static double calculateDistance(int txPower, double rssi, boolean eddy) {
    if (rssi == 0) {
        return -1.0; // if we cannot determine distance, return -1.
    }

    double ratio = rssi*1.0/(eddy?txPower-41:txPower);
    if (ratio < 1.0) {
        return Math.pow(ratio,10);
    }
    else {
        double accuracy =  (0.89976)*Math.pow(ratio,7.7095) + 0.111;
        return accuracy;
    }
}
```

For iBeacon profile works the same as Kontakt.IO SDK. For Eddystone... i don't know is OK, but looks better than mentioned 52.569 meters

**Comment by michaldrabik** [comment]
@marioosh-net You are right I've noticed that we use same algorithm in our SDK both for iBeacon and Eddystone distance calculation. You should indeed substract 41 as you did in your snippet. There is a discussion here (http://stackoverflow.com/questions/20416218/understanding-ibeacon-distancing), if you haven't seen it yet.

Also be aware that radio-signal-based distance measuring is pretty inaccurate and you need to be aware of that when you design your system. Given distance values are only approximates.

Regards

**Comment by Jul4a** [comment]
Hello, 

Im developing Android app using beacons. Can you help me, what type of beacon should I buy If I want to measure the distance between app user and beacon?

I need a beacon that know to send multiple packets at a time. And know to measure the real distance. 

 

Thank you.
