### ISSUE TITLE
Android SDK 2.0.0 - proguard configuration 

### ISSUE THREAD

**Issue by GaelCougnaud** [kontaktio/kontakt-android-sdk#47]
Hi,

I have integrated your SDK in version 2.0.0. That's work fine on debug mode, but I can not compile in release one, with proguard minified. 
I have tried add some keep and dontwarn options for your SDK, but I did not found the true configuration. 
Could you help me to proguard your library ?

Thanks,
Gaël

**Comment by jakubkontakt** [comment]
Please use check this configuration:

```
-keep class com.squareup.okhttp.** { *; }
-keep interface com.squareup.okhttp.** { *; }
-dontwarn com.squareup.okhttp.**
-dontwarn okio.**

-keep class com.kontakt.sdk.** { *; }
-keep interface com.kontakt.sdk.** { *; }
```

**Comment by GaelCougnaud** [comment]
Thanks. That's working.

In my previous test, my configuration was near this solution. 
I forgot to keep the interface (-keep interface com.kontakt.sdk.*\* { *; })

Gaël
