### ISSUE TITLE
Callback events not being fired consistently

### ISSUE THREAD

**Issue by 55dante41** [kontaktio/kontakt-android-sdk#49]
We are working on making an app that corresponds with your beacons (to do some stuff), but our app depends heavily on the beacon. What we observed is that sometimes the events are fired and everything works well, sometimes the events are not raised at all (I see the beacons in the bluetooth devices in settings screen though). I'm using Android 4.4.4. Are there any known causes and/or workarounds for this?

**Comment by jakubkontakt** [comment]
Have you tried set ForceScanConfiguration to your ScanContext?

**Comment by jakubkontakt** [comment]
Hi @devmaestro, what is the status of issue?

**Comment by 55dante41** [comment]
Hey @jakubkontakt sorry missed this thread (did not get the email notif for the previous one). Will use "setForceScanConfiguration(ForceScanConfiguration.DEFAULT)" and revert back to you on the status.
