### ISSUE TITLE
Android integration

### ISSUE THREAD

**Issue by bitseeker1** [kontaktio/kontakt-android-sdk#50]
Hello,

We have received the beacons and our Android engineers are trying to integrate the beacons with our android app.

Our engineers have used the steps on http://docs.kontakt.io/android-sdk/2.0.0/quickstart/

But they have encountered the following integration errors. Can you please assist us by forwarding to relevant team.

:app:validateDebugSigning
:app:packageDebug
Error: duplicate files during packaging of APK D:\AndroidStudio\DiscoveryBLE\app\build\outputs\apk\app-debug-unaligned.apk
    Path in archive: main/AndroidManifest.xml

```
Origin 1: D:\AndroidStudio\DiscoveryBLE\app\build\intermediates\exploded-aar\com.kontakt.sdk.android\kontakt.io-ble-sdk\2.0.0\classes.jar

Origin 2: D:\AndroidStudio\DiscoveryBLE\app\build\intermediates\exploded-aar\com.kontakt.sdk.android\kontakt.io-android-sdk\2.0.0\classes.jar
```

 FAILED

Regards,
J

**Comment by jakubkontakt** [comment]
Please put following lines in your build.gradle inside android tree

```
    packagingOptions {
        exclude 'main/AndroidManifest.xml'
    }
```

So whole file may look like:

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.0"

    defaultConfig {
        applicationId "com.your.package"
        minSdkVersion 18
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude 'main/AndroidManifest.xml'
    }

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.kontakt.sdk.android:kontakt.io-android-sdk:2.0.0'
}
```

**Comment by jakubkontakt** [comment]
Did it solved your build problem?

**Comment by pendragonformsrepo** [comment]
I have the same problem and that solution does not work for me :(

**Comment by jakubkontakt** [comment]
What error messages are you receiving?

Could you post your **build.gradle** and **AndroidManifest.xml** configuration?
