### ISSUE TITLE
SpaceAbandoned event

### ISSUE THREAD

**Issue by logo17** [kontaktio/kontakt-android-sdk#51]
Hi, I have a problem.

I'm using the kontakt android 2.0 library, I'm having some problems with the SpaceAbandonedEvent.

I have an scan context subscribed to these events:

.setEventTypes(EnumSet.of(EventType.DEVICES_UPDATE, EventType.SPACE_ABANDONED, EventType.SPACE_ENTERED))

It is working fine with DevicesUpdate event, but I'm having problem with SpaceAbandoned event. It is never launched.

For testing the space abandoned event, I'm using a beacon and I remove its battery to test it this event is launched, but when I remove the battery nothing happened and this event is never launched.

**Comment by jakubkontakt** [comment]
Hi,

Could you provide me a part of code where you are setting IBeaconRegion to IBeaconScanContext?

Described behaviour may happen if you did not set your custom Regions. Then SDK is using default Region EVERYWHERE. In such situation event SPACE_ABANDONED will be called only if you are not in range of any beacon. 

To monitor for each beacon separately you should set specific regions for devices.

By the way, update your dependencies to latest version 2.0.1

**Comment by jakubkontakt** [comment]
Hi, what is the status of issue?

**Comment by jakubkontakt** [comment]
@logo17 
What is the status of your issue? Is it fixed after upgrading to 2.0.1?

**Comment by logo17** [comment]
Sorry, by the way. It was fixed in the upgrade, Thank you.
