### ISSUE TITLE
Eddystone URL wrong tld extension

### ISSUE THREAD

**Issue by antonino-tocco** [kontaktio/kontakt-android-sdk#53]
Hi, I'm developing an Android App based on kontakt-beacon-admin-sample-app. In monitor I get url form EddystoneDevice Object, but URL have a wrong tld extension.
Thanks in advance for the support

**Comment by jakubkontakt** [comment]
Could you post what is your desired TLD? And what actually you are receiving from SDK?

**Comment by antonino-tocco** [comment]
My desired TLD is .com because the EddystoneDevice URL is http://www.entonytocco.com, but I receiving http://www.entonytocco.gov from SDK.

**Comment by jakubkontakt** [comment]
We spotted that bug as well and we are going to release new version of SDK soon with bugfix. As workaround for now you can set your TLD as ".com/" and it should work well.

**Comment by antonino-tocco** [comment]
But if I have different TLD, I can’t set manually for all extension

Antonino Tocco
Dottore in Informatica
Via dei Normanni,76
90048,San Giuseppe Jato ( PA )
Mobile: 3807829491
Web: http://www.entonytocco.com
P.IVA 06442900822

**Comment by antonino-tocco** [comment]
There are news about this issue?

**Comment by jakubkontakt** [comment]
This issue is going to be fixed with new release of SDK which should be very soon.
