### ISSUE TITLE
Beacon cache

### ISSUE THREAD

**Issue by spooke9** [kontaktio/kontakt-android-sdk#55]
Hi,
I'm developing an android app that uses last SDK (2.0.0). I'm able to scan and detect perfectly, the only thing is that, after an hour or more that the app scan the beacon, it continues to detect also beacons not in range. There is a method for clear the cache of beacons scanned?

Thanks

**Comment by jakubkontakt** [comment]
Have you tested that on version 2.0.1? We fixed in 2.0.1 some bugs related to caching beacons and event firing, so please update and give us a feedback about that.

**Comment by spooke9** [comment]
Hi,
I tried the version 2.0.1 of SDK and it seems to have solved the problem with the cache!
Thank you
