### ISSUE TITLE
Android native API - connecting to Kontakt.io beacons fails

### ISSUE THREAD

**Issue by dsomekh** [kontaktio/kontakt-android-sdk#56]
Hello Support,

Below is the code I am using to connect to Kontakt.io beacon. The connection is successful but after about 1 min it is disconnected. (onConnectionStateChange is called with STATE_DISCONNECTED)

Can you tell me what might be the issue?

Tested with:

Nexus 5 - Lollipop, Marshmallow
HTC ONE M8 - Lollipop

public void Scan()
    {

```
    ScanSettings.Builder scanSettingsBuilder = new ScanSettings.Builder();
    if(scanSettingsBuilder != null) {
        scanSettingsBuilder.setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY);
        mScanSettings = scanSettingsBuilder.build();
    }

    if(mScanHandler != null)
        mScanHandler.post(scanRunnable);


}

private Runnable scanRunnable = new Runnable() {
    @Override
    public void run() {
        mScanner = BluetoothAdapter.getDefaultAdapter().getBluetoothLeScanner();
        if(mScanner != null)
            mScanner.startScan(scanFilters, mScanSettings, scanCallback);

    }
};

private ScanCallback scanCallback = new ScanCallback() {
    @Override
    public void onScanResult(int callbackType, ScanResult result) {
        super.onScanResult(callbackType, result);

        BluetoothDevice device = null;

        if(result != null) {
            int rssi = result.getRssi();
            device = result.getDevice();
        }

    If(device != null)
           mBluetoothGatt = device.connectGatt(app, false, mGattCallback);
```

};

private final BluetoothGattCallback mGattCallback =
            new BluetoothGattCallback() {
                @Override
                public void onConnectionStateChange(BluetoothGatt gatt, int status,int newState) {
                   if(mDisabled)
                        return;
                   if (newState == BluetoothProfile.STATE_CONNECTED) {
                       if (gatt != null && gatt.getDevice().getAddress().equals(GetID())) {
                           OnDeviceFound();
                       }
                   }
                    else if (newState == BluetoothProfile.STATE_DISCONNECTED) {
                        if(gatt != null && gatt.getDevice().getAddress().equals(GetID())) {

```
                        gatt.disconnect();
                        gatt.close();
                        OnDeviceNotFound();
                    }

                }
            }};
```

**Comment by jakubkontakt** [comment]
What I see in your snippet that you are not writing password to beacon.

You are supposed to know password of your device and write it to characteristic: "a1ea8131-0e1b-d4a1-b840-63f88c8da1ea" in service "a1ea8130-0e1b-d4a1-b840-63f88c8da1ea" after `onServicesDiscovered` is called.

We created Connection class that handles that work for you. Check this http://kontaktio.github.io/Android-SDK/2.0.0/Javadoc/com/kontakt/sdk/android/ble/connection/ibeacon/IBeaconConnection.html

**Comment by dsomekh** [comment]
Hi,

Can you give me an example code that shows how to write the password?

Also, I see from your docs that after 6 mins I am disconnected from the device.

If I want to keep the connection, I need to re-connect every 6 mins?

@Override
    // New services discovered
    public void onServicesDiscovered(BluetoothGatt gatt, int status) {
        if (status == BluetoothGatt.GATT_SUCCESS) {
            gatt.writeCharacteristic();
           // broadcastUpdate(ACTION_GATT_SERVICES_DISCOVERED);
        } else {
         //   Log.w(TAG, "onServicesDiscovered received: " + status);
        }
    }

Thanks,
David

**Comment by jakubkontakt** [comment]
First of all you should not keep connection between device and beacon as it decreases lifetime of beacon battery.

My next recommendation about connection is to use our BeaconConnection, because there is a lot of edge cases and Android native API has a lot of issues to get it working.

If you want to to write charactestics on your own please study:
- http://developer.android.com/reference/android/bluetooth/BluetoothGatt.html
- http://developer.android.com/reference/android/bluetooth/BluetoothGattCharacteristic.html
- http://developer.android.com/reference/android/bluetooth/BluetoothGattServerCallback.html

**Comment by dsomekh** [comment]
Hi,

See below my code for setting the password, but I am still getting disconnected.

What am I doing wrong?

```
 @Override
    // New services discovered
    public void onServicesDiscovered(BluetoothGatt gatt, int status) {
        if (status == BluetoothGatt.GATT_SUCCESS) {
            UUID serviceUUID = UUID.fromString("a1ea8130-0e1b-d4a1-b840-63f88c8da1ea");
           BluetoothGattCharacteristic characteristic = new BluetoothGattCharacteristic(serviceUUID,BluetoothGattCharacteristic.PERMISSION_WRITE | BluetoothGattCharacteristic.PERMISSION_WRITE_SIGNED  | BluetoothGattCharacteristic.PERMISSION_WRITE_ENCRYPTED_MITM,BluetoothGattCharacteristic.PROPERTY_WRITE | BluetoothGattCharacteristic.PROPERTY_SIGNED_WRITE | BluetoothGattCharacteristic.PROPERTY_WRITE_NO_RESPONSE);
            characteristic.setValue("6wRO");
            gatt.writeCharacteristic(characteristic);

        } else {
            Log.w(TAG, "onServicesDiscovered received: " + status);
        }
    }
```

**Comment by jakubkontakt** [comment]
You should get needed service from `gatt.getServices()` and look for password characteristic in `service.getCharacteristics()`. After that you can set password for founded characteristic

**Comment by jakubkontakt** [comment]
Closing as this is not related itself to SDK but to Android BluetoothGatt.
