### ISSUE TITLE
Could not find method com.kontakt.sdk.android.common.KontaktSDK.initialize, referenced from method walkrecognizer.com.acc.MainActivity.onCreate

### ISSUE THREAD

**Issue by palettodiferro** [kontaktio/kontakt-android-sdk#57]
I don't have The Api key yet, but i'm trying to test your Android SDK. At started I tried to put your jar files into "libs" folder of my Android project but it gave me the error "Error generating final archive: duplicate entry: AndroidManifest.xml" (because in your jar file exists another AndroidManiest). So I tried to add your jar (version 2.0.0) as external jar putting them in another folder, external to the project, and now it's working. But when I add the following part of code, 

 KontaktSDK.initialize(this)
               .setDebugLoggingEnabled(BuildConfig.DEBUG)
               .setLogLevelEnabled(LogLevel.DEBUG, true)
               .setCrashlyticsLoggingEnabled(true);

 on "onCreate()" method of my main activity and run the project I get the the error "Could not find method com.kontakt.sdk.android.common.KontaktSDK.initialize, referenced from method walkrecognizer.com.acc.MainActivity.onCreate" and my app crashes.

Can you help me please? Why it gave me this error?   I'm using Eclipse.

**Comment by jakubkontakt** [comment]
Hi @palettodiferro we are aware that our current jars are not built right, but we focus more on Gradle dependencies as it is current official Android Build System. 

In the next release all jars will be replaced with single one and `AndroidManifest.xml` file will not be included into jar. 

There is also one more required jar which by mistake was not listed in guideline. Kontakt SDK uses internally [OkHttp](http://square.github.io/okhttp/), so please add as well okhttp jar to your buildpath and test it again.

If it does not work, please give more details about your build configuration so we can reproduce this issue.
