### ISSUE TITLE
How to define region with only (UUID plus Major value)

### ISSUE THREAD

**Issue by grzegorzgolec** [kontaktio/kontakt-android-sdk#58]
According to your blog post (http://kontakt.io/blog/beacon-id-strategy-guide-quick-deployment/) especialy this sentence:

"A region can be defined by proximity UUID only, a UUID plus Major value, a UUID plus Major and Minor values. You can select the level of granularity you need."

I have tried below code with no success 

<code>
new BeaconRegion(UUID.fromString("f7826da6-4fa2-4e98-8024-bc5b71e0893e") , 4545, 0 )
</code>

How to do this ?

**Comment by jakubkontakt** [comment]
In latest version 2.0.1 

BeaconRegion will be checked with exact values so in your snippet beacons must fulfil following conditions:
- UUID = f7826da6-4fa2-4e98-8024-bc5b71e0893e
- Major(M) = 4545
- Minor(m) = 0

Your case can be done via combining BeaconRegion and IBeaconFilter.

You should set your IBeaconRegion to EVERYWHERE and set custom IBeaconFilter as follow:

```
final UUID proximity = UUID.fromString("f7826da6-4fa2-4e98-8024-bc5b71e0893e");
final int major = 4545;

//create filter
IBeaconFilter beaconFilter = new IBeaconFilter() {
        @Override
        public boolean apply(IBeaconAdvertisingPacket iBeaconAdvertisingPacket) {
             return iBeaconAdvertisingPacket.getProximityUUID().equals(proximity) && iBeaconAdvertisingPacket.getMajor() == major;
          }
};

//create scan context
//Region EVERYWHERE is default value if no regions set
IBeaconScanContext beaconScanContext = new IBeaconScanContext.Builder()
            .setIBeaconFilters(Arrays.asList(beaconFilter))
            .build();
```

In the next release we changed API of IBeaconRegion a little bit. You will be able to choose granularity of regions to only PROXIMITY with MAJOR, with MINOR or any combination of them. Only one value will be required - PROXIMITY, rest of them will be optional and by by default will not be checked

**Comment by jakubkontakt** [comment]
Hi @grzegorzgolec 
Please check our latest release 2.1.1, we introduced possibility to set region only on UUID and as well for combination of UUID + Major/minor
