### ISSUE TITLE
Beacons - Connection not correctly closed

### ISSUE THREAD

**Issue by StephanGs** [kontaktio/kontakt-android-sdk#59]
Hello,

I have a question concerning programming kontakt.io beacons in Android using Android SDK (SDK 23) – NOT the kontakt.io Android SDK.

I wrote a test program in Android that
- Connects to a beacon via GATT interface
- Reads the provided services and characteristics
- Reads the characteristics values
- Closes the connection to the beacon device

All works fine, but it seems that the connection is not closed correctly on the beacon side.
Do you have any idea what I am doing wrong? Can you help me?

I am programming under Android SDK 23 (M), using the Android Gatt classes (BluetoothGatt, BluetoothGattService, BluetoothGattCharacteristic,…). I am not able to use the kontakt.io SDK, because the code must stay generic.
I would be very pleased if you could help me anyway.

Details:
In the test app I use the Android Bluetooth LE Gatt classes (BluetoothGatt, BluetoothGattService, …), which are part of the Android SDK. Opening the connection and reading the services, characteristics, and values works fine. Also the callback “onConnectionStateChange” returns no error code, after calling BluetoothGatt.disconnect(). But if I try to start the test program again, the beacon refuses the connection with the error code 0x85. After a period of some minutes the device can be connected successfully again. I also tested the app “nRF Master Control Panel” by Nordic. And it seems that it has the same problems as my test program. With the kontakt.io app everything seems to work – but not shortly after my test app was closed :).

Additional Infos: 
I also tested the app “nRF Master Control Panel” by Nordic with kontakt.io beacons. And it seems that it has the same problems as my test program.
The test program works correctly using another Bluetooth LE device.

**Comment by jakubkontakt** [comment]
0x85 is undocumented android GATT_ERROR - 133.

This error may has many sources, but according to your flow it seems that your are not calling method `close()` but only `disconnect()`. You should always call method `close()` after you are done with beacons.

Not calling `close()` may result in blocking beacon for few minutes, because beacon itself will disconnect from any remote device after few minutes in connected state. 

After long period of being in connected state beacon will disconnect and go to NOTCONNECTABLE mode. I such scenario you would not be able to connect to beacon again for a while.

More details can  also be found on [stackoverflow thread](http://stackoverflow.com/questions/25330938/android-bluetoothgatt-status-133-register-callback)

**Comment by StephanGs** [comment]
Thank you for the quick answer.
I replaced “disconnect” by “close” (before the change I called “disconnect” and then, after receiving the “onConnectionStateChange” callback, “close”).
But the result is the same. The beacon is still not connectable for some minutes.

If the connection succeeds, the connected state will not last longer than a few ( < 10 ) seconds. I don’t think that should be too long.

Do you have any other ideas?

**Comment by jakubkontakt** [comment]
Have you authorized with password to beacon? You need to write password of beacon to characteristic and after that you will be able to continue your work with beacon.

Have you read this thread? https://github.com/kontaktio/Android-SDK/issues/56

If no, please do. But this is more complicated work to do with connecting to beacon, so I am not going to explain whole process of it. 

My advise is to use our connection in SDK, which handles all the job.

**Comment by StephanGs** [comment]
Hi,

thank you again. I will try it. 
But one more (maybe stupid) question: 
What is or where do I find a beacon’s password?
Is this the 4-digit alphanumeric ID (e.g. Gk7h) that is printed on the beacon’s label?

**Comment by jakubkontakt** [comment]
You can find it in on your account. Check panel.kontakt.io website.

The ID you are talking about is beacon unique id, not password.

**Comment by jakubkontakt** [comment]
Closing this issue due it is not related to kontakt.io SDK but Android SDK itself
