### ISSUE TITLE
What is wrong with Nexus devices ???

### ISSUE THREAD

**Issue by grzegorzgolec** [kontaktio/kontakt-android-sdk#62]
Nexus 5 with Android 6.0 no scanning activity. To be sure ive also installed your admin app from Google Play. I have 5 beacons on my desk, when I launched admin app and choose "nearby" tab there is no devices neraby! Ive tried this few times always withe the same result.  

Nexus 7 (2013) same as Nexus 5, but also i cant install admin app from Google Play what is wrong with this device ?

**Comment by jakubkontakt** [comment]
Hi,

Do you see on "All" tabs devices that are assigned to your account?

If so, have you tested scanning beacons with other applications?

**Comment by grzegorzgolec** [comment]
I have also Galaxy S4 and everything is working perfectly. Problem is with Nexus devices.

I have 150 beacons and I see them all i "All" tab.

**Comment by jakubkontakt** [comment]
This seems like a Bluetooth chipset problem. 

We have tested scanning beacons as well on Nexus 5 (Marshmallow), Nexus 7(Marshmallow) and Nexus 6(Lollipop) devices. 

From the above devices only Nexus 7 seemed to has problems with efficient Bluetooth scan, but eventually it scans beacons.  Other devices scanned all beacons very well.

Please test on Nexus other beacons scanner. If they do not see beacons, please try restart Bluetooth adapter or even whole phone.

**Comment by jakubkontakt** [comment]
Hi, What is the status of issue? Is it related to SDK or phone?

**Comment by grzegorzgolec** [comment]
I have tried to scan beacons with Locate Beacon (Radius Networks) with no luck. 
Nexus 5 could not find any beacons, i assume there is something on hardware level, on Nexus 7 there is extra info that device has no BLE module. 

Thanks for help.

**Comment by jakubkontakt** [comment]
Thanks, I am closing issue.

**Comment by LipanGhosh** [comment]
I am facing the same problem.I have nexus 7 along with samsung tab and a micromax tab.Nexus 7 is not able to scan the beacons properly.
