### ISSUE TITLE
Get real instanceId beacon

### ISSUE THREAD

**Issue by palettodiferro** [kontaktio/kontakt-android-sdk#64]
I'm testing Proximity Manager example code described on Kontakt.io Android Api Documentation http://developer.kontakt.io/android-sdk/2.0.0/quickstart/#using-the-sdk-proximity-manager-example.
I need to get the real instaceId of beacons to configure a generic beacon as starting beacon and another generic beacon as stopping beacon and add both as eddystone filters. 

How can I get the real instanceId?

**Comment by jakubkontakt** [comment]
@palettodiferro 
What do you mean by <b>real instanceId</b>? 

All values received from in `onEvent()` method are real one.

Could you post more details what do you mean by <b>real instanceId</b>?

**Comment by palettodiferro** [comment]
For istance, from Kontakt.io official Android app I can see that the instance id of one beacon is "xxxxxxx" and if I put this on my code as eddystone filter, it works correctly. However, when I print value of instance Id of the same beacon on onEvent() method I get another value (different than I can see from official app).

case EDDYSTONE:
                   final EddystoneDeviceEvent eddystoneDeviceEvent = (EddystoneDeviceEvent) event;
                   getActivity().runOnUiThread(new Runnable() {
                       @Override
                       public void run() {
                           IEddystoneNamespace namespace = eddystoneDeviceEvent.getNamespace();
                           List<IEddystoneDevice> deviceList = eddystoneDeviceEvent.getDeviceList();

 // Here I get different namespace and different devices instanceId than showed on official app for each beacon
                           Log.i("HERE", "NameSpace: " + namespace);
                           Log.i("HERE", "Array: " + Arrays.toString(deviceList.toArray()));
                       }
                   });
                   break;

MayBe I'm not using correct methods to get namespace and instanceId?

**Comment by jakubkontakt** [comment]
Basically you are printing an object as it is. Both of the methods

```
Log.i("Here", "NameSpace: " + namespace);
Log.i("HERE", "Array: " + Arrays.toString(deviceList.toArray()));
```

are using `toString()` method on object. 

Default implementation of that method is `getClass().getName() + '@' + Integer.toHexString(hashCode())`

This is kinda basic stuff about Java.

If you want to get instanceId of beacon use corresponding method for that on <b>EddystoneDevice</b> `getInstanceId()` on single item, not on a list of items
