### ISSUE TITLE
Loop "Device discovered", "device lost"

### ISSUE THREAD

**Issue by palettodiferro** [kontaktio/kontakt-android-sdk#65]
I'm testing Proximity Manager example code described on Kontakt.io Android Api Documentation http://developer.kontakt.io/android-sdk/2.0.0/quickstart/#using-the-sdk-proximity-manager-example. 

I'm realizing that printing eventType on onEvent() method, for Eddystone device, the same beacon is discovered and after a few seconds it's lost and then again discovered and so on. I put as Active scan Period 5 seconds and Passive scan period 0. 
Is that a normal behavior or not?

**Comment by jakubkontakt** [comment]
Hi @palettodiferro 

Please update gradle dependency to latest version 2.0.1 and check again. 

Described behaviour is not normal and should not be appearing.
