### ISSUE TITLE
Not getting distance update accurate

### ISSUE THREAD

**Issue by vishundayal** [kontaktio/kontakt-android-sdk#66]
Hi,
I am trying to get beacons within a radius of 20m. After I start ranging beacons, I am getting continuously the **same accuracy** even if I moved the beacons away, in-fact out of our range. 

Like if once it got beacons at 1m accuracy then it keeps calling `onBeaconsUpdated` with 1m accuracy and does not change even if I move it far or near.

This is how I am trying to get beacon ranging.

```
beaconManager = BeaconManager.newInstance(this);
beaconManager.setMonitorPeriod(MonitorPeriod.MINIMAL);
beaconManager.setForceScanConfiguration(ForceScanConfiguration.DEFAULT);
beaconManager.registerMonitoringListener(this);
connect();

private void connect() {
    try {
        beaconManager.connect(new OnServiceBoundListener() {
            @Override
            public void onServiceBound() {
                try {
                    HashSet regions = new HashSet();
                    regions.add(Region.EVERYWHERE);
                    beaconManager.startMonitoring(regions);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
        });
    } catch (RemoteException e) {
        throw new IllegalStateException(e);
    }
}

public void onBeaconsUpdated(Region region, List<BeaconDevice> beacons) {
if (beacons != null) {
        mListbeacons = getBeaconDetail(beacons);
        showAlertForAdvertizement();
}
}
```

**I have also attached the source code java file.

Thanks,
Vishun
[BeaconServices.txt](https://github.com/kontaktio/Android-SDK/files/55589/BeaconServices.txt)

**Comment by jakubkontakt** [comment]
It seems that you are using older version 1.0.6 or even previous. Current supported version of SDK is 2.0.1. 

Please update your dependencies and follow guide on http://developer.kontakt.io/android-sdk/2.0.0/quickstart/ for updating from older version
