### ISSUE TITLE
Using 2.0.1 JAR files and still getting DEVICE_DISCOVERED and DEVICE_LOST bug

### ISSUE THREAD

**Issue by bradleywildman** [kontaktio/kontakt-android-sdk#67]
Hi,

Upon reading that there was a bug fix for the DEVICE_DISCOVERED/DEVICE_LOST issue in 2.0.1 i have migrated the correct jar files into my project, when i run my application it works however the bugfix doesn't appear to have worked, when looking at my logcat i am getting these logs:

12-08 14:11:31.539 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: onCreate
12-08 14:11:31.565 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: onResume
12-08 14:11:31.698 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: onServiceReady
12-08 14:11:31.988 4852-4923/com.example.bradleywwildman.practiseapp D/iBeacon: case : onScanStart
12-08 14:13:59.690 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:13:59.690 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_DISCOVERED
12-08 14:13:59.816 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:13:59.816 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_DISCOVERED
12-08 14:14:01.819 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:14:01.819 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_DISCOVERED
12-08 14:14:11.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:14:11.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_LOST
12-08 14:14:11.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:14:11.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_LOST
12-08 14:14:51.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:14:51.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_LOST
12-08 14:14:57.747 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:14:57.747 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_DISCOVERED
12-08 14:15:16.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:15:16.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_LOST
12-08 14:15:57.038 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:15:57.038 4852-4852/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_DISCOVERED
12-08 14:16:36.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: case : IBEACON
12-08 14:16:36.998 4852-4937/com.example.bradleywwildman.practiseapp D/iBeacon: DEVICE_LOST

These are the same logs i was getting from using to 2.0.0 JAR files.

Any assistance would be appreciated. thanks :)

**Comment by jakubkontakt** [comment]
Hi @bradleywildman Could you provide more details about your code? What is your method onEvent and your ScanContext Configuration?

With that information I will be able to check what is going on.

And as well please provide more details what is the model of device that you are running your code.

**Comment by bradleywildman** [comment]
The device i am running my code on is nexus 5

My onEvent method is : 

@Override
    public void onEvent(BluetoothDeviceEvent event) {

```
    final long startTime = System.nanoTime();

    switch (event.getDeviceProfile()) {

        case IBEACON:
            Log.d("iBeacon", "case : IBEACON");

            final IBeaconDeviceEvent iBeaconDeviceEvent = (IBeaconDeviceEvent) event;

            switch (iBeaconDeviceEvent.getEventType()) {
                case DEVICE_DISCOVERED:
                    Log.d("iBeacon", "DEVICE_DISCOVERED");
                    Toast.makeText(getApplicationContext(), "Entered Geo-fence.",
                            Toast.LENGTH_SHORT).show();
                    break;

                case DEVICE_LOST:
                    Log.d("iBeacon", "DEVICE_LOST");
                    Toast.makeText(getApplicationContext(), "Left Geo-fence.",
                            Toast.LENGTH_SHORT).show();
                    break;

                default:
                    runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            IBeaconRegion region = iBeaconDeviceEvent.getRegion();
                            List<IBeaconDevice> deviceList = iBeaconDeviceEvent.getDeviceList();
                            Log.d("iBeacon", "run");

                        }
                    });
            }
```

iBeacon ScanContext : 
                  IBeaconScanContext iBeaconScanContext = new IBeaconScanContext.Builder()
                .setEventTypes(EnumSet.of(EventType.DEVICE_DISCOVERED,
                        EventType.DEVICE_LOST))
                .setRssiCalculator(RssiCalculators.newLimitedMeanRssiCalculator(5))
                .setIBeaconFilters(Arrays.asList(
                        new IBeaconFilter() {
                            @Override
                            public boolean apply(IBeaconAdvertisingPacket iBeaconAdvertisingPacket) {
                                return iBeaconAdvertisingPacket.getProximity() == Proximity.NEAR;
                            }
                        },
                        IBeaconFilters.newMajorFilter(34)
                ))
                .build();

**Comment by jakubkontakt** [comment]
Thanks for code, I am going to look int and investigate issue

**Comment by jakubkontakt** [comment]
@bradleywildman 
I run your code and it is working as it supposed to work.

SDK has following proximities:
- IMMEDIATE
- NEAR
- FAR

You can think of them like of sets. But the most important thing that this sets are disjointed. It is done on purpose for determining exact PROXIMITY of beacon.

So the flow may look like:

discover FAR -> discover NEAR / lost FAR -> discover IMMEDIATE / lost NEAR

In some circumstances signal from Beacon may be fluctuated by external factors like walls etc. This leads to changing rssi received by Android phone and in the end calculated PROXIMITY could be different that is in reality. 

I hope that explanation is sufficient for your, but if you have any more question please do.

**Comment by bradleywildman** [comment]
all of these logs in my logcat listed in my first post are being logged without me even moving the beacons/ device is it meant to do this?

**Comment by jakubkontakt** [comment]
Yes, that may happen because of signal changes which may be noised with some other factors. 

You can make your filter more smarter by extending PROXIMITY filter to following:

```
 new IBeaconFilter() {
    @Override
    public boolean apply(IBeaconAdvertisingPacket iBeaconAdvertisingPacket) {
         return iBeaconAdvertisingPacket.getProximity() == Proximity.NEAR || iBeaconAdvertisingPacket.getProximity() == Proximity.IMMEDIATE;
    }
}
```
