### ISSUE TITLE
Eddystone Device getProximity() return always FAR

### ISSUE THREAD

**Issue by palettodiferro** [kontaktio/kontakt-android-sdk#69]
I set beacon transmission power of my beacons to 1. On device discovered event, calling getProximity() method, I get always "FAR", also putting my device near to beacons. 
Why does it happen? Why do i never get Proximity.NEAR or Provimity.IMMEDIATE?

**Comment by palettodiferro** [comment]
MoreOver, what is distance measure of com.kontakt.sdk.android.common.profile.RemoteBluetoothDevice.getDistance() method? I read somewhere it was "m" but it has no sense because give me too big distances. 
I guess distance measure is in "cm", is it correct?

**Comment by andreribeiropinto104** [comment]
Hello, Have you already tried to set power tx to 3? 

The distance metric depends on the beacon profile. In Ibeacon is "m", in eddystone is "cm".
