### ISSUE TITLE
App crash if Bluetooth is off (some devices)

### ISSUE THREAD

**Issue by datasmurfen** [kontaktio/kontakt-android-sdk#7]
Hello the app crash on some devices if the BlueTooth is turned off on start/install.  (But not on  all of test devices.) It runs fine on Samsung S5 but crash on HTC One. SDK 1.0.6

```
    final BeaconManager beaconManager = BeaconManager.newInstance(this);
    beaconManager.setMonitorPeriod(new MonitorPeriod(TimeUnit.SECONDS.toMillis(50L), TimeUnit.SECONDS.toMillis(50L)));
            beaconManager.setForceScanConfiguration(ForceScanConfiguration.DEFAULT);
    beaconManager.registerMonitoringListener(new BeaconManager.MonitoringListener() {

        @Override
        public void onMonitorStart() {

            System.out.println("onMonitorStart");
        }

        @Override
        public void onMonitorStop() {

            System.out.println("onMonitorStop");
        }

        @Override
        public void onBeaconsUpdated(Region region, List<BeaconDevice> beaconDevices) {
            System.out.println("onBeaconsUpdated");

            for (int i = 0; i < beaconDevices.size(); i++) {
                System.out.println(beaconDevices.get(i).getProximityUUID());
            }

        }

        @Override
        public void onBeaconAppeared(Region region, BeaconDevice beaconDevice) {
            System.out.println("onBeaconAppeared");
        }


        @Override
        public void onRegionEntered(final Region region) {
            System.out.println("onRegionEntered");
        }

        @Override
        public void onRegionAbandoned(final Region region) {
            System.out.println("onRegionAbandoned");
        }
    });

    try {
        beaconManager.connect(new OnServiceBoundListener() {
            @Override
            public void onServiceBound() {
                try {
                    Region region = new Region(UUID.fromString("XXXX-XXX-..-...-XXX"), XXXX, XXX);
                    Set<Region> set = new HashSet();
                    set.add(region);
                    beaconManager.startMonitoring(set);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
        });
    } catch (RemoteException e) {
        throw new IllegalStateException(e);
    }
```

**Comment by dawidgdanski** [comment]
Hey @datasmurfen, manual interruptions in Bluetooth may cause the SDK to raise exceptions. You can, however, prevent the SDK from behaving this way. Register  either statically or dynamically the BroadcastReceiver intercepting connection state change broadcasts from BluetoothManager (http://developer.android.com/reference/android/bluetooth/BluetoothAdapter.html#STATE_CONNECTED). If the state switches to STATE_DISCONNECTING, it is a good moment to stop scanning. In the state STATE_CONNECTED you can enable scan again.

Hope that helps.

**Comment by datasmurfen** [comment]
@dawidgdanski 
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.le.BluetoothLeScanner.startScan(java.util.List, android.bluetooth.le.ScanSettings, android.bluetooth.le.ScanCallback)' on a null object reference
            at com.kontakt.sdk.android.factory.RunnersL$2.run(RunnersL.java:84)
            at com.kontakt.sdk.android.manager.MonitorController$Consumer.run(MonitorController.java:95)
            at java.lang.Thread.run(Thread.java:818)

It not solves my problem.

**Comment by dawidgdanski** [comment]
Hey @datasmurfen  unfortunately I am forced to ask you for patience. Primarily, We came up with the assumption that BeaconManager should work when Bluetooth is turned on without care of manual interruptions. Some enhancements to handle such situations will be implemented in next version with examples provided.

**Comment by datasmurfen** [comment]
Hello, @dawidgdanski , thanks for the headsup.   Do you have any ETA(F) because I am in the end of making a app with Beacons.

**Comment by dawidgdanski** [comment]
Hey @datasmurfen, new reelease should arrive in the middle of June.

**Comment by mail2bhramar** [comment]
Yes I am also come across the same issue.
Tried this code to handle this issue.

```
    @Override
    public void onReceive(Context arg0, Intent arg1) {
        final String action = arg1.getAction();
        if(action.equals(BluetoothAdapter.STATE_TURNING_OFF)){
            beaconManager.stopMonitoring();


        }
    }  
```

But getting the error 

java.lang.IllegalStateException: BT Adapter is not turned ON
            at android.bluetooth.le.BluetoothLeUtils.checkAdapterStateOn(BluetoothLeUtils.java:136)
            at android.bluetooth.le.BluetoothLeScanner.stopScan(BluetoothLeScanner.java:145)...

**Comment by datasmurfen** [comment]
Good to hear @dawidgdanski  . Please tag  us , and comment here as soon as the new release is out. Thank you! :)

**Comment by datasmurfen** [comment]
" Hey @datasmurfen, new reelease should arrive in the middle of June."
@dawidgdanski  it's soon  middle of Juli.

**Comment by kwanzen** [comment]
I am also waiting for the update since beginning of June.
Customers are waiting...

**Comment by dawidgdanski** [comment]
Hey @datasmurfen @mail2bhramar  @mrmilk90. We've released a new version of the SDK. The bug is fixed, please check our docs and sample application. Thanks for your contribution.
