### ISSUE TITLE
Quick start is waaaay out of date

### ISSUE THREAD

**Issue by RickRockholdMediafour** [kontaktio/kontakt-android-sdk#71]
The quickstart page (http://developer.kontakt.io/android-sdk/quickstart/) says the latest version is 1.0.6, even though 2.0 was released six months ago. Where can I find up-to-date examples?

**Comment by jakubkontakt** [comment]
Hi @RickRockhold 
Quickstart is available here http://developer.kontakt.io/android-sdk/2.0.0/quickstart/
