### ISSUE TITLE
Change Scan Period

### ISSUE THREAD

**Issue by logo17** [kontaktio/kontakt-android-sdk#73]
Hi, it is possible to change ScanPeriod after it have been set?

For example,  I have something like that:

new ScanContext.Builder()
                .setScanPeriod(new ScanPeriod(TimeUnit.SECONDS.toMillis(5), TimeUnit.SECONDS.toMillis(5)))
                .setIBeaconScanContext(new IBeaconScanContext.Builder()
                        .setIBeaconFilters(Collections.singleton(new ProximityUUIDFilter(UUID.fromString(uuid))))
                        .setEventTypes(EnumSet.of(EventType.DEVICES_UPDATE, EventType.SPACE_ABANDONED, EventType.SPACE_ENTERED))
                        .setRssiCalculator(RssiCalculators.newLimitedMeanRssiCalculator(5))
                        .build())
                .setScanMode(ProximityManager.SCAN_MODE_BALANCED)
                .build();

but, if an event occurs , I want to change the ScanPeriod in the ScanContext for something like that:

.setScanPeriod(new ScanPeriod(TimeUnit.SECONDS.toMillis(5), 0))

Thank you.

**Comment by jakubkontakt** [comment]
Hi @logo17 ScanContext is immutable object so any changes are not possible after creation.

Only way to change period is to build new ScanContext and call `restartScan()` with new scan context
