### ISSUE TITLE
IBeaconDevice constructor 

### ISSUE THREAD

**Issue by jbarmanet** [kontaktio/kontakt-android-sdk#75]
I need to use the Kontakt SDK only for writing new data to the beacons, all the scanning and ranging stuff is handled by another way.

Is it possible to build an IBeaconDevice object with the detected beacon characteristics, in order to use all the SyncableIBeaconConnection stuff ?

So far I saw that : 
An IBeaconDevice implements BeaconDevice...
And a BeaconDevice can be constructed with an IBeaconAdvertisingPacket...

But I'm unable to understand what is the minimal info it needs to be constructed... It would be great if you could give me some tips on this !

Thank you for your help !

**Comment by jakubkontakt** [comment]
Hi @jbarmanet 

`BeaconDevice` was not meant to be created outside the SDK. 

If you want only to use connection to beacon to manipulate its characteristics you can implement other interface `RemoteBluetoothDevice` on you own and pass object of that class to Connection class.

**Comment by jbarmanet** [comment]
Hi,

Ok, will go to do this by myself with BluetoothGatt...
However I encounter a first issue about writing data (writing the password) : it gives the following write error : GATT_INVALID_ATTRIBUTE_LENGTH 

My question is : what is the parameter value format expected by the Kontakt beacon device ?

Here is the code I'm using : 

```
UUID id_service = UUID.fromString("A1EA8130-0E1B-D4A1-B840-63F88C8DA1EA");
UUID id_level = UUID.fromString("A1EA8131-0E1B-D4A1-B840-63F88C8DA1EA");
BluetoothGattService service = gatt.getService(id_service);
BluetoothGattCharacteristic myChar = service.getCharacteristic(id_level);
String pwd = Utilities.asciiToHex("MumH"); // the resulting value is: 4d756d48  
myChar.setValue(pwd); 
gatt.writeCharacteristic(myChar);
```

Is there some kind of conversion to do prior to set the password value ?

Thank you for your help on this

JB

PS : for information I used the attributes addesses from this document http://developer.kontakt.io/beacon/kontakt-beacon-v2.pdf

**Comment by jakubkontakt** [comment]
Try passing passing password as `bytes[]` instead of hex value.

**Comment by jbarmanet** [comment]
Thank you it worked !
For whom it may help, I used the method described here to transform the hex string value to bytes[] : 
http://stackoverflow.com/a/18714790/1720332
