### ISSUE TITLE
Beacon not always recognized

### ISSUE THREAD

**Issue by matrazorleg** [kontaktio/kontakt-android-sdk#76]
Hello,

I've set the scanContext as below:

``` Java
scanContext = new ScanContext.Builder()
                .setScanMode(ProximityManager.SCAN_MODE_BALANCED)
                .setScanPeriod(new ScanPeriod(TimeUnit.SECONDS.toMillis(5), TimeUnit.SECONDS.toMillis(2)))
                .setForceScanConfiguration(ForceScanConfiguration.DEFAULT)
                .setActivityCheckConfiguration(ActivityCheckConfiguration.DEFAULT)
                .setIBeaconScanContext(new IBeaconScanContext.Builder()
                                .setEventTypes(EnumSet.of(EventType.DEVICE_DISCOVERED, EventType.DEVICE_LOST))
                                .setRssiCalculator(RssiCalculators.newLimitedMeanRssiCalculator(5))
                                .setDevicesUpdateCallbackInterval(TimeUnit.SECONDS.toMillis(2))
                                .setDistanceSort(DistanceSort.DESC)
                                .setIBeaconFilters(Arrays.asList(
                                        new IBeaconFilter() {
                                            @Override
                                            public boolean apply(IBeaconAdvertisingPacket iBeaconAdvertisingPacket) {
                                                return iBeaconAdvertisingPacket.getProximity() == Proximity.IMMEDIATE || iBeaconAdvertisingPacket.getProximity() == Proximity.NEAR;
                                            }
                                        },
                                        IBeaconFilters.newMajorFilter(34)
                                ))
                                .build()
                )
                .build();
```

but the beacons not always are recognized by my application, i've 6 beacon placed in the same area and i expect to view all of them, but sometimes i get 3 devices, sometimes i get 2 devices and so on.

How can i change my scanContext for getting better performance? I'm doing anything wrong?

Thank you.

**Comment by jakubkontakt** [comment]
Have you tried to disable IBeaconFilter which filters beacons based on Proximity? 

> ```
> return iBeaconAdvertisingPacket.getProximity() == Proximity.IMMEDIATE || iBeaconAdvertisingPacket.getProximity() == Proximity.NEAR;
> ```

Snippet above will only return beacons which are NEAR or IMMEDIATE .

Bluetooth signal may fluctuate and thus the signal might be too low for some of beacons, so their Proximity will not be NEAR or IMMEDIATE. 

Could you also post following details:
- Android OS Version
- Device Model
- Beacons TX Power
- Beacons Advertising Interval

**Comment by matrazorleg** [comment]
I deleted that line of code and the situation is getting better. But sometimes one or two beacons are not detected correctly.

My device is a ASUS ZenPad10, with Android 5.0.2 and the beacons are set with the default profile.

**Comment by Washisama** [comment]
We are using the default method in order to detect Kontakt beacons but on some android devices, Kontakt beacons (there is around 30 of them in a range of max 1 meter) are simply not detected.

Is there anything we can do to have the guarantee to detect them all?

It occures on :

Huawei P9 Light
Android 6.0

One Plus 3
Android 7.1.1
