### ISSUE TITLE
Device found but not recognized as Beacon

### ISSUE THREAD

**Issue by MasterAsI** [kontaktio/kontakt-android-sdk#77]
When I'm scanning for beacons in the logcat I see these messages:

```
D/kontakt.io SDK: Device discovered ZZ:ZZ:ZZ:ZZ:ZZ:ZZ
D/kontakt.io SDK: Device found but not recognized as Beacon [name: Kontakt, address: ZZ:ZZ:ZZ:ZZ:ZZ:ZZ]
```

I'm using device with Bluetooth 3.0, API level 19 and your iBeacon.  Here is part of my code:

```
        ProximityManager beaconManager = new ProximityManager(this);

        ScanContext scanContext = new ScanContext.Builder()
                .setScanPeriod(new ScanPeriod(TimeUnit.SECONDS.toMillis(5),
                                              TimeUnit.SECONDS.toMillis(2)))
                .setIBeaconScanContext(new IBeaconScanContext.Builder()
                      .setEventTypes(Arrays.asList(
                              EventType.SPACE_ENTERED,
                              EventType.SPACE_ABANDONED,
                              EventType.DEVICE_DISCOVERED))
                      .setRssiCalculator(RssiCalculators.newLimitedMeanRssiCalculator(5))
                      .setDevicesUpdateCallbackInterval(TimeUnit.SECONDS.toMillis(2))
                      .setDistanceSort(DistanceSort.ASC)
                      .build())
                .setForceScanConfiguration(ForceScanConfiguration.DEFAULT)
                .setActivityCheckConfiguration(ActivityCheckConfiguration.DEFAULT)
                .setScanMode(ProximityManager.SCAN_MODE_BALANCED)
                .build();

        beaconManager.initializeScan(scanContext, new OnServiceReadyListener() {
            @Override
            public void onServiceReady() {
                beaconManager.attachListener(MainActivity.this);
            }

            @Override
            public void onConnectionFailure()
            { }
        });
```

**Comment by jakubkontakt** [comment]
Hi @MasterAsI Could you tell me what is the profile of beacon? Is it iBeacon or Eddystone?

**Comment by MasterAsI** [comment]
@jakubkontakt, I'm so sorry, I made a mistake. I'm using a device with Bluetooth 3.0 instead of 4.0, API level 19. After adding `EddystoneScanContext` problem still exist. In the device's micro scheme written "Beacon v2.2"

**Comment by MasterAsI** [comment]
@jakubkontakt, my problem is not resolved. If the device has API level 18+ and has Bluetooth version < than 4.0 should your SDK work with beacons?

**Comment by jakubkontakt** [comment]
No, since Bluetooth Low Energy starts with 4.0

**Comment by MasterAsI** [comment]
@jakubkontakt, my device runs on 19th version of API with Bluetooth 3.0, but `getPackageManager().hasSystemFeature(PackageManager.FEATURE_BLUETOOTH_LE);` returns `true`. Is it system bug or this is should be? Because I don't know how to validate device in another way...

**Comment by jakubkontakt** [comment]
It seems like a bug in device, but could you please post name of your device? And as well you can add to your <b>AndroidManifest.xml</b> following tag:

```
<uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>
```

Change true to false if BLE is not crucial to your app, otherwise leave it as is.
