### ISSUE TITLE
Scan failed - internal error.

### ISSUE THREAD

**Issue by jcyu0208** [kontaktio/kontakt-android-sdk#79]
I'm testing on a Nexus 7 Android 5.1 and I can't seem to get the sdk to work properly.

Sequence of events are as follows based on logs from Kontakt SDK
- Starting scan (force) 
- Sleep during active period: 1000
- **Scan failed - internal error**
- Stopping scan (force)

It's a bit hard to debug the SDK at this point since it doesn't provide more information regarding the problem. We've tested on other device and android sdk configuration combinations and so far they've been working just fine, so it might not be a configuration issue.

Please advise.

**EDIT**

Tried using the admin application and it was not showing the Scan Failed error, but it wasn't detecting the beacons either.

I also keep getting this:
BluetoothLeScanner: could not find callback wrapper

**Comment by jakubkontakt** [comment]
Hi @jcyu0208 

Unfortunately Nexus 7 is known to has really poor Bluetooth performance.

Error, you have spotted: 

> <b>Scan Failed - internal error</b>

is caused not by our code but by Android OS, which is

> public static final int SCAN_FAILED_INTERNAL_ERROR
> Added in API level 21
> Fails to start scan due an internal error

Constant Value: 3 (0x00000003)

Docs link: http://developer.android.com/reference/android/bluetooth/le/ScanCallback.html#SCAN_FAILED_INTERNAL_ERROR

Documentation lacks about details what is the source of that error, but reading through <b><a href="https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/bluetooth/le/BluetoothLeScanner.java">BluetoothLeScanner</a></b> source code it seems that this error is returned in following cases:
- Calling method startScan on <b>BluetoothLeScanner</b>

> ```
>  if (gatt == null) {
>     postCallbackError(callback, ScanCallback.SCAN_FAILED_INTERNAL_ERROR);
>     return;
>  }
> ```
-  During registration

> ```
> catch (InterruptedException | RemoteException e) {
>     Log.e(TAG, "application registeration exception", e);
>     postCallbackError(mScanCallback, ScanCallback.SCAN_FAILED_INTERNAL_ERROR);
> }
> ```

So, could you post your ScanContext configuration?

**Comment by psam44** [comment]
Could this issue be open again? I have this problem.
Nexus 7 Android 5.1.1
SDK 3.3.1

Log:
06-14 15:53:20.189 32709-325/com.ices D/kontakt.io SDK: Starting monitoring
06-14 15:53:20.202 32709-324/com.ices D/kontakt.io SDK: Start Scan
06-14 15:53:20.205 32709-32762/com.ices I/ReactNativeJS: { status: 'START' }
06-14 15:53:20.205 32709-32762/com.ices I/ReactNativeJS: START
06-14 15:53:20.207 32709-32709/com.ices D/kontakt.io SDK: ProximityService Message received.
06-14 15:53:20.207 32709-324/com.ices D/kontakt.io SDK: On Monitor started
06-14 15:53:20.207 32709-32709/com.ices D/kontakt.io SDK: ProximityService MESSAGE_ATTACH_MONITORING_LISTENER
06-14 15:53:20.207 32709-32709/com.ices D/kontakt.io SDK: MonitoringListener registered: 46653846
06-14 15:53:20.207 32709-32709/com.ices D/kontakt.io SDK: Scan failed - internal error
06-14 15:53:20.207 32709-32709/com.ices D/kontakt.io SDK: Scan failed - internal error
06-14 15:53:20.208 32709-324/com.ices D/kontakt.io SDK: ForceScanController not enabled
06-14 15:53:20.208 32709-32763/com.ices D/ListenerManager: onMonitoringCycleStart
06-14 15:53:20.210 32709-32762/com.ices I/ReactNativeJS: { status: 'START' }
06-14 15:53:20.210 32709-32762/com.ices I/ReactNativeJS: START

06-14 15:53:28.190 32709-325/com.ices D/kontakt.io SDK: : Stopping monitoring
06-14 15:53:28.190 32709-324/com.ices D/kontakt.io SDK: ForceScanController not enabled
06-14 15:53:28.191 32709-324/com.ices D/kontakt.io SDK: Stopping scan
06-14 15:53:28.193 32709-324/com.ices D/BluetoothLeScanner: could not find callback wrapper
06-14 15:53:28.193 32709-324/com.ices D/kontakt.io SDK: On monitor stopped
06-14 15:53:28.194 32709-32763/com.ices D/ListenerManager: onMonitoringCycleStop
06-14 15:53:28.200 32709-32762/com.ices I/ReactNativeJS: { status: 'STOP' }
06-14 15:53:28.200 32709-32762/com.ices I/ReactNativeJS: STOP

06-14 15:53:58.190 32709-325/com.ices D/kontakt.io SDK: Starting monitoring
06-14 15:53:58.191 32709-324/com.ices D/kontakt.io SDK: Start Scan
06-14 15:53:58.192 32709-324/com.ices D/kontakt.io SDK: On Monitor started
06-14 15:53:58.192 32709-32709/com.ices D/kontakt.io SDK: Scan failed - internal error
06-14 15:53:58.193 32709-324/com.ices D/kontakt.io SDK: ForceScanController not enabled
06-14 15:53:58.193 32709-32763/com.ices D/ListenerManager: onMonitoringCycleStart
06-14 15:53:58.196 32709-32762/com.ices I/ReactNativeJS: { status: 'START' }
06-14 15:53:58.196 32709-32762/com.ices I/ReactNativeJS: START

06-14 15:54:06.190 32709-325/com.ices D/kontakt.io SDK: : Stopping monitoring
...
The problem should be in startScan():
            try {
                gatt = mBluetoothManager.getBluetoothGatt();
            } catch (RemoteException e) {
                gatt = null;
            }
            if (gatt == null) {
                postCallbackError(callback, ScanCallback.SCAN_FAILED_INTERNAL_ERROR);

getBluetoothGatt() can potentially return null, so there may be no exception.

My scanContext is: default + ScanPeriod.MONITORING + monitoringEnabled false
No Filters, no Spaces, a SpaceListener, a ScanStatusListener
Developed as a module in react-native 0.45 (only Android part so far)

**Comment by psam44** [comment]
My device is a 2012 Nexus 7, and it seems Google did not enable BLE (although the chipset is capable)
https://stackoverflow.com/questions/20669590/ble-on-nexus-7-me370t-with-android-4-4-2

**Comment by psam44** [comment]
Confirmed:
```
PackageManager pm = reactContext.getPackageManager();
boolean hasBLE = pm.hasSystemFeature(PackageManager.FEATURE_BLUETOOTH_LE);
Log.d(TAG, "supports BLE: " + hasBLE); // false
Log.d(TAG, "supports BT: "
 + pm.hasSystemFeature(PackageManager.FEATURE_BLUETOOTH)); // true
```
To discard inadequate devices, it may be useful to add in the AndroidManifest.xml:
`<uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>`

It would be useful to add these notes in your https://developer.kontakt.io/android-sdk/quickstart/
