### ISSUE TITLE
onBeaconAppeared() is not calling every time even if my beacon is in within the range.

### ISSUE THREAD

**Issue by mail2bhramar** [kontaktio/kontakt-android-sdk#8]
I am using your Kontakt(Android) SKD Version 1.0.6. In my Service class  I implemented BeaconManager.MonitoringListener. The issue is   onMonitorStart() and onMonitorStop() is calling every time but onBeaconAppeared() is not calling every time even if my beacon is in within the range.so please provide me some solution to overcome this issue.

**Comment by dawidgdanski** [comment]
onMonitorStart() and monitorStop() are bound with MonitorPeriod. onBeaconAppeared() is called when the beacon appears for the first time and it is called once. Beacons that appeared are notified via onBeaconsUpdated().

**Comment by mail2bhramar** [comment]
Yes @dawidgdanski .Even if a new Beacon within the range, it is also not calling onBeaconAppeared() method.

**Comment by dawidgdanski** [comment]
Could you please provide some code?
