### ISSUE TITLE
Packet loss from Beacons. Identical data from Beacons.

### ISSUE THREAD

**Issue by Lokk1** [kontaktio/kontakt-android-sdk#81]
Hello company kontakt.io. 
We have a problem with your android sdk. In our office we use your kontakt smart beacons that broadcast every 200ms. We previously used our decision but we have a problem with lost package. Packet loss is about 60-70 percent. (We use the constant method stop and start the beacon scanner with the timer). Learning that you have solved the problem with the loss of packages we have decided to use your SDK. Scanning was done by your Monitoring example. But there is a problem with the data we receive through your SDK. Below is a log file:
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 7427, 7427, -80.0, 1453279250879, NEAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 7427, 7427, -80.0, 1453279250879, NEAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 54367, 54367, -78.0, 1453279250911, NEAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 7427, 7427, -80.0, 1453279250879, NEAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 54367, 54367, -78.0, 1453279250911, NEAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 36458, 36458, -78.0, 1453279250949, NEAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 7427, 7427, -80.0, 1453279250879, NEAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 54367, 54367, -78.0, 1453279250911, NEAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 36458, 36458, -78.0, 1453279250949, NEAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 41160, 41160, -86.0, 1453279251256, FAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 7427, 7427, -80.0, 1453279250879, NEAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 54367, 54367, -78.0, 1453279250911, NEAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 36458, 36458, -78.0, 1453279250949, NEAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 41160, 41160, -86.0, 1453279251256, FAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 33855, 33855, -88.0, 1453279251752, NEAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 7427, 7427, -80.0, 1453279250879, NEAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 54367, 54367, -78.0, 1453279250911, NEAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 36458, 36458, -78.0, 1453279250949, NEAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 41160, 41160, -86.0, 1453279251256, FAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 33855, 33855, -88.0, 1453279251752, NEAR
f7826da6-4fa2-4e98-8024-bc5b71e0893e, 7427, 7427, -80.0, 1453279250879, NEAR
Sequence data: UUID, MAJOR, MINOR, RSSI, TIMESTAMP, PROXIMITY.
From this log can be seen that during the scanning does not change the rssi value and timestamp value. He have some questions.
Why is your SDK gives us the same data?
Maybe your SDK does not solve the problem of packet loss if the beacons broadcast very often, for example every 200 milliseconds? 
Maybe need more global settings for your scanner?
Is it possible to solve our problem with the loss of packages by your SDK?

BeaconManager we created with this settings:

_beaconManager = BeaconManager.newInstance(_context);
        _beaconManager.registerMonitoringListener(this);
        _beaconManager.setForceScanConfiguration(beaconSettings.getForceScanConfiguration());
        _beaconManager.setScanMode(beaconSettings.getScanMode().getScanModeCode());
        _beaconManager.setMonitorPeriod(beaconSettings.getMonitorPeriod());
       _beaconManager.setBeaconActivityCheckConfiguration(beaconSettings.getBeaconActivityCheckConfiguration());

ForceScanConfiguration - DEFAULT
MonitorPeriod - DEFAULT

Can you explain why ForceScan Active Period can not enlarge 700ms?
Can you explain why ForceScan Passive Period can not enlarge 300ms?
Can you explain why Monitor Active Period and Monitor Passive Period can not enlarge 5000ms?

Best regards, Artiom Levshuk.

**Comment by jakubkontakt** [comment]
Hi @Lokk1 

What is the version of SDK that you are using? 
Latest version is 2.0.1.

**Comment by Lokk1** [comment]
Our version is 1.0.6
22 янв. 2016 г. 13:04 пользователь "jakubkontakt" notifications@github.com
написал:

**Comment by jakubkontakt** [comment]
We are not supporting anymore SDK 1.0.x, please update to 2.0.1 your dependencies.

**Comment by jakubkontakt** [comment]
As this issue is related to outdated sdk version, I am closing this issue. If this bug still happens please open new issue.
