### ISSUE TITLE
2.1.0 - Gradle / Android Studio can't find the repo

### ISSUE THREAD

**Issue by ignitiongit** [kontaktio/kontakt-android-sdk#83]
Seems like there's some naming issue with the jar files.

Android studio says it cant find x2.1.0.jar 

But the file in your repo says x-2.1.0.jar 

Is that a gradle/android studio issue on our end?

**Comment by jakubkontakt** [comment]
If you are using gradle, now it is supposed to work. Remember to add our repository:

```
maven { url 'http://repo.kontakt.io/repository/internal/' }
```
