### ISSUE TITLE
Unrecoverable error when Bluetooth is off and scanning is started

### ISSUE THREAD

**Issue by jcyu0208** [kontaktio/kontakt-android-sdk#85]
If scanning is initialized with the Bluetooth turned off, we get an exception inside ScanController.Consumer which triggers a log of:

"Force scan interrupted, exception swallowed"

Upon investigating, this is primarily caused by a null pointer exception because the Bluetooth was not turned on. Is this by design? Does this mean we have to listen to Bluetooth Adapter state changes and reinitialize scanning to avoid this?

**Comment by michaldrabik** [comment]
Closing as I was not with Kontakt.io when this was issued. Feel free to reopen if necessary.
