### ISSUE TITLE
SPACE_ABANDONED not firing when monitoring

### ISSUE THREAD

**Issue by simongarnier** [kontaktio/kontakt-android-sdk#86]
With a `ScanPeriod` setup with an active and passive period of 10 second, `SPACE_ABANDONED` will **only** fire if `SPACE_ENTERED` as been fired in the same active period. We suspect that spaces are forgotten when the `KontaktProximityManager` switches to passive. 

Any insight? We need this event to be reliably fired, independently of the `ScanPeriod`. Is this possible?

**Comment by andschdk** [comment]
I am experiencing the same behaviour:
`03-04 08:18:18.317 29512-29671/xxx D/BackgroundScanService: Scan started
03-04 08:18:20.016 29512-29512/xxx D/BackgroundScanService: Space entered - Major: 2
03-04 08:18:33.318 29512-29671/xxx D/BackgroundScanService: Scan stopped`
TURN OFF beacon here
`03-04 08:18:43.338 29512-29671/xxx D/BackgroundScanService: Scan started
03-04 08:18:58.334 29512-29671/xxx D/BackgroundScanService: Scan stopped`
Space is never abandoned.

This is my scan context:

`````` java
List<EventType> eventTypes = Arrays.asList(EventType.SPACE_ENTERED, EventType.SPACE_ABANDONED);

        ScanContext scanContext = new ScanContext.Builder()
                .setScanPeriod(new ScanPeriod(TimeUnit.SECONDS.toMillis(15), TimeUnit.SECONDS.toMillis(10))) // monitoring for 15 seconds scan and 10 seconds waiting
                .setScanMode(ProximityManager.SCAN_MODE_BALANCED)
                .setActivityCheckConfiguration(ActivityCheckConfiguration.MINIMAL)
                .setForceScanConfiguration(ForceScanConfiguration.MINIMAL)
                .setIBeaconScanContext(new IBeaconScanContext.Builder().setEventTypes(eventTypes).setIBeaconRegions(getRegions()).build())
                .setEddystoneScanContext(null)
                .setForceScanConfiguration(ForceScanConfiguration.MINIMAL)
                .build();```
``````

**Comment by michaldrabik** [comment]
@simongarnier @andschdk Version 2.1.2 of the SDK has been released and this bug should be resolved now. Feel free to check it out: https://github.com/kontaktio/kontakt-android-sdk
