### ISSUE TITLE
Get beacons list in onEvent

### ISSUE THREAD

**Issue by emacaste** [kontaktio/kontakt-android-sdk#88]
Hi, i do not understand how to get beacons list inside onEvent callback, like iOS's - `(void)beaconManager:(KTKBeaconManager *)manager didRangeBeacons:(NSArray <CLBeacon *> *)beacons inRegion:(__kindof KTKBeaconRegion *)region ;` do.

I would set one region with only UUID and let the major and minor be detected from webserver's beacons array populated by my custom backend.

I can't hardcode every single beacon UUID major minor (i have a lot) in the ScanContextBuilder.

How can i do that?

**Comment by michaldrabik** [comment]
@beniaminorossini If I understand the problem correctly **Filtering** is what you need. You can read more about filtering [HERE](http://developer.kontakt.io/android-sdk/2.1.0/quickstart/#basic-usage-filtering). Basically what you need to do is to set a ProximityUUIDFilter with your UUID and only Beacons with given UUID will be returned in onEvent callback. To retreive list of devices use 

```
@Override
public void onEvent(BluetoothDeviceEvent bluetoothDeviceEvent) {
  List<? extends RemoteBluetoothDevice> deviceList = bluetoothDeviceEvent.getDeviceList(); 
}
```

**Comment by emacaste** [comment]
Ok, i have misunderstood difference between regions and filters.
Everythings works well now.
Thx
