### ISSUE TITLE
BeaconID coming null

### ISSUE THREAD

**Issue by gsandeep100** [kontaktio/kontakt-android-sdk#96]
I am using the shuffling and trying to fetch the new Major/Minor and also Becon ID using Android SDK in my Application using firmware 4.
I am not able to fetch the latest Major/Minor rather its returning me the old Major/Minor and BeconID is coming as null..Please suggest

**Comment by michaldrabik** [comment]
@gsandeep100 Make sure you are using `KontaktProximityManager` not `ProximityManager` (more on the topic here: http://developer.kontakt.io/android-sdk/2.1.0/quickstart/#security-shuffling). Also if by "BeaconID" you mean Unique ID (4 digits code), then be aware that it is not transmited while the beacon is shuffled.

**Comment by gsandeep100** [comment]
Hi,
    Thanks for the response.I have a further question is that how i am going to
differentiate between Beacons..Which unique id i can use to differentiate
between beacons using the sdk...

Thanks
Sandeep

On Mon, Mar 14, 2016 at 3:57 PM, Michal Drabik notifications@github.com
wrote:

> @gsandeep100 https://github.com/gsandeep100 Make sure you are using
> KontaktProximityManager not ProximityManager (more on the topic here:
> http://developer.kontakt.io/android-sdk/2.1.0/quickstart/#security-shuffling).
> Also if by "BeaconID" you mean Unique ID (4 digits code), then be aware
> that it is not transmited while the beacon is shuffled.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kontaktio/kontakt-android-sdk/issues/96#issuecomment-196351440
> .

## 

"Kind words can be short and easy to speak,
but their echoes are truly endless."
Mother Teresa

**Comment by gsandeep100** [comment]
and one more question is that Major and Minor is not Changing when we use Android SDK.....
