### ISSUE TITLE
need help SDK integration with mobile apps - Android   and IOS

### ISSUE THREAD

**Issue by SubodhSaini** [kontaktio/kontakt-android-sdk#97]
Actually I am building an app for the purpose of marketing promotions based on location.. For an example , If mobile app user enters to a particular location where beacon are tagged to that location. As soon mobile come in beacon proximity area, mobile app will detect the beacon and based on beacon id, back end application can trigger the promotions to users.
I know Kontakt.io SDK has broader use for different business however I am seeking the targeted method/classes in provided SDK(iOS and Adnroid) to support the above business case.

**Comment by michaldrabik** [comment]
@SubodhSaini Everything you need to create your application is described in our SDK Quickstart (http://developer.kontakt.io/android-sdk/2.1.0/quickstart/#basic-usage-ranging-monitoring-beacons). Ranging and Monitoring section. We can't write code for you, though :)
