### ISSUE TITLE
Beacon detection not happening in some devices like micromax and lenova

### ISSUE THREAD

**Issue by subbu1234** [kontaktio/kontakt-android-sdk#98]
We identified that beacon detection not happening in the following devices with Kontakt.io sdk 2.1.1.
Following are details about the devices.
Micromax: 
   Android version 4.4.2
Kernel version 3.4.67
Build Number: ALPS.KK1.MP1.V2.10
Model number: micromax A290

Lenovo:
   Android version 4.4.2
   Build number: S820_ROW_S222_141121
   Model Number: Lenovo S820
While debugging the code we observed that onEvent(BluetoothDeviceEvent bluetoothDeviceEvent) not firing . Please provide solution . Thanks in advance.

**Comment by michaldrabik** [comment]
Does your code work on any other device different than these two?

**Comment by subbu1234** [comment]
We tested with the following devices its working well.
Nexus:
Android version 4.4.4
Build number: KTU84Q
Kernel version: 3.4.0-gd59db4e
Model Number: Nexus 5

Samsung:
Android version 4.4.2
Build number: KOT49H.G800HXXU1ANL2
Kernel version: 3.4.0-3650868
Model Number: Nexus 5

**Comment by subbu1234** [comment]
Can you please provide solution? Very urgent for us (our clients waiting).
Thanks and regards,
subbu

**Comment by michaldrabik** [comment]
@subbu1234 Sorry for the delay. Unfortunately the BLE on Android is very immature, especially on lower-end devices and older systems (like 4.4.2, 4.4.4). As you can see your code works well on Nexus 5 but not so good on less popular devices like Micromax. My advice is to update Android OS to 5.0 or higher and see if that helps - BLE works better on 5.0+ systems.
